!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : BESS_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE BESS_1Dyn(PQref)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakDyn      ! 
!     SUBR    FFT_ModDyn    ! 
!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    REALPOLE      ! Real Pole
!     SUBR    PWM_3LevelDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: PQref(2)

! Electrical Node Indices

! Control Signals
      INTEGER  MCB_DRV1, UFP5, UFP4, UFP3, UFP2
      INTEGER  OFP3, OFP2, OFP1, UFP1, UFP5Timems
      INTEGER  UFP4Timems, UFP3Timems, OFP3Timems
      INTEGER  OFP2Timems, OFP1Timems, UFP2Timems
      INTEGER  UFP1Timems, UVP4Timems, UVP3Timems
      INTEGER  UVP4, UVP3, OVP4, OVP3, OVP2, OVP1
      INTEGER  UVP2, UVP1, UVP1Timems, UVP2Timems
      INTEGER  OVP4Timems, OVP3Timems, OVP2Timems
      INTEGER  OVP1Timems, MCB_DRV, spov_trip
      INTEGER  OCP_ENx, PWM_EN1, RPWM_EN, SPWM_EN
      INTEGER  TPWM_EN, MCB_DRV2, DampCoft
      INTEGER  VgridHpfFreq, JCoft, SclToBess
      INTEGER  CommandWord, SetupWord, IT_1
      INTEGER  spov_gblock, oc_block
      REAL     PWMDRV1(12), Vab0, Vbc0, RT_1
      REAL     RT_2, RT_3, RT_4, RT_5, RT_6, RT_7
      REAL     Grd_Vdc1, Grd_Vdc2, Ibat1, Vca0
      REAL     RT_8(3), RT_9(4), RT_10(4)
      REAL     RT_11(4), RT_12(4), RT_13(4)
      REAL     RT_14(4), DCC_SS_EN1, DCC_EN1
      REAL     ACSSC_DRV1, RT_15(3), Ug_rms_LV(3)
      REAL     RT_16, RT_17, RT_18, RT_19, RT_20
      REAL     RT_21, Bat_SOC, Grd_Ia1, Grd_Ib1
      REAL     RT_22(2), RT_23(3), Triasign, Qref
      REAL     RT_24, RT_25, RT_26, RT_27, RT_28
      REAL     RT_29, FrequenceTripTh(8)
      REAL     FrequenceTripTime(8)
      REAL     VoltageTripTh(8)
      REAL     VoltageTripTime(8), MCB_DRVx
      REAL     RT_30, RT_31, RT_32, RT_33, RT_34
      REAL     RT_35, RT_36, RT_37, RT_38, Tocp
      REAL     Socp, OCP_EN, Rocp, PWM1_EN(4)
      REAL     VoltSet, FreqSet, TP_ic, TP_ib
      REAL     TP_ia, Tsample, DebugData2(16)
      REAL     DebugData1(16), PWM_EN(4)
      REAL     Duty_M4(3), Duty_M3(3), Duty_M2(3)
      REAL     Duty_M1(3), DCSSC_DRV(4)
      REAL     DCC_DRV(4), ACSSC_DRV(4)
      REAL     ACM_DRV(4), BattMeas(3)
      REAL     PQRefSet(2), CapCur(2)
      REAL     ModuleCur(3), BusVolt(2)
      REAL     GridVolt(2), EN_inv_bk, PWM_EN1x
      REAL     EN_inv, vc_inv, RT_39, vb_inv
      REAL     RT_40, va_inv, RT_41, BatVolt
      REAL     ia_inv_dc, Duty_M1C, Grd_Icc1
      REAL     ib_inv_dc, Duty_M1B, Grd_Ibc1
      REAL     ic_inv_dc, Duty_M1A, Grd_Iac1
      REAL     Qmeas, TP_iS(3), Vabc1(3)
      REAL     AMC_DRV1, AMC_DRV2, AMC_DRV3
      REAL     AMC_DRV4, DCC_EN2, DCC_EN3
      REAL     DCC_EN4, DCC_SS_EN2, DCC_SS_EN3
      REAL     ACSSC_DRV2, ACSSC_DRV3, ACSSC_DRV4
      REAL     PWM_EN2, PWM_EN3, PWM_EN4
      REAL     PQ_pos(2), IPQ_pos(2), Pref, Qref1
      REAL     TP_iG(3), Bat_SOC2

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD1_2, RVD2_1(2), RVD1_3
      REAL     RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ICX, IPGB                           ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 50
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 270
      IPGB      = NPGB
      NPGB      = NPGB + 97
      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 50
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 62

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vab0     = STOF(ISTOF + 15)
      Vbc0     = STOF(ISTOF + 16)
      RT_1     = STOF(ISTOF + 17)
      RT_2     = STOF(ISTOF + 18)
      RT_3     = STOF(ISTOF + 19)
      RT_4     = STOF(ISTOF + 20)
      RT_5     = STOF(ISTOF + 21)
      RT_6     = STOF(ISTOF + 22)
      RT_7     = STOF(ISTOF + 23)
      Grd_Vdc1 = STOF(ISTOF + 24)
      Grd_Vdc2 = STOF(ISTOF + 25)
      Ibat1    = STOF(ISTOF + 26)
      Vca0     = STOF(ISTOF + 27)
      DCC_SS_EN1 = STOF(ISTOF + 55)
      DCC_EN1  = STOF(ISTOF + 56)
      ACSSC_DRV1 = STOF(ISTOF + 57)
      RT_16    = STOF(ISTOF + 64)
      RT_17    = STOF(ISTOF + 65)
      RT_18    = STOF(ISTOF + 66)
      RT_19    = STOF(ISTOF + 67)
      MCB_DRV1 = STOI(ISTOI + 1)
      RT_20    = STOF(ISTOF + 68)
      RT_21    = STOF(ISTOF + 69)
      Bat_SOC  = STOF(ISTOF + 70)
      Grd_Ia1  = STOF(ISTOF + 71)
      Grd_Ib1  = STOF(ISTOF + 72)
      Triasign = STOF(ISTOF + 78)
      Qref     = STOF(ISTOF + 79)
      RT_24    = STOF(ISTOF + 80)
      RT_25    = STOF(ISTOF + 81)
      RT_26    = STOF(ISTOF + 82)
      RT_27    = STOF(ISTOF + 83)
      RT_28    = STOF(ISTOF + 84)
      RT_29    = STOF(ISTOF + 85)
      UFP5     = STOI(ISTOI + 2)
      UFP4     = STOI(ISTOI + 3)
      UFP3     = STOI(ISTOI + 4)
      UFP2     = STOI(ISTOI + 5)
      OFP3     = STOI(ISTOI + 6)
      OFP2     = STOI(ISTOI + 7)
      OFP1     = STOI(ISTOI + 8)
      UFP1     = STOI(ISTOI + 9)
      UFP5Timems = STOI(ISTOI + 10)
      UFP4Timems = STOI(ISTOI + 11)
      UFP3Timems = STOI(ISTOI + 12)
      OFP3Timems = STOI(ISTOI + 13)
      OFP2Timems = STOI(ISTOI + 14)
      OFP1Timems = STOI(ISTOI + 15)
      UFP2Timems = STOI(ISTOI + 16)
      UFP1Timems = STOI(ISTOI + 17)
      UVP4Timems = STOI(ISTOI + 18)
      UVP3Timems = STOI(ISTOI + 19)
      UVP4     = STOI(ISTOI + 20)
      UVP3     = STOI(ISTOI + 21)
      OVP4     = STOI(ISTOI + 22)
      OVP3     = STOI(ISTOI + 23)
      OVP2     = STOI(ISTOI + 24)
      OVP1     = STOI(ISTOI + 25)
      UVP2     = STOI(ISTOI + 26)
      UVP1     = STOI(ISTOI + 27)
      UVP1Timems = STOI(ISTOI + 28)
      UVP2Timems = STOI(ISTOI + 29)
      OVP4Timems = STOI(ISTOI + 30)
      OVP3Timems = STOI(ISTOI + 31)
      OVP2Timems = STOI(ISTOI + 32)
      OVP1Timems = STOI(ISTOI + 33)
      MCB_DRV  = STOI(ISTOI + 34)
      MCB_DRVx = STOF(ISTOF + 118)
      spov_trip = STOI(ISTOI + 35)
      RT_30    = STOF(ISTOF + 119)
      RT_31    = STOF(ISTOF + 120)
      RT_32    = STOF(ISTOF + 121)
      RT_33    = STOF(ISTOF + 122)
      RT_34    = STOF(ISTOF + 123)
      RT_35    = STOF(ISTOF + 124)
      RT_36    = STOF(ISTOF + 125)
      RT_37    = STOF(ISTOF + 126)
      RT_38    = STOF(ISTOF + 127)
      Tocp     = STOF(ISTOF + 128)
      Socp     = STOF(ISTOF + 129)
      OCP_ENx  = STOI(ISTOI + 36)
      OCP_EN   = STOF(ISTOF + 130)
      Rocp     = STOF(ISTOF + 131)
      PWM_EN1  = STOI(ISTOI + 37)
      RPWM_EN  = STOI(ISTOI + 38)
      SPWM_EN  = STOI(ISTOI + 39)
      TPWM_EN  = STOI(ISTOI + 40)
      MCB_DRV2 = STOI(ISTOI + 41)
      VoltSet  = STOF(ISTOF + 136)
      FreqSet  = STOF(ISTOF + 137)
      DampCoft = STOI(ISTOI + 42)
      VgridHpfFreq = STOI(ISTOI + 43)
      JCoft    = STOI(ISTOI + 44)
      TP_ic    = STOF(ISTOF + 138)
      TP_ib    = STOF(ISTOF + 139)
      TP_ia    = STOF(ISTOF + 140)
      SclToBess = STOI(ISTOI + 45)
      Tsample  = STOF(ISTOF + 141)
      CommandWord = STOI(ISTOI + 46)
      SetupWord = STOI(ISTOI + 47)
      IT_1     = STOI(ISTOI + 48)
      EN_inv_bk = STOF(ISTOF + 220)
      PWM_EN1x = STOF(ISTOF + 221)
      EN_inv   = STOF(ISTOF + 222)
      vc_inv   = STOF(ISTOF + 223)
      RT_39    = STOF(ISTOF + 224)
      vb_inv   = STOF(ISTOF + 225)
      RT_40    = STOF(ISTOF + 226)
      va_inv   = STOF(ISTOF + 227)
      RT_41    = STOF(ISTOF + 228)
      BatVolt  = STOF(ISTOF + 229)
      ia_inv_dc = STOF(ISTOF + 230)
      Duty_M1C = STOF(ISTOF + 231)
      Grd_Icc1 = STOF(ISTOF + 232)
      ib_inv_dc = STOF(ISTOF + 233)
      Duty_M1B = STOF(ISTOF + 234)
      Grd_Ibc1 = STOF(ISTOF + 235)
      ic_inv_dc = STOF(ISTOF + 236)
      Duty_M1A = STOF(ISTOF + 237)
      Grd_Iac1 = STOF(ISTOF + 238)
      Qmeas    = STOF(ISTOF + 239)
      spov_gblock = STOI(ISTOI + 49)
      oc_block = STOI(ISTOI + 50)
      AMC_DRV1 = STOF(ISTOF + 246)
      AMC_DRV2 = STOF(ISTOF + 247)
      AMC_DRV3 = STOF(ISTOF + 248)
      AMC_DRV4 = STOF(ISTOF + 249)
      DCC_EN2  = STOF(ISTOF + 250)
      DCC_EN3  = STOF(ISTOF + 251)
      DCC_EN4  = STOF(ISTOF + 252)
      DCC_SS_EN2 = STOF(ISTOF + 253)
      DCC_SS_EN3 = STOF(ISTOF + 254)
      ACSSC_DRV2 = STOF(ISTOF + 255)
      ACSSC_DRV3 = STOF(ISTOF + 256)
      ACSSC_DRV4 = STOF(ISTOF + 257)
      PWM_EN2  = STOF(ISTOF + 258)
      PWM_EN3  = STOF(ISTOF + 259)
      PWM_EN4  = STOF(ISTOF + 260)
      Pref     = STOF(ISTOF + 265)
      Qref1    = STOF(ISTOF + 266)
      Bat_SOC2 = STOF(ISTOF + 270)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_22(IT_0) = STOF(ISTOF + 72 + IT_0)
         PQRefSet(IT_0) = STOF(ISTOF + 208 + IT_0)
         CapCur(IT_0) = STOF(ISTOF + 210 + IT_0)
         BusVolt(IT_0) = STOF(ISTOF + 215 + IT_0)
         GridVolt(IT_0) = STOF(ISTOF + 217 + IT_0)
         PQ_pos(IT_0) = STOF(ISTOF + 260 + IT_0)
         IPQ_pos(IT_0) = STOF(ISTOF + 262 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_8(IT_0) = STOF(ISTOF + 27 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 57 + IT_0)
         Ug_rms_LV(IT_0) = STOF(ISTOF + 60 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 74 + IT_0)
         Duty_M4(IT_0) = STOF(ISTOF + 177 + IT_0)
         Duty_M3(IT_0) = STOF(ISTOF + 180 + IT_0)
         Duty_M2(IT_0) = STOF(ISTOF + 183 + IT_0)
         Duty_M1(IT_0) = STOF(ISTOF + 186 + IT_0)
         BattMeas(IT_0) = STOF(ISTOF + 205 + IT_0)
         ModuleCur(IT_0) = STOF(ISTOF + 212 + IT_0)
         TP_iS(IT_0) = STOF(ISTOF + 239 + IT_0)
         Vabc1(IT_0) = STOF(ISTOF + 242 + IT_0)
         TP_iG(IT_0) = STOF(ISTOF + 266 + IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         RT_9(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_10(IT_0) = STOF(ISTOF + 34 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 38 + IT_0)
         RT_12(IT_0) = STOF(ISTOF + 42 + IT_0)
         RT_13(IT_0) = STOF(ISTOF + 46 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 50 + IT_0)
         PWM1_EN(IT_0) = STOF(ISTOF + 131 + IT_0)
         PWM_EN(IT_0) = STOF(ISTOF + 173 + IT_0)
         DCSSC_DRV(IT_0) = STOF(ISTOF + 189 + IT_0)
         DCC_DRV(IT_0) = STOF(ISTOF + 193 + IT_0)
         ACSSC_DRV(IT_0) = STOF(ISTOF + 197 + IT_0)
         ACM_DRV(IT_0) = STOF(ISTOF + 201 + IT_0)
      END DO

! Array (1:8) quantities...
      DO IT_0 = 1,8
         FrequenceTripTh(IT_0) = STOF(ISTOF + 85 + IT_0)
         FrequenceTripTime(IT_0) = STOF(ISTOF + 93 + IT_0)
         VoltageTripTh(IT_0) = STOF(ISTOF + 101 + IT_0)
         VoltageTripTime(IT_0) = STOF(ISTOF + 109 + IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         PWMDRV1(IT_0) = STOF(ISTOF + 2 + IT_0)
      END DO

! Array (1:16) quantities...
      DO IT_0 = 1,16
         DebugData2(IT_0) = STOF(ISTOF + 141 + IT_0)
         DebugData1(IT_0) = STOF(ISTOF + 157 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakDyn()


! 20:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         MCB_DRV2 = 1
      ELSE
         MCB_DRV2 = 1
         IF ( TIME .GE. 0.002 ) MCB_DRV2 = (1-1)
      ENDIF

! 30:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         MCB_DRV1 = 1
      ELSE
         MCB_DRV1 = 1
         IF ( TIME .GE. 0.002 ) MCB_DRV1 = (1-1)
      ENDIF

! 50:[breaker3] 3 Phase Breaker 'MCB_DRV2'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+19),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV2)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+20),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV2)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+21),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV2)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+19),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+20),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+21),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,707526076,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,707526076,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,707526076,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+19),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+20),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+21),SS(1)))

! 110:[breaker3] 3 Phase Breaker 'MCB_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+1),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+2),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+3),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+1),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+2),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+3),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,715928027,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,715928027,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,715928027,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+1),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+2),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+3),SS(1)))

! 180:[battery] Generic battery model 'Bat2'
      IVD1_1=NSTORF
      CALL COMPONENT_ID(ICALL_NO,431765413)
      CALL BATTERYCOEFF1_EXE(SS(1), (IBRCH(1)+16))
      Bat_SOC2 = STORF(IVD1_1+2)*100.0

! 220:[consti] Integer Constant 
      OFP3 = 6300

! 240:[consti] Integer Constant 
      OFP2 = 6160

! 250:[battery] Generic battery model 'Bat1'
      IVD1_1=NSTORF
      CALL COMPONENT_ID(ICALL_NO,1483980752)
      CALL BATTERYCOEFF1_EXE(SS(1), (IBRCH(1)+17))
      Bat_SOC = STORF(IVD1_1+2)*100.0

! 260:[consti] Integer Constant 
      OFP1 = 6060

! 270:[consti] Integer Constant 
      UFP1 = 5940

! 280:[consti] Integer Constant 
      UFP2 = 5840

! 310:[consti] Integer Constant 
      UFP3 = 5780

! 330:[consti] Integer Constant 
      UFP4 = 5730

! 350:[consti] Integer Constant 
      UFP5 = 5700

! 360:[consti] Integer Constant 
      OFP3Timems = 30000

! 380:[consti] Integer Constant 
      OFP2Timems = 300000

! 390:[consti] Integer Constant 
      OFP1Timems = 300000

! 400:[datamerge] Merges data signals into an array 
      BattMeas(1) = Bat_SOC
      BattMeas(2) = Ibat1
      BattMeas(3) = BatVolt

! 410:[consti] Integer Constant 
      UFP1Timems = 300000

! 430:[var] Variable Input Slider 'ActivePowerSet'
      RT_20 = CX(CXMAP(ICX+1))

! 440:[consti] Integer Constant 
      UFP2Timems = 300000

! 450:[consti] Integer Constant 
      UFP3Timems = 300000

! 460:[consti] Integer Constant 
      UFP4Timems = 300000

! 470:[var] Variable Input Slider 'ReactivePowerSet'
      RT_21 = CX(CXMAP(ICX+2))

! 480:[consti] Integer Constant 
      UFP5Timems = 30000

! 500:[consti] Integer Constant 
      OVP4 = 1300

! 510:[consti] Integer Constant 
      OVP3 = 1175

! 520:[datatap] Scalar/Array Tap 
      Pref = PQref(1)

! 530:[consti] Integer Constant 
      OVP2 = 1150

! 540:[consti] Integer Constant 
      JCoft = 1753844

! 550:[consti] Integer Constant 
      OVP1 = 1100

! 560:[datatap] Scalar/Array Tap 
      Qref1 = PQref(2)

! 570:[consti] Integer Constant 
      DampCoft = 540000

! 580:[consti] Integer Constant 
      UVP1 = 900

! 590:[consti] Integer Constant 
      CommandWord = 8709

! 600:[consti] Integer Constant 
      UVP2 = 750

! 610:[consti] Integer Constant 
      SetupWord = 34757

! 620:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 630:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 640:[consti] Integer Constant 
      UVP3 = 650

! 650:[consti] Integer Constant 
      SclToBess = 6188

! 660:[consti] Integer Constant 
      UVP4 = 450

! 670:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,338651251)
      CALL E_XSGEN1_EXE(1,16000.0,RVD2_1)
      Triasign = RVD2_1(1)

! 680:[consti] Integer Constant 
      OVP4Timems = 30000

! 690:[consti] Integer Constant 
      OVP3Timems = 30000

! 700:[FFT_Mod]  
      CALL FFT_ModDyn(Vab0, Vbc0, TP_ia, TP_ib, TP_ic, RT_1, RT_2, RT_3,&
     & RT_4, RT_5, RT_6, RT_7)


! 710:[consti] Integer Constant 
      OVP2Timems = 30000

! 720:[consti] Integer Constant 
      OVP1Timems = 30000

! 730:[pgb] Output Channel 'Triasign_PWM'

      PGB(IPGB+1) = Triasign

! 740:[datamerge] Merges data signals into an array 
      Ug_rms_LV(1) = RT_1
      Ug_rms_LV(2) = RT_2
      Ug_rms_LV(3) = RT_3

! 750:[consti] Integer Constant 
      UVP1Timems = 30000

! 760:[consti] Integer Constant 
      IT_1 = 1

! 770:[datamerge] Merges data signals into an array 
      PQ_pos(1) = RT_4
      PQ_pos(2) = RT_5

! 780:[consti] Integer Constant 
      UVP2Timems = 30000

! 790:[datamerge] Merges data signals into an array 
      IPQ_pos(1) = RT_6
      IPQ_pos(2) = RT_7

! 800:[consti] Integer Constant 
      UVP3Timems = 30000

! 810:[pgb] Output Channel 'SOC'

      PGB(IPGB+2) = Bat_SOC

! 820:[consti] Integer Constant 
      UVP4Timems = 30000

! 830:[const] Real Constant 
      RT_25 = 0.0

! 840:[const] Real Constant 
      RT_26 = 0.0

! 850:[time-sig] Output of Simulation Time 
      RT_28 = TIME

! 860:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.5,RT_28,0.0,0.0,1.0,RVD2_1)
      RT_24 = RVD2_1(1)

! 870:[pgb] Output Channel 'Vlrms'

      DO IVD1_1 = 1, 3
         PGB(IPGB+3+IVD1_1-1) = Ug_rms_LV(IVD1_1)
      ENDDO

! 880:[const] Real Constant 
      RT_36 = 1000.0

! 890:[datatap] Scalar/Array Tap 
      RT_16 = PQ_pos(1)

! 900:[pgb] Output Channel 'P'

      PGB(IPGB+6) = RT_16

! 910:[const] Real Constant 
      RT_34 = 1000.0

! 920:[datatap] Scalar/Array Tap 
      RT_18 = PQ_pos(2)

! 930:[pgb] Output Channel 'Q'

      PGB(IPGB+7) = RT_18

! 940:[const] Real Constant 
      RT_31 = 1000.0

! 950:[datatap] Scalar/Array Tap 
      RT_17 = IPQ_pos(1)

! 960:[pgb] Output Channel 'I_active'

      PGB(IPGB+8) = RT_17

! 970:[datatap] Scalar/Array Tap 
      RT_19 = IPQ_pos(2)

! 980:[pgb] Output Channel 'I_reactive'

      PGB(IPGB+9) = RT_19

! 1020:[datamerge] Merges data signals into an array 
      FrequenceTripTh(1) = REAL(OFP3)
      FrequenceTripTh(2) = REAL(OFP2)
      FrequenceTripTh(3) = REAL(OFP1)
      FrequenceTripTh(4) = REAL(UFP1)
      FrequenceTripTh(5) = REAL(UFP2)
      FrequenceTripTh(6) = REAL(UFP3)
      FrequenceTripTh(7) = REAL(UFP4)
      FrequenceTripTh(8) = REAL(UFP5)

! 1030:[datamerge] Merges data signals into an array 
      FrequenceTripTime(1) = REAL(OFP3Timems)
      FrequenceTripTime(2) = REAL(OFP2Timems)
      FrequenceTripTime(3) = REAL(OFP1Timems)
      FrequenceTripTime(4) = REAL(UFP1Timems)
      FrequenceTripTime(5) = REAL(UFP2Timems)
      FrequenceTripTime(6) = REAL(UFP3Timems)
      FrequenceTripTime(7) = REAL(UFP4Timems)
      FrequenceTripTime(8) = REAL(UFP5Timems)

! 1040:[datamerge] Merges data signals into an array 
      VoltageTripTh(1) = REAL(OVP4)
      VoltageTripTh(2) = REAL(OVP3)
      VoltageTripTh(3) = REAL(OVP2)
      VoltageTripTh(4) = REAL(OVP1)
      VoltageTripTh(5) = REAL(UVP1)
      VoltageTripTh(6) = REAL(UVP2)
      VoltageTripTh(7) = REAL(UVP3)
      VoltageTripTh(8) = REAL(UVP4)

! 1050:[datamerge] Merges data signals into an array 
      VoltageTripTime(1) = REAL(OVP4Timems)
      VoltageTripTime(2) = REAL(OVP3Timems)
      VoltageTripTime(3) = REAL(OVP2Timems)
      VoltageTripTime(4) = REAL(OVP1Timems)
      VoltageTripTime(5) = REAL(UVP1Timems)
      VoltageTripTime(6) = REAL(UVP2Timems)
      VoltageTripTime(7) = REAL(UVP3Timems)
      VoltageTripTime(8) = REAL(UVP4Timems)

! 1060:[select] Two Input Selector 
      IF (NINT(RT_24) .EQ. RTCI(NRTCI)) THEN
         RT_27 = RT_25
      ELSE
         RT_27 = RT_26
      ENDIF
      NRTCI = NRTCI + 1
!

! 1070:[oc_spov]  
!
      CALL COMPONENT_ID(ICALL_NO,237356938)
      CALL oc_spovDyn(spov_trip, spov_gblock, oc_block, TP_iS, Vabc1, 0.&
     &69, 10.0, 10.0, 10.0, 0.5)
!

! 1080:[mult] Multiplier 
      RT_38 = Grd_Iac1 * RT_36

! 1090:[abs] Absolute Value 
      RT_37 = ABS(RT_38)

! 1100:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,RT_37,0.0,0.0,1.0,RVD2_1)
      Rocp = RVD2_1(1)

! 1110:[mult] Multiplier 
      RT_33 = Grd_Ibc1 * RT_34

! 1120:[abs] Absolute Value 
      RT_35 = ABS(RT_33)

! 1130:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,RT_35,0.0,0.0,1.0,RVD2_1)
      Socp = RVD2_1(1)

! 1140:[mult] Multiplier 
      RT_30 = Grd_Icc1 * RT_31

! 1150:[abs] Absolute Value 
      RT_32 = ABS(RT_30)

! 1160:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,RT_32,0.0,0.0,1.0,RVD2_1)
      Tocp = RVD2_1(1)

! 1170:[special_funcs]  
!
      CALL COMPONENT_ID(ICALL_NO,50746761)
      CALL special_funcsDyn(Qref, Qmeas, Qref1, Vabc1, FreqSet, 0, 1.0, &
     &0, 1.0, 0.01, 0.01)
!

! 1180:[datamerge] Merges data signals into an array 
      PQRefSet(1) = Pref
      PQRefSet(2) = Qref

! 1190:[Ctrl_1]  
! PCS2 Interface for PSCAD&IVF&VS

 !     CALL AUX_PCS2CTRL(GridVolt,BusVolt,REAL(SetupWord),ModuleCur,CapCur,PQRefSet,BattMeas,REAL(CommandWord),MCB_DRVx,ACM_DRV,ACSSC_DRV,DCC_DRV,DCSSC_DRV,Duty_M1,Duty_M2,Duty_M3,Duty_M4,PWM_EN,DebugData1,DebugData2)
       CALL AUX_PCS2CTRL(GridVolt,BusVolt,REAL(SetupWord),ModuleCur,CapC&
     &ur,PQRefSet,BattMeas,REAL(CommandWord),Tsample,REAL(SclToBess),TP_&
     &ia,TP_ib,TP_ic,REAL(JCoft),REAL(VgridHpfFreq),REAL(DampCoft),Frequ&
     &enceTripTh,FrequenceTripTime,VoltageTripTh,VoltageTripTime,MCB_DRV&
     &x,ACM_DRV,ACSSC_DRV,DCC_DRV,DCSSC_DRV,Duty_M1,Duty_M2,Duty_M3,Duty&
     &_M4,PWM_EN,DebugData1,DebugData2)

! 1200:[datatap] Scalar/Array Tap 
      FreqSet = DebugData2(10)

! 1210:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (NINT(MCB_DRVx) .NE. 0) .OR. (spov_trip .NE. 0) ) THEN
        MCB_DRV = 1
      ELSE
        MCB_DRV = 0
      ENDIF

! 1220:[breaker3] 3 Phase Breaker 'MCB_DRV'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+10),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+11),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+12),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+11),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+12),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1405209624,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1405209624,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1405209624,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+11),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+12),SS(1)))

! 1230:[datatap] Scalar/Array Tap 
      OCP_EN = DCSSC_DRV(4)

! 1240:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(OCP_EN) .NE. 0) .AND. (NINT(OCP_EN) .NE. 0) ) THEN
        OCP_ENx = 0
      ELSE
        OCP_ENx = 1
      ENDIF

! 1250:[datatap] Scalar/Array Tap 
      PWM_EN1x = PWM_EN(1)

! 1260:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (NINT(PWM_EN1x) .NE. 0) .OR. (NINT(PWM_EN1x) .NE. 0) ) THEN
        PWM_EN1 = 1
      ELSE
        PWM_EN1 = 0
      ENDIF

! 1270:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Tocp) .NE. 0) ) THEN
        TPWM_EN = 1
      ELSE
        TPWM_EN = 0
      ENDIF

! 1280:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Socp) .NE. 0) ) THEN
        SPWM_EN = 1
      ELSE
        SPWM_EN = 0
      ENDIF

! 1290:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Rocp) .NE. 0) ) THEN
        RPWM_EN = 1
      ELSE
        RPWM_EN = 0
      ENDIF

! 1300:[datatap] Scalar/Array Tap 
      Duty_M1C = Duty_M1(3)

! 1310:[datatap] Scalar/Array Tap 
      Duty_M1B = Duty_M1(2)

! 1320:[datatap] Scalar/Array Tap 
      Duty_M1A = Duty_M1(1)

! 1330:[mult] Multiplier 
      RT_39 = Duty_M1C * BatVolt

! 1340:[datamerge] Merges data signals into an array 
      PWM1_EN(1) = REAL(PWM_EN1)
      PWM1_EN(2) = REAL(RPWM_EN)
      PWM1_EN(3) = REAL(SPWM_EN)
      PWM1_EN(4) = REAL(TPWM_EN)

! 1350:[mult] Multiplier 
      RT_40 = Duty_M1B * BatVolt

! 1360:[datatap] Scalar/Array Tap 
      VoltSet = DebugData2(9)

! 1370:[datatap] Scalar/Array Tap 
      RT_14 = DebugData2(5 : 8)

! 1380:[datatap] Scalar/Array Tap 
      RT_9 = DebugData1(1 : 4)

! 1390:[mult] Multiplier 
      RT_41 = Duty_M1A * BatVolt

! 1400:[realpole] Real Pole 
!  Real_Pole
      RT_29 = REALPOLE(0,1,0,1.0,0.1,RT_27,0.0,-1.0E20,1.0E20)

! 1410:[pgb] Output Channel 'Qref'

      PGB(IPGB+10) = Qref

! 1420:[pgb] Output Channel 'PWM_Mod'

      DO IVD1_1 = 1, 3
         PGB(IPGB+11+IVD1_1-1) = Duty_M1(IVD1_1)
      ENDDO

! 1430:[mult] Multiplier 
      EN_inv_bk = PWM_EN1x * REAL(IT_1)

! 1440:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,0.5,PWM_EN1x,1.0,0.0,0.0,RVD2_1)
      EN_inv = RVD2_1(1)

! 1450:[PWM_3Level]  
      CALL PWM_3LevelDyn(Duty_M1A, Duty_M1B, Duty_M1C, PWMDRV1, Triasign&
     &, PWM1_EN)


! 1460:[mult] Multiplier 
      vc_inv = RT_39 * EN_inv

! 1470:[pgb] Output Channel 'DebugData2'

      DO IVD1_1 = 1, 16
         PGB(IPGB+14+IVD1_1-1) = DebugData2(IVD1_1)
      ENDDO

! 1480:[pgb] Output Channel 'DebugData1'

      DO IVD1_1 = 1, 16
         PGB(IPGB+30+IVD1_1-1) = DebugData1(IVD1_1)
      ENDDO

! 1490:[pgb] Output Channel 'T10'

      PGB(IPGB+46) = FreqSet

! 1500:[mult] Multiplier 
      vb_inv = RT_40 * EN_inv

! 1510:[datatap] Scalar/Array Tap 
      RT_12 = DebugData1(13 : 16)

! 1520:[pgb] Output Channel 'T4'

      DO IVD1_1 = 1, 4
         PGB(IPGB+47+IVD1_1-1) = RT_12(IVD1_1)
      ENDDO

! 1530:[pgb] Output Channel 'T9'

      PGB(IPGB+51) = VoltSet

! 1540:[datatap] Scalar/Array Tap 
      RT_11 = DebugData1(9 : 12)

! 1550:[pgb] Output Channel 'T3'

      DO IVD1_1 = 1, 4
         PGB(IPGB+52+IVD1_1-1) = RT_11(IVD1_1)
      ENDDO

! 1560:[datatap] Scalar/Array Tap 
      PWM_EN4 = PWM_EN(4)

! 1570:[pgb] Output Channel 'PCS Fault'

      DO IVD1_1 = 1, 4
         PGB(IPGB+56+IVD1_1-1) = RT_14(IVD1_1)
      ENDDO

! 1580:[datatap] Scalar/Array Tap 
      RT_10 = DebugData1(5 : 8)

! 1590:[pgb] Output Channel 'T2'

      DO IVD1_1 = 1, 4
         PGB(IPGB+60+IVD1_1-1) = RT_10(IVD1_1)
      ENDDO

! 1600:[datatap] Scalar/Array Tap 
      PWM_EN3 = PWM_EN(3)

! 1610:[datatap] Scalar/Array Tap 
      RT_13 = DebugData2(1 : 4)

! 1620:[datatap] Scalar/Array Tap 
      PWM_EN2 = PWM_EN(2)

! 1630:[pgb] Output Channel 'T7'

      DO IVD1_1 = 1, 4
         PGB(IPGB+64+IVD1_1-1) = RT_13(IVD1_1)
      ENDDO

! 1640:[mult] Multiplier 
      va_inv = RT_41 * EN_inv

! 1650:[pgb] Output Channel 'T1'

      DO IVD1_1 = 1, 4
         PGB(IPGB+68+IVD1_1-1) = RT_9(IVD1_1)
      ENDDO

! 1660:[datatap] Scalar/Array Tap 
      DCC_SS_EN3 = DCSSC_DRV(3)

! 1670:[mult] Multiplier 
      ia_inv_dc = Duty_M1C * Grd_Icc1

! 1680:[datatap] Scalar/Array Tap 
      DCC_SS_EN2 = DCSSC_DRV(2)

! 1690:[datatap] Scalar/Array Tap 
      DCC_SS_EN1 = DCSSC_DRV(1)

! 1700:[datatap] Scalar/Array Tap 
      DCC_EN4 = DCC_DRV(4)

! 1710:[datatap] Scalar/Array Tap 
      DCC_EN3 = DCC_DRV(3)

! 1720:[mult] Multiplier 
      ib_inv_dc = Duty_M1B * Grd_Ibc1

! 1730:[datatap] Scalar/Array Tap 
      DCC_EN2 = DCC_DRV(2)

! 1740:[datatap] Scalar/Array Tap 
      DCC_EN1 = DCC_DRV(1)

! 1750:[pgb] Output Channel 'PWM'

      DO IVD1_1 = 1, 4
         PGB(IPGB+72+IVD1_1-1) = PWM1_EN(IVD1_1)
      ENDDO

! 1760:[datatap] Scalar/Array Tap 
      ACSSC_DRV4 = ACSSC_DRV(4)

! 1770:[datatap] Scalar/Array Tap 
      ACSSC_DRV3 = ACSSC_DRV(3)

! 1780:[datatap] Scalar/Array Tap 
      ACSSC_DRV2 = ACSSC_DRV(2)

! 1790:[pgb] Output Channel 'MCB'

      PGB(IPGB+76) = REAL(MCB_DRV)

! 1800:[datatap] Scalar/Array Tap 
      ACSSC_DRV1 = ACSSC_DRV(1)

! 1810:[mult] Multiplier 
      ic_inv_dc = Duty_M1A * Grd_Iac1

! 1820:[datatap] Scalar/Array Tap 
      AMC_DRV4 = ACM_DRV(4)

! 1830:[pgb] Output Channel 'MC'

      DO IVD1_1 = 1, 4
         PGB(IPGB+77+IVD1_1-1) = ACM_DRV(IVD1_1)
      ENDDO

! 1840:[datatap] Scalar/Array Tap 
      AMC_DRV3 = ACM_DRV(3)

! 1850:[datatap] Scalar/Array Tap 
      AMC_DRV2 = ACM_DRV(2)

! 1860:[datatap] Scalar/Array Tap 
      AMC_DRV1 = ACM_DRV(1)

! 1870:[pgb] Output Channel 'DC_EN'

      PGB(IPGB+81) = DCC_EN1

! 1880:[pgb] Output Channel 'DC_SS_EN'

      PGB(IPGB+82) = DCC_SS_EN1

! 1890:[pgb] Output Channel 'AC_SS_EN'

      PGB(IPGB+83) = ACSSC_DRV1

! 1910:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+22),SS(1)) = ia_inv_dc
      IF (TIMEZERO) CCBRD( (IBRCH(1)+22),SS(1)) = ia_inv_dc

! 1930:[source_1] Single Phase Voltage Source Model 2 'Source_1'
! Externally controlled DC source: Type: Ideal
      RVD1_1 = vc_inv
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+29),RVD1_4,0,RVD1_1,RVD1_2,RVD1&
     &_3)

! 1940:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+23),SS(1)) = ib_inv_dc
      IF (TIMEZERO) CCBRD( (IBRCH(1)+23),SS(1)) = ib_inv_dc

! 1960:[source_1] Single Phase Voltage Source Model 2 'Source_1'
! Externally controlled DC source: Type: Ideal
      RVD1_1 = vb_inv
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+28),RVD1_4,0,RVD1_1,RVD1_2,RVD1&
     &_3)

! 1970:[breaker3] 3 Phase Breaker 'EN_inv_bk'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+25),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-EN_inv_bk))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+26),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-EN_inv_bk))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+27),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-EN_inv_bk))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+25),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+26),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+27),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1458862097,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1458862097,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1458862097,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+25),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+26),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+27),SS(1)))

! 1990:[src_ccin_1] Current Source 'Source 1_1'
      CCBR( (IBRCH(1)+24),SS(1)) = ic_inv_dc
      IF (TIMEZERO) CCBRD( (IBRCH(1)+24),SS(1)) = ic_inv_dc

! 2000:[breaker3] 3 Phase Breaker 'AMC_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+35),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-AMC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+36),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-AMC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+37),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-AMC_DRV1))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+35),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+36),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+37),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,123013057,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,123013057,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,123013057,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+35),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+36),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+37),SS(1)))

! 2010:[breaker1] Single Phase Breaker 'DCC_EN1'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+18),0.005,1000000.0,1,NINT(1.0-&
     &DCC_EN1))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+18),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,734835594,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+18),SS(1)))

! 2020:[source_1] Single Phase Voltage Source Model 2 'Source_1'
! Externally controlled DC source: Type: Ideal
      RVD1_1 = va_inv
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS(1), (IBRCH(1)+30),RVD1_4,0,RVD1_1,RVD1_2,RVD1&
     &_3)

! 2050:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+43),0.005,1000000.0,1,NINT(1.0-&
     &DCC_SS_EN1))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+43),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1311922066,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+43),SS(1)))

! 2060:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+38),0.001,100000000.0,RTCF(NR&
     &TCF),1,NINT(1.0-ACSSC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+39),0.001,100000000.0,RTCF(NR&
     &TCF),1,NINT(1.0-ACSSC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+40),0.001,100000000.0,RTCF(NR&
     &TCF),1,NINT(1.0-ACSSC_DRV1))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+38),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+39),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+40),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,757793417,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,757793417,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,757793417,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+38),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+39),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+40),SS(1)))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 15) = Vab0
      STOF(ISTOF + 16) = Vbc0
      STOF(ISTOF + 17) = RT_1
      STOF(ISTOF + 18) = RT_2
      STOF(ISTOF + 19) = RT_3
      STOF(ISTOF + 20) = RT_4
      STOF(ISTOF + 21) = RT_5
      STOF(ISTOF + 22) = RT_6
      STOF(ISTOF + 23) = RT_7
      STOF(ISTOF + 24) = Grd_Vdc1
      STOF(ISTOF + 25) = Grd_Vdc2
      STOF(ISTOF + 26) = Ibat1
      STOF(ISTOF + 27) = Vca0
      STOF(ISTOF + 55) = DCC_SS_EN1
      STOF(ISTOF + 56) = DCC_EN1
      STOF(ISTOF + 57) = ACSSC_DRV1
      STOF(ISTOF + 64) = RT_16
      STOF(ISTOF + 65) = RT_17
      STOF(ISTOF + 66) = RT_18
      STOF(ISTOF + 67) = RT_19
      STOI(ISTOI + 1) = MCB_DRV1
      STOF(ISTOF + 68) = RT_20
      STOF(ISTOF + 69) = RT_21
      STOF(ISTOF + 70) = Bat_SOC
      STOF(ISTOF + 71) = Grd_Ia1
      STOF(ISTOF + 72) = Grd_Ib1
      STOF(ISTOF + 78) = Triasign
      STOF(ISTOF + 79) = Qref
      STOF(ISTOF + 80) = RT_24
      STOF(ISTOF + 81) = RT_25
      STOF(ISTOF + 82) = RT_26
      STOF(ISTOF + 83) = RT_27
      STOF(ISTOF + 84) = RT_28
      STOF(ISTOF + 85) = RT_29
      STOI(ISTOI + 2) = UFP5
      STOI(ISTOI + 3) = UFP4
      STOI(ISTOI + 4) = UFP3
      STOI(ISTOI + 5) = UFP2
      STOI(ISTOI + 6) = OFP3
      STOI(ISTOI + 7) = OFP2
      STOI(ISTOI + 8) = OFP1
      STOI(ISTOI + 9) = UFP1
      STOI(ISTOI + 10) = UFP5Timems
      STOI(ISTOI + 11) = UFP4Timems
      STOI(ISTOI + 12) = UFP3Timems
      STOI(ISTOI + 13) = OFP3Timems
      STOI(ISTOI + 14) = OFP2Timems
      STOI(ISTOI + 15) = OFP1Timems
      STOI(ISTOI + 16) = UFP2Timems
      STOI(ISTOI + 17) = UFP1Timems
      STOI(ISTOI + 18) = UVP4Timems
      STOI(ISTOI + 19) = UVP3Timems
      STOI(ISTOI + 20) = UVP4
      STOI(ISTOI + 21) = UVP3
      STOI(ISTOI + 22) = OVP4
      STOI(ISTOI + 23) = OVP3
      STOI(ISTOI + 24) = OVP2
      STOI(ISTOI + 25) = OVP1
      STOI(ISTOI + 26) = UVP2
      STOI(ISTOI + 27) = UVP1
      STOI(ISTOI + 28) = UVP1Timems
      STOI(ISTOI + 29) = UVP2Timems
      STOI(ISTOI + 30) = OVP4Timems
      STOI(ISTOI + 31) = OVP3Timems
      STOI(ISTOI + 32) = OVP2Timems
      STOI(ISTOI + 33) = OVP1Timems
      STOI(ISTOI + 34) = MCB_DRV
      STOF(ISTOF + 118) = MCB_DRVx
      STOI(ISTOI + 35) = spov_trip
      STOF(ISTOF + 119) = RT_30
      STOF(ISTOF + 120) = RT_31
      STOF(ISTOF + 121) = RT_32
      STOF(ISTOF + 122) = RT_33
      STOF(ISTOF + 123) = RT_34
      STOF(ISTOF + 124) = RT_35
      STOF(ISTOF + 125) = RT_36
      STOF(ISTOF + 126) = RT_37
      STOF(ISTOF + 127) = RT_38
      STOF(ISTOF + 128) = Tocp
      STOF(ISTOF + 129) = Socp
      STOI(ISTOI + 36) = OCP_ENx
      STOF(ISTOF + 130) = OCP_EN
      STOF(ISTOF + 131) = Rocp
      STOI(ISTOI + 37) = PWM_EN1
      STOI(ISTOI + 38) = RPWM_EN
      STOI(ISTOI + 39) = SPWM_EN
      STOI(ISTOI + 40) = TPWM_EN
      STOI(ISTOI + 41) = MCB_DRV2
      STOF(ISTOF + 136) = VoltSet
      STOF(ISTOF + 137) = FreqSet
      STOI(ISTOI + 42) = DampCoft
      STOI(ISTOI + 43) = VgridHpfFreq
      STOI(ISTOI + 44) = JCoft
      STOF(ISTOF + 138) = TP_ic
      STOF(ISTOF + 139) = TP_ib
      STOF(ISTOF + 140) = TP_ia
      STOI(ISTOI + 45) = SclToBess
      STOF(ISTOF + 141) = Tsample
      STOI(ISTOI + 46) = CommandWord
      STOI(ISTOI + 47) = SetupWord
      STOI(ISTOI + 48) = IT_1
      STOF(ISTOF + 220) = EN_inv_bk
      STOF(ISTOF + 221) = PWM_EN1x
      STOF(ISTOF + 222) = EN_inv
      STOF(ISTOF + 223) = vc_inv
      STOF(ISTOF + 224) = RT_39
      STOF(ISTOF + 225) = vb_inv
      STOF(ISTOF + 226) = RT_40
      STOF(ISTOF + 227) = va_inv
      STOF(ISTOF + 228) = RT_41
      STOF(ISTOF + 229) = BatVolt
      STOF(ISTOF + 230) = ia_inv_dc
      STOF(ISTOF + 231) = Duty_M1C
      STOF(ISTOF + 232) = Grd_Icc1
      STOF(ISTOF + 233) = ib_inv_dc
      STOF(ISTOF + 234) = Duty_M1B
      STOF(ISTOF + 235) = Grd_Ibc1
      STOF(ISTOF + 236) = ic_inv_dc
      STOF(ISTOF + 237) = Duty_M1A
      STOF(ISTOF + 238) = Grd_Iac1
      STOF(ISTOF + 239) = Qmeas
      STOI(ISTOI + 49) = spov_gblock
      STOI(ISTOI + 50) = oc_block
      STOF(ISTOF + 246) = AMC_DRV1
      STOF(ISTOF + 247) = AMC_DRV2
      STOF(ISTOF + 248) = AMC_DRV3
      STOF(ISTOF + 249) = AMC_DRV4
      STOF(ISTOF + 250) = DCC_EN2
      STOF(ISTOF + 251) = DCC_EN3
      STOF(ISTOF + 252) = DCC_EN4
      STOF(ISTOF + 253) = DCC_SS_EN2
      STOF(ISTOF + 254) = DCC_SS_EN3
      STOF(ISTOF + 255) = ACSSC_DRV2
      STOF(ISTOF + 256) = ACSSC_DRV3
      STOF(ISTOF + 257) = ACSSC_DRV4
      STOF(ISTOF + 258) = PWM_EN2
      STOF(ISTOF + 259) = PWM_EN3
      STOF(ISTOF + 260) = PWM_EN4
      STOF(ISTOF + 265) = Pref
      STOF(ISTOF + 266) = Qref1
      STOF(ISTOF + 270) = Bat_SOC2

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = PQref(IT_0)
         STOF(ISTOF + 72 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 208 + IT_0) = PQRefSet(IT_0)
         STOF(ISTOF + 210 + IT_0) = CapCur(IT_0)
         STOF(ISTOF + 215 + IT_0) = BusVolt(IT_0)
         STOF(ISTOF + 217 + IT_0) = GridVolt(IT_0)
         STOF(ISTOF + 260 + IT_0) = PQ_pos(IT_0)
         STOF(ISTOF + 262 + IT_0) = IPQ_pos(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 27 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 57 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 60 + IT_0) = Ug_rms_LV(IT_0)
         STOF(ISTOF + 74 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 177 + IT_0) = Duty_M4(IT_0)
         STOF(ISTOF + 180 + IT_0) = Duty_M3(IT_0)
         STOF(ISTOF + 183 + IT_0) = Duty_M2(IT_0)
         STOF(ISTOF + 186 + IT_0) = Duty_M1(IT_0)
         STOF(ISTOF + 205 + IT_0) = BattMeas(IT_0)
         STOF(ISTOF + 212 + IT_0) = ModuleCur(IT_0)
         STOF(ISTOF + 239 + IT_0) = TP_iS(IT_0)
         STOF(ISTOF + 242 + IT_0) = Vabc1(IT_0)
         STOF(ISTOF + 266 + IT_0) = TP_iG(IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         STOF(ISTOF + 30 + IT_0) = RT_9(IT_0)
         STOF(ISTOF + 34 + IT_0) = RT_10(IT_0)
         STOF(ISTOF + 38 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 42 + IT_0) = RT_12(IT_0)
         STOF(ISTOF + 46 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 50 + IT_0) = RT_14(IT_0)
         STOF(ISTOF + 131 + IT_0) = PWM1_EN(IT_0)
         STOF(ISTOF + 173 + IT_0) = PWM_EN(IT_0)
         STOF(ISTOF + 189 + IT_0) = DCSSC_DRV(IT_0)
         STOF(ISTOF + 193 + IT_0) = DCC_DRV(IT_0)
         STOF(ISTOF + 197 + IT_0) = ACSSC_DRV(IT_0)
         STOF(ISTOF + 201 + IT_0) = ACM_DRV(IT_0)
      END DO

! Array (1:8) quantities...
      DO IT_0 = 1,8
         STOF(ISTOF + 85 + IT_0) = FrequenceTripTh(IT_0)
         STOF(ISTOF + 93 + IT_0) = FrequenceTripTime(IT_0)
         STOF(ISTOF + 101 + IT_0) = VoltageTripTh(IT_0)
         STOF(ISTOF + 109 + IT_0) = VoltageTripTime(IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         STOF(ISTOF + 2 + IT_0) = PWMDRV1(IT_0)
      END DO

! Array (1:16) quantities...
      DO IT_0 = 1,16
         STOF(ISTOF + 141 + IT_0) = DebugData2(IT_0)
         STOF(ISTOF + 157 + IT_0) = DebugData1(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESS_1Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakOut      ! 
      REAL    VBRANCH       ! 
      REAL    EMTDC_VVDC    ! 
!     SUBR    FFT_ModOut    ! 
!     SUBR    PWM_3LevelOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_5, NT_17, NT_21, NT_50, NT_51
      INTEGER  NT_52, NT_53

! Control Signals
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      INTEGER  DampCoft, VgridHpfFreq, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  IT_1
      REAL     Vab0, Vbc0, Grd_Vdc1, Grd_Vdc2
      REAL     Ibat1, Vca0, RT_8(3), RT_15(3)
      REAL     Grd_Ia1, Grd_Ib1, RT_22(2)
      REAL     RT_23(3), RT_25, RT_26, RT_31
      REAL     RT_34, RT_36, TP_ic, TP_ib, TP_ia
      REAL     Tsample, CapCur(2), ModuleCur(3)
      REAL     BusVolt(2), GridVolt(2), BatVolt
      REAL     Grd_Icc1, Grd_Ibc1, Grd_Iac1
      REAL     Qmeas, TP_iS(3), Vabc1(3)
      REAL     TP_iG(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 97
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 50
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 62

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vab0     = STOF(ISTOF + 15)
      Vbc0     = STOF(ISTOF + 16)
      Grd_Vdc1 = STOF(ISTOF + 24)
      Grd_Vdc2 = STOF(ISTOF + 25)
      Ibat1    = STOF(ISTOF + 26)
      Vca0     = STOF(ISTOF + 27)
      Grd_Ia1  = STOF(ISTOF + 71)
      Grd_Ib1  = STOF(ISTOF + 72)
      RT_25    = STOF(ISTOF + 81)
      RT_26    = STOF(ISTOF + 82)
      UFP5     = STOI(ISTOI + 2)
      UFP4     = STOI(ISTOI + 3)
      UFP3     = STOI(ISTOI + 4)
      UFP2     = STOI(ISTOI + 5)
      OFP3     = STOI(ISTOI + 6)
      OFP2     = STOI(ISTOI + 7)
      OFP1     = STOI(ISTOI + 8)
      UFP1     = STOI(ISTOI + 9)
      UFP5Timems = STOI(ISTOI + 10)
      UFP4Timems = STOI(ISTOI + 11)
      UFP3Timems = STOI(ISTOI + 12)
      OFP3Timems = STOI(ISTOI + 13)
      OFP2Timems = STOI(ISTOI + 14)
      OFP1Timems = STOI(ISTOI + 15)
      UFP2Timems = STOI(ISTOI + 16)
      UFP1Timems = STOI(ISTOI + 17)
      UVP4Timems = STOI(ISTOI + 18)
      UVP3Timems = STOI(ISTOI + 19)
      UVP4     = STOI(ISTOI + 20)
      UVP3     = STOI(ISTOI + 21)
      OVP4     = STOI(ISTOI + 22)
      OVP3     = STOI(ISTOI + 23)
      OVP2     = STOI(ISTOI + 24)
      OVP1     = STOI(ISTOI + 25)
      UVP2     = STOI(ISTOI + 26)
      UVP1     = STOI(ISTOI + 27)
      UVP1Timems = STOI(ISTOI + 28)
      UVP2Timems = STOI(ISTOI + 29)
      OVP4Timems = STOI(ISTOI + 30)
      OVP3Timems = STOI(ISTOI + 31)
      OVP2Timems = STOI(ISTOI + 32)
      OVP1Timems = STOI(ISTOI + 33)
      RT_31    = STOF(ISTOF + 120)
      RT_34    = STOF(ISTOF + 123)
      RT_36    = STOF(ISTOF + 125)
      DampCoft = STOI(ISTOI + 42)
      VgridHpfFreq = STOI(ISTOI + 43)
      JCoft    = STOI(ISTOI + 44)
      TP_ic    = STOF(ISTOF + 138)
      TP_ib    = STOF(ISTOF + 139)
      TP_ia    = STOF(ISTOF + 140)
      SclToBess = STOI(ISTOI + 45)
      Tsample  = STOF(ISTOF + 141)
      CommandWord = STOI(ISTOI + 46)
      SetupWord = STOI(ISTOI + 47)
      IT_1     = STOI(ISTOI + 48)
      BatVolt  = STOF(ISTOF + 229)
      Grd_Icc1 = STOF(ISTOF + 232)
      Grd_Ibc1 = STOF(ISTOF + 235)
      Grd_Iac1 = STOF(ISTOF + 238)
      Qmeas    = STOF(ISTOF + 239)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_22(IT_0) = STOF(ISTOF + 72 + IT_0)
         CapCur(IT_0) = STOF(ISTOF + 210 + IT_0)
         BusVolt(IT_0) = STOF(ISTOF + 215 + IT_0)
         GridVolt(IT_0) = STOF(ISTOF + 217 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_8(IT_0) = STOF(ISTOF + 27 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 57 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 74 + IT_0)
         ModuleCur(IT_0) = STOF(ISTOF + 212 + IT_0)
         TP_iS(IT_0) = STOF(ISTOF + 239 + IT_0)
         Vabc1(IT_0) = STOF(ISTOF + 242 + IT_0)
         TP_iG(IT_0) = STOF(ISTOF + 266 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_5  = NODE(INODE + 8)
      NT_17 = NODE(INODE + 21)
      NT_21 = NODE(INODE + 28)
      NT_50 = NODE(INODE + 39)
      NT_51 = NODE(INODE + 12)
      NT_52 = NODE(INODE + 13)
      NT_53 = NODE(INODE + 14)

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakOut()


! 40:[ammeter] Current Meter 'TP_iG'
      TP_iG(1) = ( CBR((IBRCH(1)+7), SS(1)))
      TP_iG(2) = ( CBR((IBRCH(1)+8), SS(1)))
      TP_iG(3) = ( CBR((IBRCH(1)+9), SS(1)))

! 50:[breaker3] 3 Phase Breaker 'MCB_DRV2'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+19), (IBRCH(1)+20), (IBRCH(1)+21),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 60:[ammeter] Current Meter 'TP_ia'
      TP_ia = ( CBR((IBRCH(1)+15), SS(1)))

! 70:[voltmeter] Voltmeter (Line - Line) 'Vab0'
      Vab0 = EMTDC_VVDC(SS(1), NT_51, NT_52)

! 80:[ammeter] Current Meter 'TP_iS'
      TP_iS(1) = ( CBR((IBRCH(1)+4), SS(1)))
      TP_iS(2) = ( CBR((IBRCH(1)+5), SS(1)))
      TP_iS(3) = ( CBR((IBRCH(1)+6), SS(1)))

! 90:[ammeter] Current Meter 'TP_ib'
      TP_ib = ( CBR((IBRCH(1)+14), SS(1)))

! 100:[voltmeter] Voltmeter (Line - Line) 'Vbc0'
      Vbc0 = EMTDC_VVDC(SS(1), NT_52, NT_53)

! 110:[breaker3] 3 Phase Breaker 'MCB_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (IBRCH(1)+3),0,0&
     &,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 120:[ammeter] Current Meter 'Ibat1'
      Ibat1 = ( CBR((IBRCH(1)+34), SS(1)))

! 130:[ammeter] Current Meter 'TP_ic'
      TP_ic = ( CBR((IBRCH(1)+13), SS(1)))

! 140:[ammeter] Current Meter 'Grd_Iac1'
      Grd_Iac1 = ( CBR((IBRCH(1)+33), SS(1)))

! 150:[voltmeter] Voltmeter (Line - Line) 'Vca0'
      Vca0 = EMTDC_VVDC(SS(1), NT_53, NT_51)

! 160:[voltmeter] Voltmeter (Line - Line) 'Grd_Vdc1'
      Grd_Vdc1 = EMTDC_VVDC(SS(1), NT_17, NT_21)

! 170:[ammeter] Current Meter 'Grd_Ibc1'
      Grd_Ibc1 = ( CBR((IBRCH(1)+32), SS(1)))

! 190:[ammeter] Current Meter 'Grd_Icc1'
      Grd_Icc1 = ( CBR((IBRCH(1)+31), SS(1)))

! 200:[datamerge] Merges data signals into an array 
      RT_15(1) = Grd_Iac1
      RT_15(2) = Grd_Ibc1
      RT_15(3) = Grd_Icc1

! 210:[voltmeter] Voltmeter (Line - Line) 'Grd_Vdc2'
      Grd_Vdc2 = EMTDC_VVDC(SS(1), NT_21, NT_5)

! 220:[consti] Integer Constant 

      OFP3 = 6300

! 230:[voltmeter] Voltmeter (Line - Line) 'BatVolt'
      BatVolt = EMTDC_VVDC(SS(1), NT_50, NT_5)

! 240:[consti] Integer Constant 

      OFP2 = 6160

! 260:[consti] Integer Constant 

      OFP1 = 6060

! 270:[consti] Integer Constant 

      UFP1 = 5940

! 280:[consti] Integer Constant 

      UFP2 = 5840

! 290:[ammeter] Current Meter 'Grd_Ib1'
      Grd_Ib1 = ( CBR((IBRCH(1)+42), SS(1)))

! 300:[ammeter] Current Meter 'Grd_Ia1'
      Grd_Ia1 = ( CBR((IBRCH(1)+41), SS(1)))

! 310:[consti] Integer Constant 

      UFP3 = 5780

! 320:[datamerge] Merges data signals into an array 
      CapCur(1) = Grd_Ia1
      CapCur(2) = Grd_Ib1

! 330:[consti] Integer Constant 

      UFP4 = 5730

! 340:[datamerge] Merges data signals into an array 
      GridVolt(1) = Vab0
      GridVolt(2) = Vbc0

! 350:[consti] Integer Constant 

      UFP5 = 5700

! 360:[consti] Integer Constant 

      OFP3Timems = 30000

! 370:[datamerge] Merges data signals into an array 
      BusVolt(1) = Grd_Vdc1
      BusVolt(2) = Grd_Vdc2

! 380:[consti] Integer Constant 

      OFP2Timems = 300000

! 390:[consti] Integer Constant 

      OFP1Timems = 300000

! 410:[consti] Integer Constant 

      UFP1Timems = 300000

! 420:[datamerge] Merges data signals into an array 
      ModuleCur(1) = Grd_Iac1
      ModuleCur(2) = Grd_Ibc1
      ModuleCur(3) = Grd_Icc1

! 440:[consti] Integer Constant 

      UFP2Timems = 300000

! 450:[consti] Integer Constant 

      UFP3Timems = 300000

! 460:[consti] Integer Constant 

      UFP4Timems = 300000

! 480:[consti] Integer Constant 

      UFP5Timems = 30000

! 500:[consti] Integer Constant 

      OVP4 = 1300

! 510:[consti] Integer Constant 

      OVP3 = 1175

! 530:[consti] Integer Constant 

      OVP2 = 1150

! 540:[consti] Integer Constant 

      JCoft = 1753844

! 550:[consti] Integer Constant 

      OVP1 = 1100

! 570:[consti] Integer Constant 

      DampCoft = 540000

! 580:[consti] Integer Constant 

      UVP1 = 900

! 590:[consti] Integer Constant 

      CommandWord = 8709

! 600:[consti] Integer Constant 

      UVP2 = 750

! 610:[consti] Integer Constant 

      SetupWord = 34757

! 620:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 630:[consti] Integer Constant 

      VgridHpfFreq = 100000

! 640:[consti] Integer Constant 

      UVP3 = 650

! 650:[consti] Integer Constant 

      SclToBess = 6188

! 660:[consti] Integer Constant 

      UVP4 = 450

! 680:[consti] Integer Constant 

      OVP4Timems = 30000

! 690:[consti] Integer Constant 

      OVP3Timems = 30000

! 700:[FFT_Mod]  
      CALL FFT_ModOut()


! 710:[consti] Integer Constant 

      OVP2Timems = 30000

! 720:[consti] Integer Constant 

      OVP1Timems = 30000

! 750:[consti] Integer Constant 

      UVP1Timems = 30000

! 760:[consti] Integer Constant 

      IT_1 = 1

! 780:[consti] Integer Constant 

      UVP2Timems = 30000

! 800:[consti] Integer Constant 

      UVP3Timems = 30000

! 820:[consti] Integer Constant 

      UVP4Timems = 30000

! 830:[const] Real Constant 

      RT_25 = 0.0

! 840:[const] Real Constant 

      RT_26 = 0.0

! 880:[const] Real Constant 

      RT_36 = 1000.0

! 910:[const] Real Constant 

      RT_34 = 1000.0

! 940:[const] Real Constant 

      RT_31 = 1000.0

! 990:[datamerge] Merges data signals into an array 
      Vabc1(1) = Vab0
      Vabc1(2) = Vbc0
      Vabc1(3) = Vca0

! 1000:[datamerge] Merges data signals into an array 
      RT_23(1) = TP_ia
      RT_23(2) = TP_ib
      RT_23(3) = TP_ic

! 1010:[datamerge] Merges data signals into an array 
      RT_8(1) = Grd_Iac1
      RT_8(2) = Grd_Ibc1
      RT_8(3) = Grd_Icc1

! 1070:[oc_spov]  
!
      CALL COMPONENT_ID(ICALL_NO,237356938)
      CALL oc_spovOut()
!

! 1170:[special_funcs]  
!
      CALL COMPONENT_ID(ICALL_NO,50746761)
      CALL special_funcsOut()
!

! 1220:[breaker3] 3 Phase Breaker 'MCB_DRV'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+10), (IBRCH(1)+11), (IBRCH(1)+12),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)
      IF (UPDATE_AG) THEN
        CALL PSCAD_AGR2(ICALL_NO,1405209624,RVD1_1,"P")
        CALL PSCAD_AGR2(ICALL_NO,1405209624,RVD1_2,"Q")
      ENDIF
      Qmeas = RVD1_2

! 1450:[PWM_3Level]  
      CALL PWM_3LevelOut()


! 1900:[datamerge] Merges data signals into an array 
      RT_22(1) = Grd_Ia1
      RT_22(2) = Grd_Ib1

! 1920:[pgb] Output Channel 'Icap'

      DO IVD1_1 = 1, 2
         PGB(IPGB+84+IVD1_1-1) = RT_22(IVD1_1)
      ENDDO

! 1950:[pgb] Output Channel 'Iabc2'

      DO IVD1_1 = 1, 3
         PGB(IPGB+86+IVD1_1-1) = RT_15(IVD1_1)
      ENDDO

! 1970:[breaker3] 3 Phase Breaker 'EN_inv_bk'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+25), (IBRCH(1)+26), (IBRCH(1)+27),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 1980:[pgb] Output Channel 'Iabc1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+89+IVD1_1-1) = RT_8(IVD1_1)
      ENDDO

! 2000:[breaker3] 3 Phase Breaker 'AMC_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+35), (IBRCH(1)+36), (IBRCH(1)+37),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 2010:[breaker1] Single Phase Breaker 'DCC_EN1'
! Single phase breaker current
!

! 2030:[pgb] Output Channel 'Igabc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+92+IVD1_1-1) = RT_23(IVD1_1)
      ENDDO

! 2040:[pgb] Output Channel 'Vabc1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+95+IVD1_1-1) = Vabc1(IVD1_1)
      ENDDO

! 2050:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
! Single phase breaker current
!

! 2060:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+38), (IBRCH(1)+39), (IBRCH(1)+40),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 15) = Vab0
      STOF(ISTOF + 16) = Vbc0
      STOF(ISTOF + 24) = Grd_Vdc1
      STOF(ISTOF + 25) = Grd_Vdc2
      STOF(ISTOF + 26) = Ibat1
      STOF(ISTOF + 27) = Vca0
      STOF(ISTOF + 71) = Grd_Ia1
      STOF(ISTOF + 72) = Grd_Ib1
      STOF(ISTOF + 81) = RT_25
      STOF(ISTOF + 82) = RT_26
      STOI(ISTOI + 2) = UFP5
      STOI(ISTOI + 3) = UFP4
      STOI(ISTOI + 4) = UFP3
      STOI(ISTOI + 5) = UFP2
      STOI(ISTOI + 6) = OFP3
      STOI(ISTOI + 7) = OFP2
      STOI(ISTOI + 8) = OFP1
      STOI(ISTOI + 9) = UFP1
      STOI(ISTOI + 10) = UFP5Timems
      STOI(ISTOI + 11) = UFP4Timems
      STOI(ISTOI + 12) = UFP3Timems
      STOI(ISTOI + 13) = OFP3Timems
      STOI(ISTOI + 14) = OFP2Timems
      STOI(ISTOI + 15) = OFP1Timems
      STOI(ISTOI + 16) = UFP2Timems
      STOI(ISTOI + 17) = UFP1Timems
      STOI(ISTOI + 18) = UVP4Timems
      STOI(ISTOI + 19) = UVP3Timems
      STOI(ISTOI + 20) = UVP4
      STOI(ISTOI + 21) = UVP3
      STOI(ISTOI + 22) = OVP4
      STOI(ISTOI + 23) = OVP3
      STOI(ISTOI + 24) = OVP2
      STOI(ISTOI + 25) = OVP1
      STOI(ISTOI + 26) = UVP2
      STOI(ISTOI + 27) = UVP1
      STOI(ISTOI + 28) = UVP1Timems
      STOI(ISTOI + 29) = UVP2Timems
      STOI(ISTOI + 30) = OVP4Timems
      STOI(ISTOI + 31) = OVP3Timems
      STOI(ISTOI + 32) = OVP2Timems
      STOI(ISTOI + 33) = OVP1Timems
      STOF(ISTOF + 120) = RT_31
      STOF(ISTOF + 123) = RT_34
      STOF(ISTOF + 125) = RT_36
      STOI(ISTOI + 42) = DampCoft
      STOI(ISTOI + 43) = VgridHpfFreq
      STOI(ISTOI + 44) = JCoft
      STOF(ISTOF + 138) = TP_ic
      STOF(ISTOF + 139) = TP_ib
      STOF(ISTOF + 140) = TP_ia
      STOI(ISTOI + 45) = SclToBess
      STOF(ISTOF + 141) = Tsample
      STOI(ISTOI + 46) = CommandWord
      STOI(ISTOI + 47) = SetupWord
      STOI(ISTOI + 48) = IT_1
      STOF(ISTOF + 229) = BatVolt
      STOF(ISTOF + 232) = Grd_Icc1
      STOF(ISTOF + 235) = Grd_Ibc1
      STOF(ISTOF + 238) = Grd_Iac1
      STOF(ISTOF + 239) = Qmeas

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 72 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 210 + IT_0) = CapCur(IT_0)
         STOF(ISTOF + 215 + IT_0) = BusVolt(IT_0)
         STOF(ISTOF + 217 + IT_0) = GridVolt(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 27 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 57 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 74 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 212 + IT_0) = ModuleCur(IT_0)
         STOF(ISTOF + 239 + IT_0) = TP_iS(IT_0)
         STOF(ISTOF + 242 + IT_0) = Vabc1(IT_0)
         STOF(ISTOF + 266 + IT_0) = TP_iG(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESS_1Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakDyn_Begin  ! 
!     SUBR    FFT_ModDyn_Begin  ! 
!     SUBR    PWM_3LevelDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      INTEGER  DampCoft, VgridHpfFreq, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  IT_1
      REAL     RT_25, RT_26, RT_31, RT_34, RT_36
      REAL     Tsample

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 50
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 62

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakDyn_Begin()


! 50:[breaker3] 3 Phase Breaker 'MCB_DRV2'
      CALL COMPONENT_ID(ICALL_NO,707526076)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 110:[breaker3] 3 Phase Breaker 'MCB_DRV1'
      CALL COMPONENT_ID(ICALL_NO,715928027)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 180:[battery] Generic battery model 'Bat2'
      CALL COMPONENT_ID(ICALL_NO,431765413)
      CALL BATTERYCOEFF1_CFG(SS(1), (IBRCH(1)+16),0.675,1.15,1.03,3.26,0&
     &.95,0.4,80.0,0.005,2.0)

! 220:[consti] Integer Constant 
      OFP3 = 6300

! 240:[consti] Integer Constant 
      OFP2 = 6160

! 250:[battery] Generic battery model 'Bat1'
      CALL COMPONENT_ID(ICALL_NO,1483980752)
      CALL BATTERYCOEFF1_CFG(SS(1), (IBRCH(1)+17),0.675,1.15,1.03,3.26,0&
     &.95,0.4,80.0,0.005,2.0)

! 260:[consti] Integer Constant 
      OFP1 = 6060

! 270:[consti] Integer Constant 
      UFP1 = 5940

! 280:[consti] Integer Constant 
      UFP2 = 5840

! 310:[consti] Integer Constant 
      UFP3 = 5780

! 330:[consti] Integer Constant 
      UFP4 = 5730

! 350:[consti] Integer Constant 
      UFP5 = 5700

! 360:[consti] Integer Constant 
      OFP3Timems = 30000

! 380:[consti] Integer Constant 
      OFP2Timems = 300000

! 390:[consti] Integer Constant 
      OFP1Timems = 300000

! 400:[datamerge] Merges data signals into an array 

! 410:[consti] Integer Constant 
      UFP1Timems = 300000

! 430:[var] Variable Input Slider 'ActivePowerSet'

! 440:[consti] Integer Constant 
      UFP2Timems = 300000

! 450:[consti] Integer Constant 
      UFP3Timems = 300000

! 460:[consti] Integer Constant 
      UFP4Timems = 300000

! 470:[var] Variable Input Slider 'ReactivePowerSet'

! 480:[consti] Integer Constant 
      UFP5Timems = 30000

! 500:[consti] Integer Constant 
      OVP4 = 1300

! 510:[consti] Integer Constant 
      OVP3 = 1175

! 520:[datatap] Scalar/Array Tap 

! 530:[consti] Integer Constant 
      OVP2 = 1150

! 540:[consti] Integer Constant 
      JCoft = 1753844

! 550:[consti] Integer Constant 
      OVP1 = 1100

! 560:[datatap] Scalar/Array Tap 

! 570:[consti] Integer Constant 
      DampCoft = 540000

! 580:[consti] Integer Constant 
      UVP1 = 900

! 590:[consti] Integer Constant 
      CommandWord = 8709

! 600:[consti] Integer Constant 
      UVP2 = 750

! 610:[consti] Integer Constant 
      SetupWord = 34757

! 620:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 630:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 640:[consti] Integer Constant 
      UVP3 = 650

! 650:[consti] Integer Constant 
      SclToBess = 6188

! 660:[consti] Integer Constant 
      UVP4 = 450

! 670:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,338651251)
      CALL E_XSGEN1_CFG(1,0.0,50.0,1.0,-1.0)

! 680:[consti] Integer Constant 
      OVP4Timems = 30000

! 690:[consti] Integer Constant 
      OVP3Timems = 30000

! 700:[FFT_Mod]  
      CALL FFT_ModDyn_Begin()


! 710:[consti] Integer Constant 
      OVP2Timems = 30000

! 720:[consti] Integer Constant 
      OVP1Timems = 30000

! 730:[pgb] Output Channel 'Triasign_PWM'

! 740:[datamerge] Merges data signals into an array 

! 750:[consti] Integer Constant 
      UVP1Timems = 30000

! 760:[consti] Integer Constant 
      IT_1 = 1

! 770:[datamerge] Merges data signals into an array 

! 780:[consti] Integer Constant 
      UVP2Timems = 30000

! 790:[datamerge] Merges data signals into an array 

! 800:[consti] Integer Constant 
      UVP3Timems = 30000

! 810:[pgb] Output Channel 'SOC'

! 820:[consti] Integer Constant 
      UVP4Timems = 30000

! 830:[const] Real Constant 
      RT_25 = 0.0

! 840:[const] Real Constant 
      RT_26 = 0.0

! 850:[time-sig] Output of Simulation Time 

! 860:[compare] Single Input Level Comparator 

! 870:[pgb] Output Channel 'Vlrms'

! 880:[const] Real Constant 
      RT_36 = 1000.0

! 890:[datatap] Scalar/Array Tap 

! 900:[pgb] Output Channel 'P'

! 910:[const] Real Constant 
      RT_34 = 1000.0

! 920:[datatap] Scalar/Array Tap 

! 930:[pgb] Output Channel 'Q'

! 940:[const] Real Constant 
      RT_31 = 1000.0

! 950:[datatap] Scalar/Array Tap 

! 960:[pgb] Output Channel 'I_active'

! 970:[datatap] Scalar/Array Tap 

! 980:[pgb] Output Channel 'I_reactive'

! 1020:[datamerge] Merges data signals into an array 

! 1030:[datamerge] Merges data signals into an array 

! 1040:[datamerge] Merges data signals into an array 

! 1050:[datamerge] Merges data signals into an array 

! 1060:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 1070:[oc_spov]  
      CALL COMPONENT_ID(ICALL_NO,237356938)
      CALL oc_spovDyn_Begin()

! 1080:[mult] Multiplier 

! 1090:[abs] Absolute Value 

! 1100:[compare] Single Input Level Comparator 

! 1110:[mult] Multiplier 

! 1120:[abs] Absolute Value 

! 1130:[compare] Single Input Level Comparator 

! 1140:[mult] Multiplier 

! 1150:[abs] Absolute Value 

! 1160:[compare] Single Input Level Comparator 

! 1170:[special_funcs]  
      CALL COMPONENT_ID(ICALL_NO,50746761)
      CALL special_funcsDyn_Begin()

! 1180:[datamerge] Merges data signals into an array 

! 1190:[Ctrl_1]  

! 1200:[datatap] Scalar/Array Tap 

! 1220:[breaker3] 3 Phase Breaker 'MCB_DRV'
      CALL COMPONENT_ID(ICALL_NO,1405209624)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 1230:[datatap] Scalar/Array Tap 

! 1250:[datatap] Scalar/Array Tap 

! 1300:[datatap] Scalar/Array Tap 

! 1310:[datatap] Scalar/Array Tap 

! 1320:[datatap] Scalar/Array Tap 

! 1330:[mult] Multiplier 

! 1340:[datamerge] Merges data signals into an array 

! 1350:[mult] Multiplier 

! 1360:[datatap] Scalar/Array Tap 

! 1370:[datatap] Scalar/Array Tap 

! 1380:[datatap] Scalar/Array Tap 

! 1390:[mult] Multiplier 

! 1400:[realpole] Real Pole 

! 1410:[pgb] Output Channel 'Qref'

! 1420:[pgb] Output Channel 'PWM_Mod'

! 1430:[mult] Multiplier 

! 1440:[compare] Single Input Level Comparator 

! 1450:[PWM_3Level]  
      CALL PWM_3LevelDyn_Begin()


! 1460:[mult] Multiplier 

! 1470:[pgb] Output Channel 'DebugData2'

! 1480:[pgb] Output Channel 'DebugData1'

! 1490:[pgb] Output Channel 'T10'

! 1500:[mult] Multiplier 

! 1510:[datatap] Scalar/Array Tap 

! 1520:[pgb] Output Channel 'T4'

! 1530:[pgb] Output Channel 'T9'

! 1540:[datatap] Scalar/Array Tap 

! 1550:[pgb] Output Channel 'T3'

! 1560:[datatap] Scalar/Array Tap 

! 1570:[pgb] Output Channel 'PCS Fault'

! 1580:[datatap] Scalar/Array Tap 

! 1590:[pgb] Output Channel 'T2'

! 1600:[datatap] Scalar/Array Tap 

! 1610:[datatap] Scalar/Array Tap 

! 1620:[datatap] Scalar/Array Tap 

! 1630:[pgb] Output Channel 'T7'

! 1640:[mult] Multiplier 

! 1650:[pgb] Output Channel 'T1'

! 1660:[datatap] Scalar/Array Tap 

! 1670:[mult] Multiplier 

! 1680:[datatap] Scalar/Array Tap 

! 1690:[datatap] Scalar/Array Tap 

! 1700:[datatap] Scalar/Array Tap 

! 1710:[datatap] Scalar/Array Tap 

! 1720:[mult] Multiplier 

! 1730:[datatap] Scalar/Array Tap 

! 1740:[datatap] Scalar/Array Tap 

! 1750:[pgb] Output Channel 'PWM'

! 1760:[datatap] Scalar/Array Tap 

! 1770:[datatap] Scalar/Array Tap 

! 1780:[datatap] Scalar/Array Tap 

! 1790:[pgb] Output Channel 'MCB'

! 1800:[datatap] Scalar/Array Tap 

! 1810:[mult] Multiplier 

! 1820:[datatap] Scalar/Array Tap 

! 1830:[pgb] Output Channel 'MC'

! 1840:[datatap] Scalar/Array Tap 

! 1850:[datatap] Scalar/Array Tap 

! 1860:[datatap] Scalar/Array Tap 

! 1870:[pgb] Output Channel 'DC_EN'

! 1880:[pgb] Output Channel 'DC_SS_EN'

! 1890:[pgb] Output Channel 'AC_SS_EN'

! 1910:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+22),SS(1))

! 1930:[source_1] Single Phase Voltage Source Model 2 'Source_1'
      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.05
      NRTCF = NRTCF + 2

! 1940:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+23),SS(1))

! 1960:[source_1] Single Phase Voltage Source Model 2 'Source_1'
      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.05
      NRTCF = NRTCF + 2

! 1970:[breaker3] 3 Phase Breaker 'EN_inv_bk'
      CALL COMPONENT_ID(ICALL_NO,1458862097)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 1990:[src_ccin_1] Current Source 'Source 1_1'
      CALL CURRENT_SOURCE2_CFG( (IBRCH(1)+24),SS(1))

! 2000:[breaker3] 3 Phase Breaker 'AMC_DRV1'
      CALL COMPONENT_ID(ICALL_NO,123013057)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 2010:[breaker1] Single Phase Breaker 'DCC_EN1'
      CALL COMPONENT_ID(ICALL_NO,734835594)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 2020:[source_1] Single Phase Voltage Source Model 2 'Source_1'
      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.05
      NRTCF = NRTCF + 2

! 2050:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
      CALL COMPONENT_ID(ICALL_NO,1311922066)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 2060:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
      CALL COMPONENT_ID(ICALL_NO,757793417)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE BESS_1Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakOut_Begin  ! 
!     SUBR    FFT_ModOut_Begin  ! 
!     SUBR    PWM_3LevelOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_5, NT_17, NT_21, NT_50, NT_51
      INTEGER  NT_52, NT_53

! Control Signals
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      INTEGER  DampCoft, VgridHpfFreq, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  IT_1
      REAL     RT_25, RT_26, RT_31, RT_34, RT_36
      REAL     Tsample

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 50
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 62

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_5  = NODE(INODE + 8)
      NT_17 = NODE(INODE + 21)
      NT_21 = NODE(INODE + 28)
      NT_50 = NODE(INODE + 39)
      NT_51 = NODE(INODE + 12)
      NT_52 = NODE(INODE + 13)
      NT_53 = NODE(INODE + 14)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakOut_Begin()


! 200:[datamerge] Merges data signals into an array 

! 220:[consti] Integer Constant 
      OFP3 = 6300

! 240:[consti] Integer Constant 
      OFP2 = 6160

! 260:[consti] Integer Constant 
      OFP1 = 6060

! 270:[consti] Integer Constant 
      UFP1 = 5940

! 280:[consti] Integer Constant 
      UFP2 = 5840

! 310:[consti] Integer Constant 
      UFP3 = 5780

! 320:[datamerge] Merges data signals into an array 

! 330:[consti] Integer Constant 
      UFP4 = 5730

! 340:[datamerge] Merges data signals into an array 

! 350:[consti] Integer Constant 
      UFP5 = 5700

! 360:[consti] Integer Constant 
      OFP3Timems = 30000

! 370:[datamerge] Merges data signals into an array 

! 380:[consti] Integer Constant 
      OFP2Timems = 300000

! 390:[consti] Integer Constant 
      OFP1Timems = 300000

! 410:[consti] Integer Constant 
      UFP1Timems = 300000

! 420:[datamerge] Merges data signals into an array 

! 440:[consti] Integer Constant 
      UFP2Timems = 300000

! 450:[consti] Integer Constant 
      UFP3Timems = 300000

! 460:[consti] Integer Constant 
      UFP4Timems = 300000

! 480:[consti] Integer Constant 
      UFP5Timems = 30000

! 500:[consti] Integer Constant 
      OVP4 = 1300

! 510:[consti] Integer Constant 
      OVP3 = 1175

! 530:[consti] Integer Constant 
      OVP2 = 1150

! 540:[consti] Integer Constant 
      JCoft = 1753844

! 550:[consti] Integer Constant 
      OVP1 = 1100

! 570:[consti] Integer Constant 
      DampCoft = 540000

! 580:[consti] Integer Constant 
      UVP1 = 900

! 590:[consti] Integer Constant 
      CommandWord = 8709

! 600:[consti] Integer Constant 
      UVP2 = 750

! 610:[consti] Integer Constant 
      SetupWord = 34757

! 620:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 630:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 640:[consti] Integer Constant 
      UVP3 = 650

! 650:[consti] Integer Constant 
      SclToBess = 6188

! 660:[consti] Integer Constant 
      UVP4 = 450

! 680:[consti] Integer Constant 
      OVP4Timems = 30000

! 690:[consti] Integer Constant 
      OVP3Timems = 30000

! 700:[FFT_Mod]  
      CALL FFT_ModOut_Begin()


! 710:[consti] Integer Constant 
      OVP2Timems = 30000

! 720:[consti] Integer Constant 
      OVP1Timems = 30000

! 750:[consti] Integer Constant 
      UVP1Timems = 30000

! 760:[consti] Integer Constant 
      IT_1 = 1

! 780:[consti] Integer Constant 
      UVP2Timems = 30000

! 800:[consti] Integer Constant 
      UVP3Timems = 30000

! 820:[consti] Integer Constant 
      UVP4Timems = 30000

! 830:[const] Real Constant 
      RT_25 = 0.0

! 840:[const] Real Constant 
      RT_26 = 0.0

! 880:[const] Real Constant 
      RT_36 = 1000.0

! 910:[const] Real Constant 
      RT_34 = 1000.0

! 940:[const] Real Constant 
      RT_31 = 1000.0

! 990:[datamerge] Merges data signals into an array 

! 1000:[datamerge] Merges data signals into an array 

! 1010:[datamerge] Merges data signals into an array 

! 1070:[oc_spov]  
      CALL COMPONENT_ID(ICALL_NO,237356938)
      CALL oc_spovOut_Begin()

! 1170:[special_funcs]  
      CALL COMPONENT_ID(ICALL_NO,50746761)
      CALL special_funcsOut_Begin()

! 1450:[PWM_3Level]  
      CALL PWM_3LevelOut_Begin()


! 1900:[datamerge] Merges data signals into an array 

! 1920:[pgb] Output Channel 'Icap'

! 1950:[pgb] Output Channel 'Iabc2'

! 1980:[pgb] Output Channel 'Iabc1'

! 2030:[pgb] Output Channel 'Igabc'

! 2040:[pgb] Output Channel 'Vabc1'

      RETURN
      END

