!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : FFT_Mod
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE FFT_ModDyn(Vab, Vbc, Ia, Ib, Ic, Vab_rms, Vbc_rms,     &
     &   Vca_rms, Ppos, Qpos, IPpos, IQpos)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    DGTL_RMS      ! 'RMS Measurement using Digital Samlping'
!     SUBR    FTN180        ! FFT Calculation

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vab, Vbc, Ia, Ib
      REAL,    INTENT(IN)  :: Ic
      REAL,    INTENT(OUT) :: Ppos, Qpos, IPpos
      REAL,    INTENT(OUT) :: IQpos
      REAL,    INTENT(OUT) :: Vab_rms! Aliases: Vab_RMS_in
      REAL,    INTENT(OUT) :: Vbc_rms! Aliases: Vbc_RMS_in
      REAL,    INTENT(OUT) :: Vca_rms! Aliases: Vca_RMS_in

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3
      REAL     VZM(15), VZP(15), VNM(15), VNP(15)
      REAL     RT_1, RT_2, RT_3, ANG, RT_4, VPM1
      REAL     IPP1, IZM(15), IZP(15), INM(15)
      REAL     INP(15), RT_5, RT_6, RT_7, VIM
      REAL     COSANG, SINANG, IPM1, RT_8, RT_9
      REAL     RT_10, VA, VB, VC, IPPOSSEQ, RT_11
      REAL     IQPOSSEQ, PPOSSEQ, RT_12, QPOSSEQ
      REAL     Vca, VPM(15), IPM(15), VPP1
      REAL     VPP(15), IPP(15)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 3
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 220
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vab_rms  = STOF(ISTOF + 6)
      Vbc_rms  = STOF(ISTOF + 7)
      Vca_rms  = STOF(ISTOF + 8)
      Ppos     = STOF(ISTOF + 9)
      Qpos     = STOF(ISTOF + 10)
      IPpos    = STOF(ISTOF + 11)
      IQpos    = STOF(ISTOF + 12)
      RT_1     = STOF(ISTOF + 73)
      RT_2     = STOF(ISTOF + 74)
      RT_3     = STOF(ISTOF + 75)
      ANG      = STOF(ISTOF + 76)
      RT_4     = STOF(ISTOF + 77)
      VPM1     = STOF(ISTOF + 78)
      IPP1     = STOF(ISTOF + 79)
      RT_5     = STOF(ISTOF + 140)
      RT_6     = STOF(ISTOF + 141)
      RT_7     = STOF(ISTOF + 142)
      VIM      = STOF(ISTOF + 143)
      COSANG   = STOF(ISTOF + 144)
      SINANG   = STOF(ISTOF + 145)
      IPM1     = STOF(ISTOF + 146)
      RT_8     = STOF(ISTOF + 147)
      RT_9     = STOF(ISTOF + 148)
      IT_1     = STOI(ISTOI + 1)
      RT_10    = STOF(ISTOF + 149)
      VA       = STOF(ISTOF + 150)
      IT_2     = STOI(ISTOI + 2)
      VB       = STOF(ISTOF + 151)
      IT_3     = STOI(ISTOI + 3)
      VC       = STOF(ISTOF + 152)
      IPPOSSEQ = STOF(ISTOF + 153)
      RT_11    = STOF(ISTOF + 154)
      IQPOSSEQ = STOF(ISTOF + 155)
      PPOSSEQ  = STOF(ISTOF + 156)
      RT_12    = STOF(ISTOF + 157)
      QPOSSEQ  = STOF(ISTOF + 158)
      Vca      = STOF(ISTOF + 159)
      VPP1     = STOF(ISTOF + 190)

! Array (1:15) quantities...
      DO IT_0 = 1,15
         VZM(IT_0) = STOF(ISTOF + 12 + IT_0)
         VZP(IT_0) = STOF(ISTOF + 27 + IT_0)
         VNM(IT_0) = STOF(ISTOF + 42 + IT_0)
         VNP(IT_0) = STOF(ISTOF + 57 + IT_0)
         IZM(IT_0) = STOF(ISTOF + 79 + IT_0)
         IZP(IT_0) = STOF(ISTOF + 94 + IT_0)
         INM(IT_0) = STOF(ISTOF + 109 + IT_0)
         INP(IT_0) = STOF(ISTOF + 124 + IT_0)
         VPM(IT_0) = STOF(ISTOF + 159 + IT_0)
         IPM(IT_0) = STOF(ISTOF + 174 + IT_0)
         VPP(IT_0) = STOF(ISTOF + 190 + IT_0)
         IPP(IT_0) = STOF(ISTOF + 205 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'FFT_Mod.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_1 = 2

! 30:[rms-inst] Single Phase RMS Meter 
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      NRTCF = NRTCF + 3
      CALL DGTL_RMS(64,RVD1_1,Vab,RVD1_3,RVD1_2,Vab_rms)

! 40:[consti] Integer Constant 
      IT_2 = 3

! 60:[rms-inst] Single Phase RMS Meter 
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      NRTCF = NRTCF + 3
      CALL DGTL_RMS(64,RVD1_1,Vbc,RVD1_3,RVD1_2,Vbc_rms)

! 70:[sumjct] Summing/Differencing Junctions 
      RT_10 = + Vbc - Vab

! 80:[consti] Integer Constant 
      IT_3 = 3

! 90:[sumjct] Summing/Differencing Junctions 
      Vca = - Vab - Vbc

! 150:[const] Real Constant 
      RT_11 = 0.001

! 160:[const] Real Constant 
      RT_12 = 0.001

! 170:[mult] Multiplier 
      RT_8 = Vab * REAL(IT_1)

! 180:[sumjct] Summing/Differencing Junctions 
      RT_9 = + RT_8 + Vbc

! 190:[div] Divider 
      IF (ABS(REAL(IT_2)) .LT. 1.0E-100) THEN
         IF (REAL(IT_2) .LT. 0.0)  THEN
            VA = -1.0E100 * RT_9
         ELSE
            VA =  1.0E100 * RT_9
         ENDIF
      ELSE
         VA = RT_9 / REAL(IT_2)
      ENDIF

! 200:[rms-inst] Single Phase RMS Meter 
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3 = RTCF(NRTCF+2)
      NRTCF = NRTCF + 3
      CALL DGTL_RMS(64,RVD1_1,Vca,RVD1_3,RVD1_2,Vca_rms)

! 210:[div] Divider 
      IF (ABS(REAL(IT_3)) .LT. 1.0E-100) THEN
         IF (REAL(IT_3) .LT. 0.0)  THEN
            VB = -1.0E100 * RT_10
         ELSE
            VB =  1.0E100 * RT_10
         ENDIF
      ELSE
         VB = RT_10 / REAL(IT_3)
      ENDIF

! 220:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL COMPONENT_ID(ICALL_NO,1085205145)
      CALL FTN180(0,0,15,1,60.0,60.0,Ia,IVD1_1,IPM,IPP,RT_5)
      CALL FTN180(0,0,15,1,60.0,60.0,Ib,IVD1_1,INM,INP,RT_7)
      CALL FTN180(0,0,15,1,60.0,60.0,Ic,IVD1_1,IZM,IZP,RT_6)
      CALL FTSEQN(15,0,IPM,INM,IZM,IPP,INP,IZP)
!

! 230:[datatap] Scalar/Array Tap 
      IPP1 = IPP(1)

! 240:[sumjct] Summing/Differencing Junctions 
      VC = - VA - VB

! 250:[fft] On-Line Frequency Scanner 
      IVD1_1=0
      CALL COMPONENT_ID(ICALL_NO,1617191813)
      CALL FTN180(0,0,15,1,60.0,60.0,VA,IVD1_1,VPM,VPP,RT_1)
      CALL FTN180(0,0,15,1,60.0,60.0,VB,IVD1_1,VNM,VNP,RT_3)
      CALL FTN180(0,0,15,1,60.0,60.0,VC,IVD1_1,VZM,VZP,RT_2)
      CALL FTSEQN(15,0,VPM,VNM,VZM,VPP,VNP,VZP)
!

! 260:[datatap] Scalar/Array Tap 
      VPM1 = VPM(1)

! 270:[datatap] Scalar/Array Tap 
      VPP1 = VPP(1)

! 280:[datatap] Scalar/Array Tap 
      IPM1 = IPM(1)

! 290:[sumjct] Summing/Differencing Junctions 
      ANG = + VPP1 - IPP1

! 300:[trig] Trigonometric Functions 
!  Trig-Func
      SINANG = SIN(ANG)
!

! 310:[trig] Trigonometric Functions 
!  Trig-Func
      COSANG = COS(ANG)
!

! 320:[mult] Multiplier 
      RT_4 = IPM1 * VPM1

! 330:[gain] Gain Block 
!  Gain
      VIM = 3.0 * RT_4

! 340:[mult] Multiplier 
      QPOSSEQ = SINANG * VIM

! 350:[mult] Multiplier 
      IQPOSSEQ = SINANG * IPM1

! 360:[mult] Multiplier 
      IPPOSSEQ = COSANG * IPM1

! 370:[div] Divider 
      IF (ABS(RT_12) .LT. 1.0E-100) THEN
         IF (RT_12 .LT. 0.0)  THEN
            Qpos = -1.0E100 * QPOSSEQ
         ELSE
            Qpos =  1.0E100 * QPOSSEQ
         ENDIF
      ELSE
         Qpos = QPOSSEQ / RT_12
      ENDIF

! 380:[mult] Multiplier 
      PPOSSEQ = COSANG * VIM

! 390:[div] Divider 
      IF (ABS(RT_12) .LT. 1.0E-100) THEN
         IF (RT_12 .LT. 0.0)  THEN
            Ppos = -1.0E100 * PPOSSEQ
         ELSE
            Ppos =  1.0E100 * PPOSSEQ
         ENDIF
      ELSE
         Ppos = PPOSSEQ / RT_12
      ENDIF

! 400:[div] Divider 
      IF (ABS(RT_11) .LT. 1.0E-100) THEN
         IF (RT_11 .LT. 0.0)  THEN
            IQpos = -1.0E100 * IQPOSSEQ
         ELSE
            IQpos =  1.0E100 * IQPOSSEQ
         ENDIF
      ELSE
         IQpos = IQPOSSEQ / RT_11
      ENDIF

! 410:[div] Divider 
      IF (ABS(RT_11) .LT. 1.0E-100) THEN
         IF (RT_11 .LT. 0.0)  THEN
            IPpos = -1.0E100 * IPPOSSEQ
         ELSE
            IPpos =  1.0E100 * IPPOSSEQ
         ENDIF
      ELSE
         IPpos = IPPOSSEQ / RT_11
      ENDIF

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Vab
      STOF(ISTOF + 2) = Vbc
      STOF(ISTOF + 3) = Ia
      STOF(ISTOF + 4) = Ib
      STOF(ISTOF + 5) = Ic
      STOF(ISTOF + 6) = Vab_rms
      STOF(ISTOF + 7) = Vbc_rms
      STOF(ISTOF + 8) = Vca_rms
      STOF(ISTOF + 9) = Ppos
      STOF(ISTOF + 10) = Qpos
      STOF(ISTOF + 11) = IPpos
      STOF(ISTOF + 12) = IQpos
      STOF(ISTOF + 73) = RT_1
      STOF(ISTOF + 74) = RT_2
      STOF(ISTOF + 75) = RT_3
      STOF(ISTOF + 76) = ANG
      STOF(ISTOF + 77) = RT_4
      STOF(ISTOF + 78) = VPM1
      STOF(ISTOF + 79) = IPP1
      STOF(ISTOF + 140) = RT_5
      STOF(ISTOF + 141) = RT_6
      STOF(ISTOF + 142) = RT_7
      STOF(ISTOF + 143) = VIM
      STOF(ISTOF + 144) = COSANG
      STOF(ISTOF + 145) = SINANG
      STOF(ISTOF + 146) = IPM1
      STOF(ISTOF + 147) = RT_8
      STOF(ISTOF + 148) = RT_9
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 149) = RT_10
      STOF(ISTOF + 150) = VA
      STOI(ISTOI + 2) = IT_2
      STOF(ISTOF + 151) = VB
      STOI(ISTOI + 3) = IT_3
      STOF(ISTOF + 152) = VC
      STOF(ISTOF + 153) = IPPOSSEQ
      STOF(ISTOF + 154) = RT_11
      STOF(ISTOF + 155) = IQPOSSEQ
      STOF(ISTOF + 156) = PPOSSEQ
      STOF(ISTOF + 157) = RT_12
      STOF(ISTOF + 158) = QPOSSEQ
      STOF(ISTOF + 159) = Vca
      STOF(ISTOF + 190) = VPP1

! Array (1:15) quantities...
      DO IT_0 = 1,15
         STOF(ISTOF + 12 + IT_0) = VZM(IT_0)
         STOF(ISTOF + 27 + IT_0) = VZP(IT_0)
         STOF(ISTOF + 42 + IT_0) = VNM(IT_0)
         STOF(ISTOF + 57 + IT_0) = VNP(IT_0)
         STOF(ISTOF + 79 + IT_0) = IZM(IT_0)
         STOF(ISTOF + 94 + IT_0) = IZP(IT_0)
         STOF(ISTOF + 109 + IT_0) = INM(IT_0)
         STOF(ISTOF + 124 + IT_0) = INP(IT_0)
         STOF(ISTOF + 159 + IT_0) = VPM(IT_0)
         STOF(ISTOF + 174 + IT_0) = IPM(IT_0)
         STOF(ISTOF + 190 + IT_0) = VPP(IT_0)
         STOF(ISTOF + 205 + IT_0) = IPP(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Vab_rms  is output
      !Vbc_rms  is output
      !Vca_rms  is output
      !Ppos     is output
      !Qpos     is output
      !IPpos    is output
      !IQpos    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE FFT_ModOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3
      REAL     RT_11, RT_12

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_1     = STOI(ISTOI + 1)
      IT_2     = STOI(ISTOI + 2)
      IT_3     = STOI(ISTOI + 3)
      RT_11    = STOF(ISTOF + 154)
      RT_12    = STOF(ISTOF + 157)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'FFT_Mod.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 

      IT_1 = 2

! 40:[consti] Integer Constant 

      IT_2 = 3

! 80:[consti] Integer Constant 

      IT_3 = 3

! 150:[const] Real Constant 

      RT_11 = 0.001

! 160:[const] Real Constant 

      RT_12 = 0.001

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = IT_1
      STOI(ISTOI + 2) = IT_2
      STOI(ISTOI + 3) = IT_3
      STOF(ISTOF + 154) = RT_11
      STOF(ISTOF + 157) = RT_12


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE FFT_ModDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3
      REAL     RT_11, RT_12

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_1 = 2

! 30:[rms-inst] Single Phase RMS Meter 
      RTCF(NRTCF)   = 60.0
      RTCF(NRTCF+1) = 0.0
      IF (0.69 .GT. 1.0E-20) THEN
        RTCF(NRTCF+2) = 1.0/0.69
      ELSE
        RTCF(NRTCF+2) = 1.0
      ENDIF
      NRTCF = NRTCF + 3

! 40:[consti] Integer Constant 
      IT_2 = 3

! 60:[rms-inst] Single Phase RMS Meter 
      RTCF(NRTCF)   = 60.0
      RTCF(NRTCF+1) = 0.0
      IF (0.69 .GT. 1.0E-20) THEN
        RTCF(NRTCF+2) = 1.0/0.69
      ELSE
        RTCF(NRTCF+2) = 1.0
      ENDIF
      NRTCF = NRTCF + 3

! 70:[sumjct] Summing/Differencing Junctions 

! 80:[consti] Integer Constant 
      IT_3 = 3

! 90:[sumjct] Summing/Differencing Junctions 

! 150:[const] Real Constant 
      RT_11 = 0.001

! 160:[const] Real Constant 
      RT_12 = 0.001

! 170:[mult] Multiplier 

! 180:[sumjct] Summing/Differencing Junctions 

! 190:[div] Divider 

! 200:[rms-inst] Single Phase RMS Meter 
      RTCF(NRTCF)   = 60.0
      RTCF(NRTCF+1) = 0.0
      IF (0.69 .GT. 1.0E-20) THEN
        RTCF(NRTCF+2) = 1.0/0.69
      ELSE
        RTCF(NRTCF+2) = 1.0
      ENDIF
      NRTCF = NRTCF + 3

! 210:[div] Divider 

! 220:[fft] On-Line Frequency Scanner 

! 230:[datatap] Scalar/Array Tap 

! 240:[sumjct] Summing/Differencing Junctions 

! 250:[fft] On-Line Frequency Scanner 

! 260:[datatap] Scalar/Array Tap 

! 270:[datatap] Scalar/Array Tap 

! 280:[datatap] Scalar/Array Tap 

! 290:[sumjct] Summing/Differencing Junctions 

! 300:[trig] Trigonometric Functions 

! 310:[trig] Trigonometric Functions 

! 320:[mult] Multiplier 

! 330:[gain] Gain Block 

! 340:[mult] Multiplier 

! 350:[mult] Multiplier 

! 360:[mult] Multiplier 

! 370:[div] Divider 

! 380:[mult] Multiplier 

! 390:[div] Divider 

! 400:[div] Divider 

! 410:[div] Divider 

      RETURN
      END

!=======================================================================

      SUBROUTINE FFT_ModOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3
      REAL     RT_11, RT_12

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_1 = 2

! 40:[consti] Integer Constant 
      IT_2 = 3

! 80:[consti] Integer Constant 
      IT_3 = 3

! 150:[const] Real Constant 
      RT_11 = 0.001

! 160:[const] Real Constant 
      RT_12 = 0.001

      RETURN
      END

