!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : Main Page
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    TSAT21        ! Transformer Saturation Subroutine
!     SUBR    BESS_1Dyn     ! 
!     SUBR    3PHVSRC       ! 3-Phase Source model

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_3, NT_4(3), NT_6(3), NT_7(3)

! Control Signals
      REAL     RT_1(2), Pref, Qref, Pterm, Qterm
      REAL     Vterm, Vins_term(3), Iins_Term(3)
      REAL     RT_2

! Internal Variables
      REAL     RVD1_1, OLD_CCIN_a1, OLD_CCIN_b1
      REAL     OLD_CCIN_c1, OLD_CCIN_a2
      REAL     OLD_CCIN_b2, OLD_CCIN_c2
      REAL     NEW_CCIN_a1, NEW_CCIN_b1
      REAL     NEW_CCIN_c1, NEW_CCIN_a2
      REAL     NEW_CCIN_b2, NEW_CCIN_c2, IMKa_OLD
      REAL     IMKb_OLD, IMKc_OLD, IKMa_OLD
      REAL     IKMb_OLD, IKMc_OLD, IZom, IZo
      REAL     Scl1, X_KNEE, TURNS_V, RVD1_2
      REAL     RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 14
      NPGB      = NPGB + 9
      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 21
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 19

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Pref     = STOF(ISTOF + 3)
      Qref     = STOF(ISTOF + 4)
      Pterm    = STOF(ISTOF + 5)
      Qterm    = STOF(ISTOF + 6)
      Vterm    = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 14)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_1(IT_0) = STOF(ISTOF + 0 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vins_term(IT_0) = STOF(ISTOF + 7 + IT_0)
         Iins_Term(IT_0) = STOF(ISTOF + 10 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_3  = NODE(INODE + 7)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_4(IT_0) = NODE(INODE + 7 + IT_0)
         NT_6(IT_0) = NODE(INODE + 13 + IT_0)
         NT_7(IT_0) = NODE(INODE + 16 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[var] Variable Input Slider 'ActivePowerSet'
      Pref = CX(CXMAP(ICX+1))

! 20:[var] Variable Input Slider 'ReactivePowerSet'
      Qref = CX(CXMAP(ICX+2))

! 30:[const] Real Constant 
      RT_2 = 20.0

! 40:[datamerge] Merges data signals into an array 
      RT_1(1) = Pref
      RT_1(2) = Qref

! 60:[xfmr_2w_scaled] 3 Phase 2 Winding Transformer - With Scaling! 'T32_1'




      IZo = 1.0/((0.0575*0.69*0.69)/(2.0*0.2731*TWO_PI*60.0*DELT))
      Scl1 = RT_2-1
      IZom = Scl1*IZo

! Recall current injections from the last time step
      OLD_CCIN_a1 = STORF(NSTORF+0)
      OLD_CCIN_b1 = STORF(NSTORF+1)
      OLD_CCIN_c1 = STORF(NSTORF+2)
      OLD_CCIN_a2 = STORF(NSTORF+3)
      OLD_CCIN_b2 = STORF(NSTORF+4)
      OLD_CCIN_c2 = STORF(NSTORF+5)

! Compute the branch currents from the last time step
      IMKa_OLD =  VDC(NT_6(1),SS(1))*IZo - OLD_CCIN_a2
      IMKb_OLD =  VDC(NT_6(2),SS(1))*IZo - OLD_CCIN_b2
      IMKc_OLD =  VDC(NT_6(3),SS(1))*IZo - OLD_CCIN_c2
      IKMa_OLD =  VDC(NT_7(1),SS(1))*IZo - OLD_CCIN_a1
      IKMb_OLD =  VDC(NT_7(2),SS(1))*IZo - OLD_CCIN_b1
      IKMc_OLD =  VDC(NT_7(3),SS(1))*IZo - OLD_CCIN_c1


! Define the new current injections
      NEW_CCIN_a1 = VDC(NT_6(1), SS(1))*IZo + IMKa_OLD + (VDC(NT_6(1), S&
     &S(1))*IZo + IMKa_OLD)*Scl1
      NEW_CCIN_b1 = VDC(NT_6(2), SS(1))*IZo + IMKb_OLD + (VDC(NT_6(2), S&
     &S(1))*IZo + IMKb_OLD)*Scl1
      NEW_CCIN_c1 = VDC(NT_6(3), SS(1))*IZo + IMKc_OLD + (VDC(NT_6(3), S&
     &S(1))*IZo + IMKc_OLD)*Scl1
      NEW_CCIN_a2 = VDC(NT_7(1), SS(1))*IZo + IKMa_OLD
      NEW_CCIN_b2 = VDC(NT_7(2), SS(1))*IZo + IKMb_OLD
      NEW_CCIN_c2 = VDC(NT_7(3), SS(1))*IZo + IKMc_OLD

! Put current injections into the EMTDC main program using CCIN
      CCIN(NT_6(1), SS(1)) = CCIN(NT_6(1), SS(1)) + NEW_CCIN_a2
      CCIN(NT_6(2), SS(1)) = CCIN(NT_6(2), SS(1)) + NEW_CCIN_b2
      CCIN(NT_6(3), SS(1)) = CCIN(NT_6(3), SS(1)) + NEW_CCIN_c2
      CCIN(NT_7(1), SS(1)) = CCIN(NT_7(1), SS(1)) + NEW_CCIN_a1
      CCIN(NT_7(2), SS(1)) = CCIN(NT_7(2), SS(1)) + NEW_CCIN_b1
      CCIN(NT_7(3), SS(1)) = CCIN(NT_7(3), SS(1)) + NEW_CCIN_c1

! Ensure main program records CCIN current injections at these nodes
      IF ( TIMEZERO ) THEN
         ENABCCIN(NT_6(1), SS(1)) = .TRUE.
         ENABCCIN(NT_6(2), SS(1)) = .TRUE.
         ENABCCIN(NT_6(3), SS(1)) = .TRUE.
         ENABCCIN(NT_7(1), SS(1)) = .TRUE.
         ENABCCIN(NT_7(2), SS(1)) = .TRUE.
         ENABCCIN(NT_7(3), SS(1)) = .TRUE.
      ENDIF

         GGIN(NT_6(1),SS(1)) = GGIN(NT_6(1),SS(1)) + IZo
         GGIN(NT_6(2),SS(1)) = GGIN(NT_6(2),SS(1)) + IZo
         GGIN(NT_6(3),SS(1)) = GGIN(NT_6(3),SS(1)) + IZo
         GGIN(NT_7(1),SS(1)) = GGIN(NT_7(1),SS(1)) + IZo + IZom
         GGIN(NT_7(2),SS(1)) = GGIN(NT_7(2),SS(1)) + IZo + IZom
         GGIN(NT_7(3),SS(1)) = GGIN(NT_7(3),SS(1)) + IZo + IZom


! Save current injections for use in the next time step to compute the branch currents
      STORF(NSTORF+0) = VDC(NT_6(1), SS(1))*IZo + IMKa_OLD
      STORF(NSTORF+1) = VDC(NT_6(2), SS(1))*IZo + IMKb_OLD
      STORF(NSTORF+2) = VDC(NT_6(3), SS(1))*IZo + IMKc_OLD
      STORF(NSTORF+3) = VDC(NT_7(1), SS(1))*IZo + IKMa_OLD
      STORF(NSTORF+4) = VDC(NT_7(2), SS(1))*IZo + IKMb_OLD
      STORF(NSTORF+5) = VDC(NT_7(3), SS(1))*IZo + IKMc_OLD
      NSTORF = NSTORF + 6

! 60:[xfmr_2w_scaled] 3 Phase 2 Winding Transformer - With Scaling! 'T32_1'
!  TRANSFORMER SATURATION SUBROUTINE
      IF (TIME.GT.0.1) THEN
         X_KNEE = 1.17
      ELSE
         X_KNEE = -1.17
      ENDIF
      TURNS_V = 0.398371685741
      CALL TSAT21(NT_4(1),NT_3, NT_4(2),NT_3, NT_4(3),NT_3,SS(1),0.09103&
     &33333333,TURNS_V,0.12,X_KNEE,60.0,1.0,0.014, 0.0, 0)
!

! 70:[BESS_1]  
      CALL BESS_1Dyn(RT_1)


! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
! Three Phase Source: Source 1  Type: Ideal
!  
      RVD1_1 = RTCF(NRTCF)
      RVD1_2 = RTCF(NRTCF+1)
      RVD1_3  = 0.0*PI_BY180
      RVD1_4 = RTCF(NRTCF+3)
      NRTCF  = NRTCF + 4
      CALL EMTDC_3PHVSRC(SS(1), (IBRCH(1)+4), (IBRCH(1)+5), (IBRCH(1)+6)&
     &, RVD1_4, .TRUE., RVD1_1 , RVD1_2, RVD1_3)
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 3) = Pref
      STOF(ISTOF + 4) = Qref
      STOF(ISTOF + 5) = Pterm
      STOF(ISTOF + 6) = Qterm
      STOF(ISTOF + 7) = Vterm
      STOF(ISTOF + 14) = RT_2

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = RT_1(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 7 + IT_0) = Vins_term(IT_0)
         STOF(ISTOF + 10 + IT_0) = Iins_Term(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    BESS_1Out     ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_7(3)

! Control Signals
      REAL     Pterm, Qterm, Vterm, Vins_term(3)
      REAL     Iins_Term(3), RT_2

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 9
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 21
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 19

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Pterm    = STOF(ISTOF + 5)
      Qterm    = STOF(ISTOF + 6)
      Vterm    = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 14)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vins_term(IT_0) = STOF(ISTOF + 7 + IT_0)
         Iins_Term(IT_0) = STOF(ISTOF + 10 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_7(IT_0) = NODE(INODE + 16 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 

      RT_2 = 20.0

! 50:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Iins_Term(1) = ( CBR((IBRCH(1)+1), SS(1)))
      Iins_Term(2) = ( CBR((IBRCH(1)+2), SS(1)))
      Iins_Term(3) = ( CBR((IBRCH(1)+3), SS(1)))
      Vins_term(1) = EMTDC_VVDC(SS(1), NT_7(1), 0)
      Vins_term(2) = EMTDC_VVDC(SS(1), NT_7(2), 0)
      Vins_term(3) = EMTDC_VVDC(SS(1), NT_7(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (&
     &IBRCH(1)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,805770946,RVD1_1,"Pd")
      Pterm = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (&
     &IBRCH(1)+3),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,805770946,RVD1_1,"Qd")
      Qterm = RVD1_1
      CALL DGTL_RMS3(256,SS(1),NT_7(1),NT_7(2),NT_7(3),RTCF(IVD1_1+3),1.&
     &0,0.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,805770946,RVD1_1,"Vd")
      Vterm = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,805770946,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,805770946,1,"hide2")
      ENDIF

! 70:[BESS_1]  
      CALL BESS_1Out()


! 80:[pgb] Output Channel 'Iins_Term'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = Iins_Term(IVD1_1)
      ENDDO

! 90:[pgb] Output Channel 'Vins_term'

      DO IVD1_1 = 1, 3
         PGB(IPGB+4+IVD1_1-1) = Vins_term(IVD1_1)
      ENDDO

! 100:[pgb] Output Channel 'Vterm'

      PGB(IPGB+7) = Vterm

! 110:[pgb] Output Channel 'Qterm'

      PGB(IPGB+8) = Qterm

! 120:[pgb] Output Channel 'Pterm'

      PGB(IPGB+9) = Pterm

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 5) = Pterm
      STOF(ISTOF + 6) = Qterm
      STOF(ISTOF + 7) = Vterm
      STOF(ISTOF + 14) = RT_2

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 7 + IT_0) = Vins_term(IT_0)
         STOF(ISTOF + 10 + IT_0) = Iins_Term(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    BESS_1Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_2

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 21
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 19

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[var] Variable Input Slider 'ActivePowerSet'

! 20:[var] Variable Input Slider 'ReactivePowerSet'

! 30:[const] Real Constant 
      RT_2 = 20.0

! 40:[datamerge] Merges data signals into an array 

! 60:[xfmr_2w_scaled] 3 Phase 2 Winding Transformer - With Scaling! 'T32_1'

! 70:[BESS_1]  
      CALL BESS_1Dyn_Begin()


! 1:[source_3] Three Phase Voltage Source Model 2 'Source 1'
      RTCF(NRTCF)   = 0.69*SQRT_2*SQRT_1BY3
      RTCF(NRTCF+1) = 60.0*TWO_PI
      RTCF(NRTCF+3) = 0.05
      NRTCF = NRTCF + 4

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    BESS_1Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_7(3)

! Control Signals
      REAL     RT_2

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr
      INTEGER IXFMR


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 21
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 3
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 19

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_7(IT_0) = NODE(INODE + 16 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 
      RT_2 = 20.0

! 50:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(0.69) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(0.69)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = 60.0

! 70:[BESS_1]  
      CALL BESS_1Out_Begin()


! 80:[pgb] Output Channel 'Iins_Term'

! 90:[pgb] Output Channel 'Vins_term'

! 100:[pgb] Output Channel 'Vterm'

! 110:[pgb] Output Channel 'Qterm'

! 120:[pgb] Output Channel 'Pterm'

      RETURN
      END

