!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : PWM_3Level
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE PWM_3LevelDyn(dutyA, dutyB, dutyC, PWM, Tria, PWM_EN)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: dutyA, dutyB, dutyC
      REAL,    INTENT(IN)  :: Tria, PWM_EN(4)
      REAL,    INTENT(OUT) :: PWM(12)

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5, IT_6
      INTEGER  IT_7, IT_8, IT_9, IT_10, IT_11
      INTEGER  IT_12, IT_13, IT_14, IT_15, IT_16
      INTEGER  IT_17, IT_18, IT_19, IT_20, IT_21
      INTEGER  IT_22
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, PWMEN
      REAL     RT_11, RT_12, RT_13, RT_14, REn
      REAL     SEn, TEn

! Internal Variables
      REAL     RVD2_1(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 22
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 38
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 21)
      RT_2     = STOF(ISTOF + 22)
      IT_1     = STOI(ISTOI + 1)
      IT_2     = STOI(ISTOI + 2)
      IT_3     = STOI(ISTOI + 3)
      IT_4     = STOI(ISTOI + 4)
      IT_5     = STOI(ISTOI + 5)
      IT_6     = STOI(ISTOI + 6)
      IT_7     = STOI(ISTOI + 7)
      IT_8     = STOI(ISTOI + 8)
      IT_9     = STOI(ISTOI + 9)
      IT_10    = STOI(ISTOI + 10)
      IT_11    = STOI(ISTOI + 11)
      IT_12    = STOI(ISTOI + 12)
      RT_3     = STOF(ISTOF + 23)
      RT_4     = STOF(ISTOF + 24)
      IT_13    = STOI(ISTOI + 13)
      IT_14    = STOI(ISTOI + 14)
      RT_5     = STOF(ISTOF + 25)
      IT_15    = STOI(ISTOI + 15)
      RT_6     = STOF(ISTOF + 26)
      IT_16    = STOI(ISTOI + 16)
      RT_7     = STOF(ISTOF + 27)
      IT_17    = STOI(ISTOI + 17)
      RT_8     = STOF(ISTOF + 28)
      IT_18    = STOI(ISTOI + 18)
      RT_9     = STOF(ISTOF + 29)
      IT_19    = STOI(ISTOI + 19)
      IT_20    = STOI(ISTOI + 20)
      IT_21    = STOI(ISTOI + 21)
      IT_22    = STOI(ISTOI + 22)
      RT_10    = STOF(ISTOF + 30)
      PWMEN    = STOF(ISTOF + 31)
      RT_11    = STOF(ISTOF + 32)
      RT_12    = STOF(ISTOF + 33)
      RT_13    = STOF(ISTOF + 34)
      RT_14    = STOF(ISTOF + 35)
      REn      = STOF(ISTOF + 36)
      SEn      = STOF(ISTOF + 37)
      TEn      = STOF(ISTOF + 38)

! Array (1:12) quantities...
      DO IT_0 = 1,12
         PWM(IT_0) = STOF(ISTOF + 3 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PWM_3Level.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 
      PWMEN = PWM_EN(1)

! 30:[const] Real Constant 
      RT_11 = 1.0

! 40:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(PWMEN) .NE. 0) .AND. (NINT(PWMEN) .NE. 0) ) THEN
        IT_19 = 0
      ELSE
        IT_19 = 1
      ENDIF

! 50:[datatap] Scalar/Array Tap 
      REn = PWM_EN(2)

! 60:[datatap] Scalar/Array Tap 
      SEn = PWM_EN(3)

! 70:[const] Real Constant 
      RT_14 = 0.5

! 80:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(REn) .NE. 0) .AND. (NINT(REn) .NE. 0) ) THEN
        IT_20 = 0
      ELSE
        IT_20 = 1
      ENDIF

! 90:[datatap] Scalar/Array Tap 
      TEn = PWM_EN(4)

! 120:[const] Real Constant 
      RT_3 = 1.0

! 130:[const] Real Constant 
      RT_10 = 0.5

! 140:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(SEn) .NE. 0) .AND. (NINT(SEn) .NE. 0) ) THEN
        IT_21 = 0
      ELSE
        IT_21 = 1
      ENDIF

! 160:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(TEn) .NE. 0) .AND. (NINT(TEn) .NE. 0) ) THEN
        IT_22 = 0
      ELSE
        IT_22 = 1
      ENDIF

! 180:[sumjct] Summing/Differencing Junctions 
      RT_12 = - RT_11 + Tria

! 190:[mult] Multiplier 
      RT_13 = RT_12 * RT_14

! 200:[sumjct] Summing/Differencing Junctions 
      RT_4 = + Tria + RT_3

! 210:[mult] Multiplier 
      RT_1 = RT_4 * RT_10

! 220:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyA,RT_13,1.0,0.0,0.0,RVD2_1)
      RT_5 = RVD2_1(1)

! 230:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_5) .NE. 0) .AND. (IT_20 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_2 = 1
      ELSE
        IT_2 = 0
      ENDIF

! 240:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_5) .NE. 0) .AND. (NINT(RT_5) .NE. 0) ) THEN
        IT_14 = 0
      ELSE
        IT_14 = 1
      ENDIF

! 250:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_14 .NE. 0) .AND. (IT_20 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_4 = 1
      ELSE
        IT_4 = 0
      ENDIF

! 260:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyB,RT_1,1.0,0.0,0.0,RVD2_1)
      RT_6 = RVD2_1(1)

! 270:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_6) .NE. 0) .AND. (IT_21 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_5 = 1
      ELSE
        IT_5 = 0
      ENDIF

! 280:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_6) .NE. 0) .AND. (NINT(RT_6) .NE. 0) ) THEN
        IT_15 = 0
      ELSE
        IT_15 = 1
      ENDIF

! 290:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_15 .NE. 0) .AND. (IT_21 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_7 = 1
      ELSE
        IT_7 = 0
      ENDIF

! 300:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyB,RT_13,1.0,0.0,0.0,RVD2_1)
      RT_7 = RVD2_1(1)

! 310:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_7) .NE. 0) .AND. (IT_21 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_6 = 1
      ELSE
        IT_6 = 0
      ENDIF

! 320:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_7) .NE. 0) .AND. (NINT(RT_7) .NE. 0) ) THEN
        IT_16 = 0
      ELSE
        IT_16 = 1
      ENDIF

! 330:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_16 .NE. 0) .AND. (IT_21 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_8 = 1
      ELSE
        IT_8 = 0
      ENDIF

! 340:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyC,RT_1,1.0,0.0,0.0,RVD2_1)
      RT_8 = RVD2_1(1)

! 350:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_8) .NE. 0) .AND. (IT_22 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_9 = 1
      ELSE
        IT_9 = 0
      ENDIF

! 360:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_8) .NE. 0) .AND. (NINT(RT_8) .NE. 0) ) THEN
        IT_17 = 0
      ELSE
        IT_17 = 1
      ENDIF

! 370:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_17 .NE. 0) .AND. (IT_22 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_11 = 1
      ELSE
        IT_11 = 0
      ENDIF

! 380:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyC,RT_13,1.0,0.0,0.0,RVD2_1)
      RT_9 = RVD2_1(1)

! 390:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_9) .NE. 0) .AND. (IT_22 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_10 = 1
      ELSE
        IT_10 = 0
      ENDIF

! 400:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_9) .NE. 0) .AND. (NINT(RT_9) .NE. 0) ) THEN
        IT_18 = 0
      ELSE
        IT_18 = 1
      ENDIF

! 410:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_18 .NE. 0) .AND. (IT_22 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_12 = 1
      ELSE
        IT_12 = 0
      ENDIF

! 420:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,dutyA,RT_1,1.0,0.0,0.0,RVD2_1)
      RT_2 = RVD2_1(1)

! 430:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_2) .NE. 0) .AND. (IT_20 .NE. 0) .AND. (IT_19 .NE. 0)&
     & ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 440:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(RT_2) .NE. 0) .AND. (NINT(RT_2) .NE. 0) ) THEN
        IT_13 = 0
      ELSE
        IT_13 = 1
      ENDIF

! 450:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_13 .NE. 0) .AND. (IT_20 .NE. 0) .AND. (IT_19 .NE. 0) ) TH&
     &EN
        IT_3 = 1
      ELSE
        IT_3 = 0
      ENDIF

! 460:[datamerge] Merges data signals into an array 
      PWM(1) = REAL(IT_1)
      PWM(2) = REAL(IT_2)
      PWM(3) = REAL(IT_3)
      PWM(4) = REAL(IT_4)
      PWM(5) = REAL(IT_5)
      PWM(6) = REAL(IT_6)
      PWM(7) = REAL(IT_7)
      PWM(8) = REAL(IT_8)
      PWM(9) = REAL(IT_9)
      PWM(10) = REAL(IT_10)
      PWM(11) = REAL(IT_11)
      PWM(12) = REAL(IT_12)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = dutyA
      STOF(ISTOF + 2) = dutyB
      STOF(ISTOF + 3) = dutyC
      STOF(ISTOF + 16) = Tria
      STOF(ISTOF + 21) = RT_1
      STOF(ISTOF + 22) = RT_2
      STOI(ISTOI + 1) = IT_1
      STOI(ISTOI + 2) = IT_2
      STOI(ISTOI + 3) = IT_3
      STOI(ISTOI + 4) = IT_4
      STOI(ISTOI + 5) = IT_5
      STOI(ISTOI + 6) = IT_6
      STOI(ISTOI + 7) = IT_7
      STOI(ISTOI + 8) = IT_8
      STOI(ISTOI + 9) = IT_9
      STOI(ISTOI + 10) = IT_10
      STOI(ISTOI + 11) = IT_11
      STOI(ISTOI + 12) = IT_12
      STOF(ISTOF + 23) = RT_3
      STOF(ISTOF + 24) = RT_4
      STOI(ISTOI + 13) = IT_13
      STOI(ISTOI + 14) = IT_14
      STOF(ISTOF + 25) = RT_5
      STOI(ISTOI + 15) = IT_15
      STOF(ISTOF + 26) = RT_6
      STOI(ISTOI + 16) = IT_16
      STOF(ISTOF + 27) = RT_7
      STOI(ISTOI + 17) = IT_17
      STOF(ISTOF + 28) = RT_8
      STOI(ISTOI + 18) = IT_18
      STOF(ISTOF + 29) = RT_9
      STOI(ISTOI + 19) = IT_19
      STOI(ISTOI + 20) = IT_20
      STOI(ISTOI + 21) = IT_21
      STOI(ISTOI + 22) = IT_22
      STOF(ISTOF + 30) = RT_10
      STOF(ISTOF + 31) = PWMEN
      STOF(ISTOF + 32) = RT_11
      STOF(ISTOF + 33) = RT_12
      STOF(ISTOF + 34) = RT_13
      STOF(ISTOF + 35) = RT_14
      STOF(ISTOF + 36) = REn
      STOF(ISTOF + 37) = SEn
      STOF(ISTOF + 38) = TEn

! Array (1:4) quantities...
      DO IT_0 = 1,4
         STOF(ISTOF + 16 + IT_0) = PWM_EN(IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         STOF(ISTOF + 3 + IT_0) = PWM(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !PWM      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PWM_3LevelOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_10, RT_11, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_3     = STOF(ISTOF + 23)
      RT_10    = STOF(ISTOF + 30)
      RT_11    = STOF(ISTOF + 32)
      RT_14    = STOF(ISTOF + 35)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PWM_3Level.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 

      RT_11 = 1.0

! 70:[const] Real Constant 

      RT_14 = 0.5

! 120:[const] Real Constant 

      RT_3 = 1.0

! 130:[const] Real Constant 

      RT_10 = 0.5

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 23) = RT_3
      STOF(ISTOF + 30) = RT_10
      STOF(ISTOF + 32) = RT_11
      STOF(ISTOF + 35) = RT_14


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PWM_3LevelDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_10, RT_11, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

! 30:[const] Real Constant 
      RT_11 = 1.0

! 50:[datatap] Scalar/Array Tap 

! 60:[datatap] Scalar/Array Tap 

! 70:[const] Real Constant 
      RT_14 = 0.5

! 90:[datatap] Scalar/Array Tap 

! 120:[const] Real Constant 
      RT_3 = 1.0

! 130:[const] Real Constant 
      RT_10 = 0.5

! 180:[sumjct] Summing/Differencing Junctions 

! 190:[mult] Multiplier 

! 200:[sumjct] Summing/Differencing Junctions 

! 210:[mult] Multiplier 

! 220:[compar] Two Input Comparator 

! 260:[compar] Two Input Comparator 

! 300:[compar] Two Input Comparator 

! 340:[compar] Two Input Comparator 

! 380:[compar] Two Input Comparator 

! 420:[compar] Two Input Comparator 

! 460:[datamerge] Merges data signals into an array 

      RETURN
      END

!=======================================================================

      SUBROUTINE PWM_3LevelOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_10, RT_11, RT_14

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 
      RT_11 = 1.0

! 70:[const] Real Constant 
      RT_14 = 0.5

! 120:[const] Real Constant 
      RT_3 = 1.0

! 130:[const] Real Constant 
      RT_10 = 0.5

      RETURN
      END

