!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : BESS
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE BESSDyn(PQref)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakDyn      ! 
!     SUBR    FFT_ModDyn    ! 
!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    REALPOLE      ! Real Pole
!     SUBR    PWM_3LevelDyn  ! 
!     SUBR    ThreePhase_3LevelDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: PQref(2)

! Electrical Node Indices

! Control Signals
      INTEGER  MCB_DRV1, MCB_DRV, VSGEn
      INTEGER  VgridHpfFreq, GainK, DroopCoft
      INTEGER  DampCoft, JCoft, SclToBess
      INTEGER  CommandWord, SetupWord, UFP5, UFP4
      INTEGER  UFP3, UFP2, OFP3, OFP2, OFP1, UFP1
      INTEGER  UFP5Timems, UFP4Timems, UFP3Timems
      INTEGER  OFP3Timems, OFP2Timems, OFP1Timems
      INTEGER  UFP2Timems, UFP1Timems, UVP4Timems
      INTEGER  UVP3Timems, UVP4, UVP3, OVP4, OVP3
      INTEGER  OVP2, OVP1, UVP2, UVP1, UVP1Timems
      INTEGER  UVP2Timems, OVP4Timems, OVP3Timems
      INTEGER  OVP2Timems, OVP1Timems, RPWM_EN
      INTEGER  PWM_EN1, SPWM_EN, TPWM_EN, OCP_ENx
      INTEGER  spov_trip, spov_gblock, oc_block
      REAL     Vab0, Vbc0, RT_1, RT_2, RT_3, RT_4
      REAL     RT_5, RT_6, RT_7, PWMDRV1(12)
      REAL     Duty_M1A, Duty_M1B, Duty_M1C
      REAL     Ibat1, BatVolt, Vca0, RT_8(3)
      REAL     RT_9(4), RT_10(4), RT_11(4)
      REAL     RT_12(4), RT_13(4), RT_14(4)
      REAL     NotchEn, DCC_EN1, ACSSC_DRV1
      REAL     RT_15(3), Ug_rms_LV(3), RT_16
      REAL     RT_17, RT_18, RT_19, RT_20, RT_21
      REAL     Bat_SOC, Grd_Ia1, Grd_Ib1
      REAL     RT_22(2), RT_23(3), TP_ia, TP_ib
      REAL     TP_ic, Triasign, PWM_EN1x, Qref
      REAL     RT_24, RT_25, RT_26, RT_27, RT_28
      REAL     RT_29, Tsample, DebugData2(16)
      REAL     DebugData1(16), PWM_EN(4)
      REAL     Duty_M4(3), Duty_M3(3), Duty_M2(3)
      REAL     Duty_M1(3), DCSSC_DRV(4)
      REAL     DCC_DRV(4), ACSSC_DRV(4)
      REAL     ACM_DRV(4), MCB_DRVx, BattMeas(3)
      REAL     PQRefSet(2), CapCur(2)
      REAL     ModuleCur(3), BusVolt(2)
      REAL     GridVolt(2), FrequenceTripTh(8)
      REAL     FrequenceTripTime(8)
      REAL     VoltageTripTh(8)
      REAL     VoltageTripTime(8), PWM1_EN(4)
      REAL     Rocp, Rabs, RT_30, Grd_Iac1, RT_31
      REAL     Sabs, RT_32, Grd_Ibc1, RT_33, Tabs
      REAL     RT_34, Grd_Icc1, RT_35, OCP_EN
      REAL     PWM_EN2, PWM_EN3, PWM_EN4
      REAL     PWM1_EN_OLD(4), Socp, Tocp
      REAL     Grd_Vdc1, Grd_Vdc2, RT_36(2)
      REAL     TP_iS(3), Vabc1(3), Qmeas
      REAL     AMC_DRV1, AMC_DRV2, AMC_DRV3
      REAL     AMC_DRV4, DCC_EN2, DCC_EN3
      REAL     DCC_EN4, DCC_SS_EN1, DCC_SS_EN2
      REAL     DCC_SS_EN3, ACSSC_DRV3, ACSSC_DRV4
      REAL     PQ_pos(2), IPQ_pos(2), FreqSet
      REAL     VoltSet, Pref, Qref1, TP_iG(3)
      REAL     Bat_SOC2

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD2_1(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ICX, IPGB                           ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 51
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 265
      IPGB      = NPGB
      NPGB      = NPGB + 100
      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 41
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 47

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vab0     = STOF(ISTOF + 3)
      Vbc0     = STOF(ISTOF + 4)
      RT_1     = STOF(ISTOF + 5)
      RT_2     = STOF(ISTOF + 6)
      RT_3     = STOF(ISTOF + 7)
      RT_4     = STOF(ISTOF + 8)
      RT_5     = STOF(ISTOF + 9)
      RT_6     = STOF(ISTOF + 10)
      RT_7     = STOF(ISTOF + 11)
      Duty_M1A = STOF(ISTOF + 24)
      Duty_M1B = STOF(ISTOF + 25)
      Duty_M1C = STOF(ISTOF + 26)
      Ibat1    = STOF(ISTOF + 27)
      BatVolt  = STOF(ISTOF + 28)
      Vca0     = STOF(ISTOF + 29)
      NotchEn  = STOF(ISTOF + 57)
      DCC_EN1  = STOF(ISTOF + 58)
      ACSSC_DRV1 = STOF(ISTOF + 59)
      RT_16    = STOF(ISTOF + 66)
      RT_17    = STOF(ISTOF + 67)
      RT_18    = STOF(ISTOF + 68)
      RT_19    = STOF(ISTOF + 69)
      MCB_DRV1 = STOI(ISTOI + 1)
      RT_20    = STOF(ISTOF + 70)
      RT_21    = STOF(ISTOF + 71)
      Bat_SOC  = STOF(ISTOF + 72)
      Grd_Ia1  = STOF(ISTOF + 73)
      Grd_Ib1  = STOF(ISTOF + 74)
      TP_ia    = STOF(ISTOF + 80)
      TP_ib    = STOF(ISTOF + 81)
      TP_ic    = STOF(ISTOF + 82)
      Triasign = STOF(ISTOF + 83)
      PWM_EN1x = STOF(ISTOF + 84)
      MCB_DRV  = STOI(ISTOI + 2)
      Qref     = STOF(ISTOF + 85)
      RT_24    = STOF(ISTOF + 86)
      RT_25    = STOF(ISTOF + 87)
      RT_26    = STOF(ISTOF + 88)
      RT_27    = STOF(ISTOF + 89)
      RT_28    = STOF(ISTOF + 90)
      RT_29    = STOF(ISTOF + 91)
      VSGEn    = STOI(ISTOI + 3)
      VgridHpfFreq = STOI(ISTOI + 4)
      GainK    = STOI(ISTOI + 5)
      DroopCoft = STOI(ISTOI + 6)
      DampCoft = STOI(ISTOI + 7)
      JCoft    = STOI(ISTOI + 8)
      SclToBess = STOI(ISTOI + 9)
      Tsample  = STOF(ISTOF + 92)
      MCB_DRVx = STOF(ISTOF + 157)
      CommandWord = STOI(ISTOI + 10)
      SetupWord = STOI(ISTOI + 11)
      UFP5     = STOI(ISTOI + 12)
      UFP4     = STOI(ISTOI + 13)
      UFP3     = STOI(ISTOI + 14)
      UFP2     = STOI(ISTOI + 15)
      OFP3     = STOI(ISTOI + 16)
      OFP2     = STOI(ISTOI + 17)
      OFP1     = STOI(ISTOI + 18)
      UFP1     = STOI(ISTOI + 19)
      UFP5Timems = STOI(ISTOI + 20)
      UFP4Timems = STOI(ISTOI + 21)
      UFP3Timems = STOI(ISTOI + 22)
      OFP3Timems = STOI(ISTOI + 23)
      OFP2Timems = STOI(ISTOI + 24)
      OFP1Timems = STOI(ISTOI + 25)
      UFP2Timems = STOI(ISTOI + 26)
      UFP1Timems = STOI(ISTOI + 27)
      UVP4Timems = STOI(ISTOI + 28)
      UVP3Timems = STOI(ISTOI + 29)
      UVP4     = STOI(ISTOI + 30)
      UVP3     = STOI(ISTOI + 31)
      OVP4     = STOI(ISTOI + 32)
      OVP3     = STOI(ISTOI + 33)
      OVP2     = STOI(ISTOI + 34)
      OVP1     = STOI(ISTOI + 35)
      UVP2     = STOI(ISTOI + 36)
      UVP1     = STOI(ISTOI + 37)
      UVP1Timems = STOI(ISTOI + 38)
      UVP2Timems = STOI(ISTOI + 39)
      OVP4Timems = STOI(ISTOI + 40)
      OVP3Timems = STOI(ISTOI + 41)
      OVP2Timems = STOI(ISTOI + 42)
      OVP1Timems = STOI(ISTOI + 43)
      RPWM_EN  = STOI(ISTOI + 44)
      Rocp     = STOF(ISTOF + 208)
      Rabs     = STOF(ISTOF + 209)
      RT_30    = STOF(ISTOF + 210)
      Grd_Iac1 = STOF(ISTOF + 211)
      RT_31    = STOF(ISTOF + 212)
      Sabs     = STOF(ISTOF + 213)
      RT_32    = STOF(ISTOF + 214)
      Grd_Ibc1 = STOF(ISTOF + 215)
      RT_33    = STOF(ISTOF + 216)
      Tabs     = STOF(ISTOF + 217)
      RT_34    = STOF(ISTOF + 218)
      Grd_Icc1 = STOF(ISTOF + 219)
      RT_35    = STOF(ISTOF + 220)
      OCP_EN   = STOF(ISTOF + 221)
      PWM_EN1  = STOI(ISTOI + 45)
      PWM_EN2  = STOF(ISTOF + 222)
      PWM_EN3  = STOF(ISTOF + 223)
      PWM_EN4  = STOF(ISTOF + 224)
      SPWM_EN  = STOI(ISTOI + 46)
      Socp     = STOF(ISTOF + 229)
      TPWM_EN  = STOI(ISTOI + 47)
      OCP_ENx  = STOI(ISTOI + 48)
      Tocp     = STOF(ISTOF + 230)
      Grd_Vdc1 = STOF(ISTOF + 231)
      Grd_Vdc2 = STOF(ISTOF + 232)
      spov_trip = STOI(ISTOI + 49)
      spov_gblock = STOI(ISTOI + 50)
      oc_block = STOI(ISTOI + 51)
      Qmeas    = STOF(ISTOF + 241)
      AMC_DRV1 = STOF(ISTOF + 242)
      AMC_DRV2 = STOF(ISTOF + 243)
      AMC_DRV3 = STOF(ISTOF + 244)
      AMC_DRV4 = STOF(ISTOF + 245)
      DCC_EN2  = STOF(ISTOF + 246)
      DCC_EN3  = STOF(ISTOF + 247)
      DCC_EN4  = STOF(ISTOF + 248)
      DCC_SS_EN1 = STOF(ISTOF + 249)
      DCC_SS_EN2 = STOF(ISTOF + 250)
      DCC_SS_EN3 = STOF(ISTOF + 251)
      ACSSC_DRV3 = STOF(ISTOF + 252)
      ACSSC_DRV4 = STOF(ISTOF + 253)
      FreqSet  = STOF(ISTOF + 258)
      VoltSet  = STOF(ISTOF + 259)
      Pref     = STOF(ISTOF + 260)
      Qref1    = STOF(ISTOF + 261)
      Bat_SOC2 = STOF(ISTOF + 265)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_22(IT_0) = STOF(ISTOF + 74 + IT_0)
         PQRefSet(IT_0) = STOF(ISTOF + 160 + IT_0)
         CapCur(IT_0) = STOF(ISTOF + 162 + IT_0)
         BusVolt(IT_0) = STOF(ISTOF + 167 + IT_0)
         GridVolt(IT_0) = STOF(ISTOF + 169 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 232 + IT_0)
         PQ_pos(IT_0) = STOF(ISTOF + 253 + IT_0)
         IPQ_pos(IT_0) = STOF(ISTOF + 255 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_8(IT_0) = STOF(ISTOF + 29 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 59 + IT_0)
         Ug_rms_LV(IT_0) = STOF(ISTOF + 62 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 76 + IT_0)
         Duty_M4(IT_0) = STOF(ISTOF + 128 + IT_0)
         Duty_M3(IT_0) = STOF(ISTOF + 131 + IT_0)
         Duty_M2(IT_0) = STOF(ISTOF + 134 + IT_0)
         Duty_M1(IT_0) = STOF(ISTOF + 137 + IT_0)
         BattMeas(IT_0) = STOF(ISTOF + 157 + IT_0)
         ModuleCur(IT_0) = STOF(ISTOF + 164 + IT_0)
         TP_iS(IT_0) = STOF(ISTOF + 234 + IT_0)
         Vabc1(IT_0) = STOF(ISTOF + 237 + IT_0)
         TP_iG(IT_0) = STOF(ISTOF + 261 + IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         RT_9(IT_0) = STOF(ISTOF + 32 + IT_0)
         RT_10(IT_0) = STOF(ISTOF + 36 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 40 + IT_0)
         RT_12(IT_0) = STOF(ISTOF + 44 + IT_0)
         RT_13(IT_0) = STOF(ISTOF + 48 + IT_0)
         RT_14(IT_0) = STOF(ISTOF + 52 + IT_0)
         PWM_EN(IT_0) = STOF(ISTOF + 124 + IT_0)
         DCSSC_DRV(IT_0) = STOF(ISTOF + 140 + IT_0)
         DCC_DRV(IT_0) = STOF(ISTOF + 144 + IT_0)
         ACSSC_DRV(IT_0) = STOF(ISTOF + 148 + IT_0)
         ACM_DRV(IT_0) = STOF(ISTOF + 152 + IT_0)
         PWM1_EN(IT_0) = STOF(ISTOF + 203 + IT_0)
         PWM1_EN_OLD(IT_0) = STOF(ISTOF + 224 + IT_0)
      END DO

! Array (1:8) quantities...
      DO IT_0 = 1,8
         FrequenceTripTh(IT_0) = STOF(ISTOF + 171 + IT_0)
         FrequenceTripTime(IT_0) = STOF(ISTOF + 179 + IT_0)
         VoltageTripTh(IT_0) = STOF(ISTOF + 187 + IT_0)
         VoltageTripTime(IT_0) = STOF(ISTOF + 195 + IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         PWMDRV1(IT_0) = STOF(ISTOF + 11 + IT_0)
      END DO

! Array (1:16) quantities...
      DO IT_0 = 1,16
         DebugData2(IT_0) = STOF(ISTOF + 92 + IT_0)
         DebugData1(IT_0) = STOF(ISTOF + 108 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakDyn()


! 20:[tbreakn] Timed Breaker Logic 
! Timed breaker logic
      IF ( TIMEZERO ) THEN
         MCB_DRV1 = 1
      ELSE
         MCB_DRV1 = 1
         IF ( TIME .GE. 0.002 ) MCB_DRV1 = (1-1)
      ENDIF

! 100:[breaker3] 3 Phase Breaker 'MCB_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+1),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+2),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+3),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-REAL(MCB_DRV1)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+1),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+2),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+3),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,900004966,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,900004966,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,900004966,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+1),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+2),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+3),SS(1)))

! 160:[battery] Generic battery model 'Bat2'
      IVD1_1=NSTORF
      CALL COMPONENT_ID(ICALL_NO,763973743)
      CALL BATTERYCOEFF1_EXE(SS(1), (IBRCH(1)+11))
      Bat_SOC2 = STORF(IVD1_1+2)*100.0

! 200:[consti] Integer Constant 
      OFP3 = 6300

! 210:[battery] Generic battery model 'Bat1'
      IVD1_1=NSTORF
      CALL COMPONENT_ID(ICALL_NO,1412014676)
      CALL BATTERYCOEFF1_EXE(SS(1), (IBRCH(1)+31))
      Bat_SOC = STORF(IVD1_1+2)*100.0

! 220:[consti] Integer Constant 
      OFP2 = 6160

! 240:[consti] Integer Constant 
      OFP1 = 6060

! 250:[consti] Integer Constant 
      UFP1 = 5940

! 260:[consti] Integer Constant 
      UFP2 = 5840

! 290:[consti] Integer Constant 
      UFP3 = 5780

! 300:[consti] Integer Constant 
      UFP4 = 5730

! 310:[consti] Integer Constant 
      UFP5 = 5700

! 320:[consti] Integer Constant 
      OFP3Timems = 30000

! 330:[consti] Integer Constant 
      OFP2Timems = 300000

! 340:[consti] Integer Constant 
      OFP1Timems = 300000

! 350:[consti] Integer Constant 
      UFP1Timems = 300000

! 370:[consti] Integer Constant 
      UFP2Timems = 300000

! 390:[consti] Integer Constant 
      UFP3Timems = 300000

! 400:[consti] Integer Constant 
      UFP4Timems = 300000

! 420:[consti] Integer Constant 
      UFP5Timems = 30000

! 430:[datamerge] Merges data signals into an array 
      BattMeas(1) = Bat_SOC
      BattMeas(2) = Ibat1
      BattMeas(3) = BatVolt

! 440:[consti] Integer Constant 
      OVP4 = 1300

! 460:[var] Variable Input Slider 'ActivePowerSet'
      RT_20 = CX(CXMAP(ICX+1))

! 470:[consti] Integer Constant 
      OVP3 = 1175

! 480:[consti] Integer Constant 
      OVP2 = 1150

! 490:[consti] Integer Constant 
      OVP1 = 1100

! 500:[var] Variable Input Slider 'ReactivePowerSet'
      RT_21 = CX(CXMAP(ICX+2))

! 510:[consti] Integer Constant 
      UVP1 = 900

! 520:[consti] Integer Constant 
      UVP2 = 750

! 540:[consti] Integer Constant 
      UVP3 = 650

! 550:[consti] Integer Constant 
      UVP4 = 450

! 560:[datatap] Scalar/Array Tap 
      Pref = PQref(1)

! 570:[consti] Integer Constant 
      OVP4Timems = 30000

! 580:[consti] Integer Constant 
      VSGEn = 0

! 590:[consti] Integer Constant 
      JCoft = 683999206

! 600:[consti] Integer Constant 
      OVP3Timems = 30000

! 610:[datatap] Scalar/Array Tap 
      Qref1 = PQref(2)

! 620:[consti] Integer Constant 
      DampCoft = 20000

! 630:[consti] Integer Constant 
      DroopCoft = 28

! 640:[consti] Integer Constant 
      OVP2Timems = 30000

! 650:[consti] Integer Constant 
      GainK = 49

! 660:[consti] Integer Constant 
      CommandWord = 8709

! 670:[consti] Integer Constant 
      OVP1Timems = 30000

! 680:[consti] Integer Constant 
      SetupWord = 34757

! 690:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 700:[consti] Integer Constant 
      UVP1Timems = 30000

! 710:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 720:[consti] Integer Constant 
      SclToBess = 6188

! 730:[consti] Integer Constant 
      UVP2Timems = 30000

! 740:[pgb] Output Channel 'SOC'

      PGB(IPGB+1) = Bat_SOC

! 750:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,540280048)
      CALL E_XSGEN1_EXE(1,16000.0,RVD2_1)
      Triasign = RVD2_1(1)

! 760:[consti] Integer Constant 
      UVP3Timems = 30000

! 770:[consti] Integer Constant 
      UVP4Timems = 30000

! 780:[FFT_Mod]  
      CALL FFT_ModDyn(Vab0, Vbc0, TP_ia, TP_ib, TP_ic, RT_1, RT_2, RT_3,&
     & RT_4, RT_5, RT_6, RT_7)


! 790:[datamerge] Merges data signals into an array 
      Ug_rms_LV(1) = RT_1
      Ug_rms_LV(2) = RT_2
      Ug_rms_LV(3) = RT_3

! 800:[datamerge] Merges data signals into an array 
      PQ_pos(1) = RT_4
      PQ_pos(2) = RT_5

! 810:[datamerge] Merges data signals into an array 
      IPQ_pos(1) = RT_6
      IPQ_pos(2) = RT_7

! 820:[const] Real Constant 
      RT_25 = 0.0

! 830:[pgb] Output Channel 'Vlrms'

      DO IVD1_1 = 1, 3
         PGB(IPGB+2+IVD1_1-1) = Ug_rms_LV(IVD1_1)
      ENDDO

! 840:[const] Real Constant 
      RT_26 = 0.0

! 850:[datatap] Scalar/Array Tap 
      RT_16 = PQ_pos(1)

! 860:[pgb] Output Channel 'P'

      PGB(IPGB+5) = RT_16

! 870:[time-sig] Output of Simulation Time 
      RT_28 = TIME

! 880:[datatap] Scalar/Array Tap 
      RT_18 = PQ_pos(2)

! 890:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,1.5,RT_28,0.0,0.0,1.0,RVD2_1)
      RT_24 = RVD2_1(1)

! 900:[pgb] Output Channel 'Q'

      PGB(IPGB+6) = RT_18

! 910:[datatap] Scalar/Array Tap 
      RT_17 = IPQ_pos(1)

! 920:[pgb] Output Channel 'I_active'

      PGB(IPGB+7) = RT_17

! 930:[const] Real Constant 
      RT_31 = 1000.0

! 940:[const] Real Constant 
      RT_33 = 1000.0

! 950:[datatap] Scalar/Array Tap 
      RT_19 = IPQ_pos(2)

! 960:[pgb] Output Channel 'I_reactive'

      PGB(IPGB+8) = RT_19

! 970:[const] Real Constant 
      RT_35 = 1000.0

! 1010:[datamerge] Merges data signals into an array 
      FrequenceTripTh(1) = REAL(OFP3)
      FrequenceTripTh(2) = REAL(OFP2)
      FrequenceTripTh(3) = REAL(OFP1)
      FrequenceTripTh(4) = REAL(UFP1)
      FrequenceTripTh(5) = REAL(UFP2)
      FrequenceTripTh(6) = REAL(UFP3)
      FrequenceTripTh(7) = REAL(UFP4)
      FrequenceTripTh(8) = REAL(UFP5)

! 1020:[datamerge] Merges data signals into an array 
      FrequenceTripTime(1) = REAL(OFP3Timems)
      FrequenceTripTime(2) = REAL(OFP2Timems)
      FrequenceTripTime(3) = REAL(OFP1Timems)
      FrequenceTripTime(4) = REAL(UFP1Timems)
      FrequenceTripTime(5) = REAL(UFP2Timems)
      FrequenceTripTime(6) = REAL(UFP3Timems)
      FrequenceTripTime(7) = REAL(UFP4Timems)
      FrequenceTripTime(8) = REAL(UFP5Timems)

! 1030:[datamerge] Merges data signals into an array 
      VoltageTripTh(1) = REAL(OVP4)
      VoltageTripTh(2) = REAL(OVP3)
      VoltageTripTh(3) = REAL(OVP2)
      VoltageTripTh(4) = REAL(OVP1)
      VoltageTripTh(5) = REAL(UVP1)
      VoltageTripTh(6) = REAL(UVP2)
      VoltageTripTh(7) = REAL(UVP3)
      VoltageTripTh(8) = REAL(UVP4)

! 1040:[datamerge] Merges data signals into an array 
      VoltageTripTime(1) = REAL(OVP4Timems)
      VoltageTripTime(2) = REAL(OVP3Timems)
      VoltageTripTime(3) = REAL(OVP2Timems)
      VoltageTripTime(4) = REAL(OVP1Timems)
      VoltageTripTime(5) = REAL(UVP1Timems)
      VoltageTripTime(6) = REAL(UVP2Timems)
      VoltageTripTime(7) = REAL(UVP3Timems)
      VoltageTripTime(8) = REAL(UVP4Timems)

! 1050:[select] Two Input Selector 
      IF (NINT(RT_24) .EQ. RTCI(NRTCI)) THEN
         RT_27 = RT_25
      ELSE
         RT_27 = RT_26
      ENDIF
      NRTCI = NRTCI + 1
!

! 1060:[oc_spov]  
!
      CALL COMPONENT_ID(ICALL_NO,653297001)
      CALL oc_spovDyn(spov_trip, spov_gblock, oc_block, TP_iS, Vabc1, 0.&
     &69, 10.0, 10.0, 10.0, 0.5)
!

! 1070:[mult] Multiplier 
      RT_30 = Grd_Iac1 * RT_31

! 1080:[mult] Multiplier 
      RT_32 = Grd_Ibc1 * RT_33

! 1090:[abs] Absolute Value 
      Rabs = ABS(RT_30)

! 1100:[abs] Absolute Value 
      Sabs = ABS(RT_32)

! 1110:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,Rabs,0.0,0.0,1.0,RVD2_1)
      Rocp = RVD2_1(1)

! 1120:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,Sabs,0.0,0.0,1.0,RVD2_1)
      Socp = RVD2_1(1)

! 1130:[mult] Multiplier 
      RT_34 = Grd_Icc1 * RT_35

! 1140:[abs] Absolute Value 
      Tabs = ABS(RT_34)

! 1150:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,400.0,Tabs,0.0,0.0,1.0,RVD2_1)
      Tocp = RVD2_1(1)

! 1160:[breaker3] 3 Phase Breaker 'MCB_DRV'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+18),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+19),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+20),0.005,1000000.0,RTCF(NRTC&
     &F),1,NINT(1.0-REAL(MCB_DRV)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+18),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+19),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+20),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,36475754,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,36475754,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,36475754,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+18),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+19),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+20),SS(1)))

! 1170:[special_funcs]  
!
      CALL COMPONENT_ID(ICALL_NO,328370194)
      CALL special_funcsDyn(Qref, Qmeas, Qref1, Vabc1, 60.0, 0, 1.0, 0, &
     &1.0, 0.01, 0.01)
!

! 1180:[datamerge] Merges data signals into an array 
      PQRefSet(1) = Pref
      PQRefSet(2) = Qref

! 1190:[Ctrl]  
! PCS2 Interface for PSCAD&IVF&VS

 !     CALL AUX_PCS2CTRL(GridVolt,BusVolt,REAL(SetupWord),ModuleCur,CapCur,PQRefSet,BattMeas,REAL(CommandWord),MCB_DRVx,ACM_DRV,ACSSC_DRV,DCC_DRV,DCSSC_DRV,Duty_M1,Duty_M2,Duty_M3,Duty_M4,PWM_EN,DebugData1,DebugData2)
       CALL AUX_PCS2CTRL(GridVolt,BusVolt,REAL(SetupWord),ModuleCur,CapC&
     &ur,PQRefSet,BattMeas,REAL(CommandWord),Tsample,REAL(SclToBess),REA&
     &L(JCoft),REAL(DampCoft),REAL(DroopCoft),REAL(GainK),REAL(VgridHpfF&
     &req),REAL(VSGEn),FrequenceTripTh,FrequenceTripTime,VoltageTripTh,V&
     &oltageTripTime,MCB_DRVx,ACM_DRV,ACSSC_DRV,DCC_DRV,DCSSC_DRV,Duty_M&
     &1,Duty_M2,Duty_M3,Duty_M4,PWM_EN,DebugData1,DebugData2)

! 1200:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (NINT(MCB_DRVx) .NE. 0) .OR. (spov_trip .NE. 0) ) THEN
        MCB_DRV = 1
      ELSE
        MCB_DRV = 0
      ENDIF

! 1210:[datatap] Scalar/Array Tap 
      OCP_EN = DCSSC_DRV(4)

! 1220:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (NINT(OCP_EN) .NE. 0) .AND. (NINT(OCP_EN) .NE. 0) ) THEN
        OCP_ENx = 0
      ELSE
        OCP_ENx = 1
      ENDIF

! 1230:[datatap] Scalar/Array Tap 
      PWM_EN1x = PWM_EN(1)

! 1240:[datatap] Scalar/Array Tap 
      Duty_M1B = Duty_M1(2)

! 1250:[datatap] Scalar/Array Tap 
      Duty_M1A = Duty_M1(1)

! 1260:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Tocp) .NE. 0) ) THEN
        TPWM_EN = 1
      ELSE
        TPWM_EN = 0
      ENDIF

! 1270:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Socp) .NE. 0) ) THEN
        SPWM_EN = 1
      ELSE
        SPWM_EN = 0
      ENDIF

! 1280:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (OCP_ENx .NE. 0) .AND. (NINT(Rocp) .NE. 0) ) THEN
        RPWM_EN = 1
      ELSE
        RPWM_EN = 0
      ENDIF

! 1290:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (NINT(PWM_EN1x) .NE. 0) .OR. (NINT(PWM_EN1x) .NE. 0) ) THEN
        PWM_EN1 = 1
      ELSE
        PWM_EN1 = 0
      ENDIF

! 1300:[datatap] Scalar/Array Tap 
      PWM_EN2 = PWM_EN(2)

! 1310:[datamerge] Merges data signals into an array 
      PWM1_EN(1) = REAL(PWM_EN1)
      PWM1_EN(2) = REAL(RPWM_EN)
      PWM1_EN(3) = REAL(SPWM_EN)
      PWM1_EN(4) = REAL(TPWM_EN)

! 1320:[datatap] Scalar/Array Tap 
      RT_14 = DebugData2(5 : 8)

! 1330:[datatap] Scalar/Array Tap 
      RT_10 = DebugData1(5 : 8)

! 1340:[datatap] Scalar/Array Tap 
      RT_13 = DebugData2(1 : 4)

! 1350:[datatap] Scalar/Array Tap 
      RT_9 = DebugData1(1 : 4)

! 1360:[realpole] Real Pole 
!  Real_Pole
      RT_29 = REALPOLE(0,1,0,1.0,0.1,RT_27,0.0,-1.0E20,1.0E20)

! 1370:[pgb] Output Channel 'Qref'

      PGB(IPGB+9) = Qref

! 1380:[datatap] Scalar/Array Tap 
      Duty_M1C = Duty_M1(3)

! 1390:[PWM_3Level]  
      CALL PWM_3LevelDyn(Duty_M1A, Duty_M1B, Duty_M1C, PWMDRV1, Triasign&
     &, PWM1_EN)


! 1400:[pgb] Output Channel 'PWM_Mod'

      DO IVD1_1 = 1, 3
         PGB(IPGB+10+IVD1_1-1) = Duty_M1(IVD1_1)
      ENDDO

! 1410:[pgb] Output Channel 'Triasign_PWM'

      PGB(IPGB+13) = Triasign

! 1420:[datatap] Scalar/Array Tap 
      PWM_EN4 = PWM_EN(4)

! 1430:[datatap] Scalar/Array Tap 
      PWM_EN3 = PWM_EN(3)

! 1440:[datamerge] Merges data signals into an array 
      PWM1_EN_OLD(1) = REAL(PWM_EN1)
      PWM1_EN_OLD(2) = PWM_EN2
      PWM1_EN_OLD(3) = PWM_EN3
      PWM1_EN_OLD(4) = PWM_EN4

! 1450:[datatap] Scalar/Array Tap 
      DCC_SS_EN3 = DCSSC_DRV(3)

! 1460:[pgb] Output Channel 'DebugData2'

      DO IVD1_1 = 1, 16
         PGB(IPGB+14+IVD1_1-1) = DebugData2(IVD1_1)
      ENDDO

! 1470:[pgb] Output Channel 'DebugData1'

      DO IVD1_1 = 1, 16
         PGB(IPGB+30+IVD1_1-1) = DebugData1(IVD1_1)
      ENDDO

! 1480:[datatap] Scalar/Array Tap 
      DCC_SS_EN2 = DCSSC_DRV(2)

! 1490:[datatap] Scalar/Array Tap 
      DCC_SS_EN1 = DCSSC_DRV(1)

! 1500:[datatap] Scalar/Array Tap 
      FreqSet = DebugData2(10)

! 1510:[datatap] Scalar/Array Tap 
      RT_12 = DebugData1(13 : 16)

! 1520:[pgb] Output Channel 'T4'

      DO IVD1_1 = 1, 4
         PGB(IPGB+46+IVD1_1-1) = RT_12(IVD1_1)
      ENDDO

! 1530:[datatap] Scalar/Array Tap 
      DCC_EN4 = DCC_DRV(4)

! 1540:[datatap] Scalar/Array Tap 
      VoltSet = DebugData2(9)

! 1550:[datatap] Scalar/Array Tap 
      DCC_EN3 = DCC_DRV(3)

! 1560:[datatap] Scalar/Array Tap 
      RT_11 = DebugData1(9 : 12)

! 1570:[pgb] Output Channel 'T3'

      DO IVD1_1 = 1, 4
         PGB(IPGB+50+IVD1_1-1) = RT_11(IVD1_1)
      ENDDO

! 1580:[datatap] Scalar/Array Tap 
      DCC_EN2 = DCC_DRV(2)

! 1590:[pgb] Output Channel 'PCS Fault'

      DO IVD1_1 = 1, 4
         PGB(IPGB+54+IVD1_1-1) = RT_14(IVD1_1)
      ENDDO

! 1600:[datatap] Scalar/Array Tap 
      DCC_EN1 = DCC_DRV(1)

! 1610:[pgb] Output Channel 'T2'

      DO IVD1_1 = 1, 4
         PGB(IPGB+58+IVD1_1-1) = RT_10(IVD1_1)
      ENDDO

! 1620:[pgb] Output Channel 'T7'

      DO IVD1_1 = 1, 4
         PGB(IPGB+62+IVD1_1-1) = RT_13(IVD1_1)
      ENDDO

! 1630:[datatap] Scalar/Array Tap 
      ACSSC_DRV4 = ACSSC_DRV(4)

! 1640:[pgb] Output Channel 'T1'

      DO IVD1_1 = 1, 4
         PGB(IPGB+66+IVD1_1-1) = RT_9(IVD1_1)
      ENDDO

! 1650:[datatap] Scalar/Array Tap 
      ACSSC_DRV3 = ACSSC_DRV(3)

! 1660:[datatap] Scalar/Array Tap 
      NotchEn = ACSSC_DRV(2)

! 1670:[datatap] Scalar/Array Tap 
      ACSSC_DRV1 = ACSSC_DRV(1)

! 1680:[datatap] Scalar/Array Tap 
      AMC_DRV4 = ACM_DRV(4)

! 1690:[datatap] Scalar/Array Tap 
      AMC_DRV3 = ACM_DRV(3)

! 1700:[pgb] Output Channel 'iRabs'

      PGB(IPGB+70) = Rocp

! 1710:[datatap] Scalar/Array Tap 
      AMC_DRV2 = ACM_DRV(2)

! 1720:[datatap] Scalar/Array Tap 
      AMC_DRV1 = ACM_DRV(1)

! 1730:[pgb] Output Channel 'OcpEn'

      PGB(IPGB+71) = REAL(OCP_ENx)

! 1740:[pgb] Output Channel 'PWM1'

      PGB(IPGB+72) = PWM_EN1x

! 1750:[pgb] Output Channel 'PWM'

      DO IVD1_1 = 1, 4
         PGB(IPGB+73+IVD1_1-1) = PWM1_EN(IVD1_1)
      ENDDO

! 1760:[pgb] Output Channel 'MCB'

      PGB(IPGB+77) = REAL(MCB_DRV)

! 1770:[pgb] Output Channel 'MC'

      DO IVD1_1 = 1, 4
         PGB(IPGB+78+IVD1_1-1) = ACM_DRV(IVD1_1)
      ENDDO

! 1780:[pgb] Output Channel 'DC_EN'

      PGB(IPGB+82) = DCC_EN1

! 1790:[pgb] Output Channel 'DC_SS_EN'

      PGB(IPGB+83) = NotchEn

! 1800:[pgb] Output Channel 'AC_SS_EN'

      PGB(IPGB+84) = ACSSC_DRV1

! 1850:[ThreePhase_3Level]  
      CALL ThreePhase_3LevelDyn(PWMDRV1)


! 1870:[breaker3] 3 Phase Breaker 'AMC_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+4),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-AMC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+5),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-AMC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+6),0.005,1000000.0,RTCF(NRTCF&
     &),1,NINT(1.0-AMC_DRV1))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+4),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+5),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+6),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1569782592,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1569782592,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,1569782592,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+4),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+5),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+6),SS(1)))

! 1880:[breaker1] Single Phase Breaker 'DCC_EN1'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+25),0.005,1000000.0,1,NINT(1.0-&
     &DCC_EN1))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+25),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,243978139,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+25),SS(1)))

! 1920:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
      IVD1_2 = NSTORI
      NSTORI = NSTORI + 1
      CALL E1PBRKR1_EXE(SS(1), (IBRCH(1)+26),0.005,1000000.0,1,NINT(1.0-&
     &DCC_SS_EN1))
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+26),SS(1)))
      IF (FIRSTSTEP .OR. (STORI(IVD1_2) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,196338356,IVD1_1,"BOpen")
      ENDIF
      STORI(IVD1_2) = 2*E_BtoI(OPENBR( (IBRCH(1)+26),SS(1)))

! 1930:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+8),0.001,100000000.0,RTCF(NRT&
     &CF),1,NINT(1.0-ACSSC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+9),0.001,100000000.0,RTCF(NRT&
     &CF),1,NINT(1.0-ACSSC_DRV1))
      CALL EMTDC_BREAKER1(SS(1), (IBRCH(1)+10),0.001,100000000.0,RTCF(NR&
     &TCF),1,NINT(1.0-ACSSC_DRV1))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH(1)+8),SS(1)))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH(1)+9),SS(1)))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,410852369,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,410852369,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,410852369,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH(1)+8),SS(1)))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH(1)+9),SS(1)))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH(1)+10),SS(1)))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 3) = Vab0
      STOF(ISTOF + 4) = Vbc0
      STOF(ISTOF + 5) = RT_1
      STOF(ISTOF + 6) = RT_2
      STOF(ISTOF + 7) = RT_3
      STOF(ISTOF + 8) = RT_4
      STOF(ISTOF + 9) = RT_5
      STOF(ISTOF + 10) = RT_6
      STOF(ISTOF + 11) = RT_7
      STOF(ISTOF + 24) = Duty_M1A
      STOF(ISTOF + 25) = Duty_M1B
      STOF(ISTOF + 26) = Duty_M1C
      STOF(ISTOF + 27) = Ibat1
      STOF(ISTOF + 28) = BatVolt
      STOF(ISTOF + 29) = Vca0
      STOF(ISTOF + 57) = NotchEn
      STOF(ISTOF + 58) = DCC_EN1
      STOF(ISTOF + 59) = ACSSC_DRV1
      STOF(ISTOF + 66) = RT_16
      STOF(ISTOF + 67) = RT_17
      STOF(ISTOF + 68) = RT_18
      STOF(ISTOF + 69) = RT_19
      STOI(ISTOI + 1) = MCB_DRV1
      STOF(ISTOF + 70) = RT_20
      STOF(ISTOF + 71) = RT_21
      STOF(ISTOF + 72) = Bat_SOC
      STOF(ISTOF + 73) = Grd_Ia1
      STOF(ISTOF + 74) = Grd_Ib1
      STOF(ISTOF + 80) = TP_ia
      STOF(ISTOF + 81) = TP_ib
      STOF(ISTOF + 82) = TP_ic
      STOF(ISTOF + 83) = Triasign
      STOF(ISTOF + 84) = PWM_EN1x
      STOI(ISTOI + 2) = MCB_DRV
      STOF(ISTOF + 85) = Qref
      STOF(ISTOF + 86) = RT_24
      STOF(ISTOF + 87) = RT_25
      STOF(ISTOF + 88) = RT_26
      STOF(ISTOF + 89) = RT_27
      STOF(ISTOF + 90) = RT_28
      STOF(ISTOF + 91) = RT_29
      STOI(ISTOI + 3) = VSGEn
      STOI(ISTOI + 4) = VgridHpfFreq
      STOI(ISTOI + 5) = GainK
      STOI(ISTOI + 6) = DroopCoft
      STOI(ISTOI + 7) = DampCoft
      STOI(ISTOI + 8) = JCoft
      STOI(ISTOI + 9) = SclToBess
      STOF(ISTOF + 92) = Tsample
      STOF(ISTOF + 157) = MCB_DRVx
      STOI(ISTOI + 10) = CommandWord
      STOI(ISTOI + 11) = SetupWord
      STOI(ISTOI + 12) = UFP5
      STOI(ISTOI + 13) = UFP4
      STOI(ISTOI + 14) = UFP3
      STOI(ISTOI + 15) = UFP2
      STOI(ISTOI + 16) = OFP3
      STOI(ISTOI + 17) = OFP2
      STOI(ISTOI + 18) = OFP1
      STOI(ISTOI + 19) = UFP1
      STOI(ISTOI + 20) = UFP5Timems
      STOI(ISTOI + 21) = UFP4Timems
      STOI(ISTOI + 22) = UFP3Timems
      STOI(ISTOI + 23) = OFP3Timems
      STOI(ISTOI + 24) = OFP2Timems
      STOI(ISTOI + 25) = OFP1Timems
      STOI(ISTOI + 26) = UFP2Timems
      STOI(ISTOI + 27) = UFP1Timems
      STOI(ISTOI + 28) = UVP4Timems
      STOI(ISTOI + 29) = UVP3Timems
      STOI(ISTOI + 30) = UVP4
      STOI(ISTOI + 31) = UVP3
      STOI(ISTOI + 32) = OVP4
      STOI(ISTOI + 33) = OVP3
      STOI(ISTOI + 34) = OVP2
      STOI(ISTOI + 35) = OVP1
      STOI(ISTOI + 36) = UVP2
      STOI(ISTOI + 37) = UVP1
      STOI(ISTOI + 38) = UVP1Timems
      STOI(ISTOI + 39) = UVP2Timems
      STOI(ISTOI + 40) = OVP4Timems
      STOI(ISTOI + 41) = OVP3Timems
      STOI(ISTOI + 42) = OVP2Timems
      STOI(ISTOI + 43) = OVP1Timems
      STOI(ISTOI + 44) = RPWM_EN
      STOF(ISTOF + 208) = Rocp
      STOF(ISTOF + 209) = Rabs
      STOF(ISTOF + 210) = RT_30
      STOF(ISTOF + 211) = Grd_Iac1
      STOF(ISTOF + 212) = RT_31
      STOF(ISTOF + 213) = Sabs
      STOF(ISTOF + 214) = RT_32
      STOF(ISTOF + 215) = Grd_Ibc1
      STOF(ISTOF + 216) = RT_33
      STOF(ISTOF + 217) = Tabs
      STOF(ISTOF + 218) = RT_34
      STOF(ISTOF + 219) = Grd_Icc1
      STOF(ISTOF + 220) = RT_35
      STOF(ISTOF + 221) = OCP_EN
      STOI(ISTOI + 45) = PWM_EN1
      STOF(ISTOF + 222) = PWM_EN2
      STOF(ISTOF + 223) = PWM_EN3
      STOF(ISTOF + 224) = PWM_EN4
      STOI(ISTOI + 46) = SPWM_EN
      STOF(ISTOF + 229) = Socp
      STOI(ISTOI + 47) = TPWM_EN
      STOI(ISTOI + 48) = OCP_ENx
      STOF(ISTOF + 230) = Tocp
      STOF(ISTOF + 231) = Grd_Vdc1
      STOF(ISTOF + 232) = Grd_Vdc2
      STOI(ISTOI + 49) = spov_trip
      STOI(ISTOI + 50) = spov_gblock
      STOI(ISTOI + 51) = oc_block
      STOF(ISTOF + 241) = Qmeas
      STOF(ISTOF + 242) = AMC_DRV1
      STOF(ISTOF + 243) = AMC_DRV2
      STOF(ISTOF + 244) = AMC_DRV3
      STOF(ISTOF + 245) = AMC_DRV4
      STOF(ISTOF + 246) = DCC_EN2
      STOF(ISTOF + 247) = DCC_EN3
      STOF(ISTOF + 248) = DCC_EN4
      STOF(ISTOF + 249) = DCC_SS_EN1
      STOF(ISTOF + 250) = DCC_SS_EN2
      STOF(ISTOF + 251) = DCC_SS_EN3
      STOF(ISTOF + 252) = ACSSC_DRV3
      STOF(ISTOF + 253) = ACSSC_DRV4
      STOF(ISTOF + 258) = FreqSet
      STOF(ISTOF + 259) = VoltSet
      STOF(ISTOF + 260) = Pref
      STOF(ISTOF + 261) = Qref1
      STOF(ISTOF + 265) = Bat_SOC2

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = PQref(IT_0)
         STOF(ISTOF + 74 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 160 + IT_0) = PQRefSet(IT_0)
         STOF(ISTOF + 162 + IT_0) = CapCur(IT_0)
         STOF(ISTOF + 167 + IT_0) = BusVolt(IT_0)
         STOF(ISTOF + 169 + IT_0) = GridVolt(IT_0)
         STOF(ISTOF + 232 + IT_0) = RT_36(IT_0)
         STOF(ISTOF + 253 + IT_0) = PQ_pos(IT_0)
         STOF(ISTOF + 255 + IT_0) = IPQ_pos(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 29 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 59 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 62 + IT_0) = Ug_rms_LV(IT_0)
         STOF(ISTOF + 76 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 128 + IT_0) = Duty_M4(IT_0)
         STOF(ISTOF + 131 + IT_0) = Duty_M3(IT_0)
         STOF(ISTOF + 134 + IT_0) = Duty_M2(IT_0)
         STOF(ISTOF + 137 + IT_0) = Duty_M1(IT_0)
         STOF(ISTOF + 157 + IT_0) = BattMeas(IT_0)
         STOF(ISTOF + 164 + IT_0) = ModuleCur(IT_0)
         STOF(ISTOF + 234 + IT_0) = TP_iS(IT_0)
         STOF(ISTOF + 237 + IT_0) = Vabc1(IT_0)
         STOF(ISTOF + 261 + IT_0) = TP_iG(IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         STOF(ISTOF + 32 + IT_0) = RT_9(IT_0)
         STOF(ISTOF + 36 + IT_0) = RT_10(IT_0)
         STOF(ISTOF + 40 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 44 + IT_0) = RT_12(IT_0)
         STOF(ISTOF + 48 + IT_0) = RT_13(IT_0)
         STOF(ISTOF + 52 + IT_0) = RT_14(IT_0)
         STOF(ISTOF + 124 + IT_0) = PWM_EN(IT_0)
         STOF(ISTOF + 140 + IT_0) = DCSSC_DRV(IT_0)
         STOF(ISTOF + 144 + IT_0) = DCC_DRV(IT_0)
         STOF(ISTOF + 148 + IT_0) = ACSSC_DRV(IT_0)
         STOF(ISTOF + 152 + IT_0) = ACM_DRV(IT_0)
         STOF(ISTOF + 203 + IT_0) = PWM1_EN(IT_0)
         STOF(ISTOF + 224 + IT_0) = PWM1_EN_OLD(IT_0)
      END DO

! Array (1:8) quantities...
      DO IT_0 = 1,8
         STOF(ISTOF + 171 + IT_0) = FrequenceTripTh(IT_0)
         STOF(ISTOF + 179 + IT_0) = FrequenceTripTime(IT_0)
         STOF(ISTOF + 187 + IT_0) = VoltageTripTh(IT_0)
         STOF(ISTOF + 195 + IT_0) = VoltageTripTime(IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         STOF(ISTOF + 11 + IT_0) = PWMDRV1(IT_0)
      END DO

! Array (1:16) quantities...
      DO IT_0 = 1,16
         STOF(ISTOF + 92 + IT_0) = DebugData2(IT_0)
         STOF(ISTOF + 108 + IT_0) = DebugData1(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakOut      ! 
      REAL    EMTDC_VVDC    ! 
      REAL    VBRANCH       ! 
!     SUBR    FFT_ModOut    ! 
!     SUBR    PWM_3LevelOut  ! 
!     SUBR    ThreePhase_3LevelOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_4, NT_5, NT_6, NT_16, NT_42
      INTEGER  NT_43, NT_44

! Control Signals
      INTEGER  VSGEn, VgridHpfFreq, GainK
      INTEGER  DroopCoft, DampCoft, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      REAL     Vab0, Vbc0, Ibat1, BatVolt, Vca0
      REAL     RT_8(3), RT_15(3), Grd_Ia1
      REAL     Grd_Ib1, RT_22(2), RT_23(3), TP_ia
      REAL     TP_ib, TP_ic, RT_25, RT_26
      REAL     Tsample, CapCur(2), ModuleCur(3)
      REAL     BusVolt(2), GridVolt(2), Grd_Iac1
      REAL     RT_31, Grd_Ibc1, RT_33, Grd_Icc1
      REAL     RT_35, Grd_Vdc1, Grd_Vdc2
      REAL     RT_36(2), TP_iS(3), Vabc1(3)
      REAL     Qmeas, TP_iG(3)

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 100
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 41
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 47

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vab0     = STOF(ISTOF + 3)
      Vbc0     = STOF(ISTOF + 4)
      Ibat1    = STOF(ISTOF + 27)
      BatVolt  = STOF(ISTOF + 28)
      Vca0     = STOF(ISTOF + 29)
      Grd_Ia1  = STOF(ISTOF + 73)
      Grd_Ib1  = STOF(ISTOF + 74)
      TP_ia    = STOF(ISTOF + 80)
      TP_ib    = STOF(ISTOF + 81)
      TP_ic    = STOF(ISTOF + 82)
      RT_25    = STOF(ISTOF + 87)
      RT_26    = STOF(ISTOF + 88)
      VSGEn    = STOI(ISTOI + 3)
      VgridHpfFreq = STOI(ISTOI + 4)
      GainK    = STOI(ISTOI + 5)
      DroopCoft = STOI(ISTOI + 6)
      DampCoft = STOI(ISTOI + 7)
      JCoft    = STOI(ISTOI + 8)
      SclToBess = STOI(ISTOI + 9)
      Tsample  = STOF(ISTOF + 92)
      CommandWord = STOI(ISTOI + 10)
      SetupWord = STOI(ISTOI + 11)
      UFP5     = STOI(ISTOI + 12)
      UFP4     = STOI(ISTOI + 13)
      UFP3     = STOI(ISTOI + 14)
      UFP2     = STOI(ISTOI + 15)
      OFP3     = STOI(ISTOI + 16)
      OFP2     = STOI(ISTOI + 17)
      OFP1     = STOI(ISTOI + 18)
      UFP1     = STOI(ISTOI + 19)
      UFP5Timems = STOI(ISTOI + 20)
      UFP4Timems = STOI(ISTOI + 21)
      UFP3Timems = STOI(ISTOI + 22)
      OFP3Timems = STOI(ISTOI + 23)
      OFP2Timems = STOI(ISTOI + 24)
      OFP1Timems = STOI(ISTOI + 25)
      UFP2Timems = STOI(ISTOI + 26)
      UFP1Timems = STOI(ISTOI + 27)
      UVP4Timems = STOI(ISTOI + 28)
      UVP3Timems = STOI(ISTOI + 29)
      UVP4     = STOI(ISTOI + 30)
      UVP3     = STOI(ISTOI + 31)
      OVP4     = STOI(ISTOI + 32)
      OVP3     = STOI(ISTOI + 33)
      OVP2     = STOI(ISTOI + 34)
      OVP1     = STOI(ISTOI + 35)
      UVP2     = STOI(ISTOI + 36)
      UVP1     = STOI(ISTOI + 37)
      UVP1Timems = STOI(ISTOI + 38)
      UVP2Timems = STOI(ISTOI + 39)
      OVP4Timems = STOI(ISTOI + 40)
      OVP3Timems = STOI(ISTOI + 41)
      OVP2Timems = STOI(ISTOI + 42)
      OVP1Timems = STOI(ISTOI + 43)
      Grd_Iac1 = STOF(ISTOF + 211)
      RT_31    = STOF(ISTOF + 212)
      Grd_Ibc1 = STOF(ISTOF + 215)
      RT_33    = STOF(ISTOF + 216)
      Grd_Icc1 = STOF(ISTOF + 219)
      RT_35    = STOF(ISTOF + 220)
      Grd_Vdc1 = STOF(ISTOF + 231)
      Grd_Vdc2 = STOF(ISTOF + 232)
      Qmeas    = STOF(ISTOF + 241)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_22(IT_0) = STOF(ISTOF + 74 + IT_0)
         CapCur(IT_0) = STOF(ISTOF + 162 + IT_0)
         BusVolt(IT_0) = STOF(ISTOF + 167 + IT_0)
         GridVolt(IT_0) = STOF(ISTOF + 169 + IT_0)
         RT_36(IT_0) = STOF(ISTOF + 232 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_8(IT_0) = STOF(ISTOF + 29 + IT_0)
         RT_15(IT_0) = STOF(ISTOF + 59 + IT_0)
         RT_23(IT_0) = STOF(ISTOF + 76 + IT_0)
         ModuleCur(IT_0) = STOF(ISTOF + 164 + IT_0)
         TP_iS(IT_0) = STOF(ISTOF + 234 + IT_0)
         Vabc1(IT_0) = STOF(ISTOF + 237 + IT_0)
         TP_iG(IT_0) = STOF(ISTOF + 261 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_4  = NODE(INODE + 10)
      NT_5  = NODE(INODE + 11)
      NT_6  = NODE(INODE + 12)
      NT_16 = NODE(INODE + 29)
      NT_42 = NODE(INODE + 17)
      NT_43 = NODE(INODE + 18)
      NT_44 = NODE(INODE + 19)

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakOut()


! 30:[ammeter] Current Meter 'TP_ia'
      TP_ia = ( CBR((IBRCH(1)+23), SS(1)))

! 40:[ammeter] Current Meter 'TP_iG'
      TP_iG(1) = ( CBR((IBRCH(1)+15), SS(1)))
      TP_iG(2) = ( CBR((IBRCH(1)+16), SS(1)))
      TP_iG(3) = ( CBR((IBRCH(1)+17), SS(1)))

! 50:[voltmeter] Voltmeter (Line - Line) 'Vab0'
      Vab0 = EMTDC_VVDC(SS(1), NT_42, NT_43)

! 60:[ammeter] Current Meter 'TP_iS'
      TP_iS(1) = ( CBR((IBRCH(1)+12), SS(1)))
      TP_iS(2) = ( CBR((IBRCH(1)+13), SS(1)))
      TP_iS(3) = ( CBR((IBRCH(1)+14), SS(1)))

! 70:[ammeter] Current Meter 'TP_ib'
      TP_ib = ( CBR((IBRCH(1)+22), SS(1)))

! 80:[ammeter] Current Meter 'Ibat1'
      Ibat1 = ( CBR((IBRCH(1)+7), SS(1)))

! 90:[voltmeter] Voltmeter (Line - Line) 'Vbc0'
      Vbc0 = EMTDC_VVDC(SS(1), NT_43, NT_44)

! 100:[breaker3] 3 Phase Breaker 'MCB_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+1), (IBRCH(1)+2), (IBRCH(1)+3),0,0&
     &,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 110:[ammeter] Current Meter 'TP_ic'
      TP_ic = ( CBR((IBRCH(1)+21), SS(1)))

! 120:[voltmeter] Voltmeter (Line - Line) 'Vca0'
      Vca0 = EMTDC_VVDC(SS(1), NT_44, NT_42)

! 130:[voltmeter] Voltmeter (Line - Line) 'Grd_Vdc1'
      Grd_Vdc1 = EMTDC_VVDC(SS(1), NT_4, NT_5)

! 140:[ammeter] Current Meter 'Grd_Iac1'
      Grd_Iac1 = (-CBR((IBRCH(1)+30), SS(1)))

! 150:[ammeter] Current Meter 'Grd_Ibc1'
      Grd_Ibc1 = (-CBR((IBRCH(1)+29), SS(1)))

! 170:[ammeter] Current Meter 'Grd_Icc1'
      Grd_Icc1 = (-CBR((IBRCH(1)+28), SS(1)))

! 180:[voltmeter] Voltmeter (Line - Line) 'Grd_Vdc2'
      Grd_Vdc2 = EMTDC_VVDC(SS(1), NT_5, NT_6)

! 190:[voltmeter] Voltmeter (Line - Line) 'BatVolt'
      BatVolt = EMTDC_VVDC(SS(1), NT_16, NT_6)

! 200:[consti] Integer Constant 

      OFP3 = 6300

! 220:[consti] Integer Constant 

      OFP2 = 6160

! 230:[datamerge] Merges data signals into an array 
      RT_36(1) = Grd_Vdc1
      RT_36(2) = Grd_Vdc2

! 240:[consti] Integer Constant 

      OFP1 = 6060

! 250:[consti] Integer Constant 

      UFP1 = 5940

! 260:[consti] Integer Constant 

      UFP2 = 5840

! 270:[ammeter] Current Meter 'Grd_Ib1'
      Grd_Ib1 = ( CBR((IBRCH(1)+24), SS(1)))

! 280:[ammeter] Current Meter 'Grd_Ia1'
      Grd_Ia1 = ( CBR((IBRCH(1)+27), SS(1)))

! 290:[consti] Integer Constant 

      UFP3 = 5780

! 300:[consti] Integer Constant 

      UFP4 = 5730

! 310:[consti] Integer Constant 

      UFP5 = 5700

! 320:[consti] Integer Constant 

      OFP3Timems = 30000

! 330:[consti] Integer Constant 

      OFP2Timems = 300000

! 340:[consti] Integer Constant 

      OFP1Timems = 300000

! 350:[consti] Integer Constant 

      UFP1Timems = 300000

! 360:[datamerge] Merges data signals into an array 
      CapCur(1) = Grd_Ia1
      CapCur(2) = Grd_Ib1

! 370:[consti] Integer Constant 

      UFP2Timems = 300000

! 380:[datamerge] Merges data signals into an array 
      GridVolt(1) = Vab0
      GridVolt(2) = Vbc0

! 390:[consti] Integer Constant 

      UFP3Timems = 300000

! 400:[consti] Integer Constant 

      UFP4Timems = 300000

! 410:[datamerge] Merges data signals into an array 
      BusVolt(1) = Grd_Vdc1
      BusVolt(2) = Grd_Vdc2

! 420:[consti] Integer Constant 

      UFP5Timems = 30000

! 440:[consti] Integer Constant 

      OVP4 = 1300

! 450:[datamerge] Merges data signals into an array 
      ModuleCur(1) = Grd_Iac1
      ModuleCur(2) = Grd_Ibc1
      ModuleCur(3) = Grd_Icc1

! 470:[consti] Integer Constant 

      OVP3 = 1175

! 480:[consti] Integer Constant 

      OVP2 = 1150

! 490:[consti] Integer Constant 

      OVP1 = 1100

! 510:[consti] Integer Constant 

      UVP1 = 900

! 520:[consti] Integer Constant 

      UVP2 = 750

! 540:[consti] Integer Constant 

      UVP3 = 650

! 550:[consti] Integer Constant 

      UVP4 = 450

! 570:[consti] Integer Constant 

      OVP4Timems = 30000

! 580:[consti] Integer Constant 

      VSGEn = 0

! 590:[consti] Integer Constant 

      JCoft = 683999206

! 600:[consti] Integer Constant 

      OVP3Timems = 30000

! 620:[consti] Integer Constant 

      DampCoft = 20000

! 630:[consti] Integer Constant 

      DroopCoft = 28

! 640:[consti] Integer Constant 

      OVP2Timems = 30000

! 650:[consti] Integer Constant 

      GainK = 49

! 660:[consti] Integer Constant 

      CommandWord = 8709

! 670:[consti] Integer Constant 

      OVP1Timems = 30000

! 680:[consti] Integer Constant 

      SetupWord = 34757

! 690:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 700:[consti] Integer Constant 

      UVP1Timems = 30000

! 710:[consti] Integer Constant 

      VgridHpfFreq = 100000

! 720:[consti] Integer Constant 

      SclToBess = 6188

! 730:[consti] Integer Constant 

      UVP2Timems = 30000

! 760:[consti] Integer Constant 

      UVP3Timems = 30000

! 770:[consti] Integer Constant 

      UVP4Timems = 30000

! 780:[FFT_Mod]  
      CALL FFT_ModOut()


! 820:[const] Real Constant 

      RT_25 = 0.0

! 840:[const] Real Constant 

      RT_26 = 0.0

! 930:[const] Real Constant 

      RT_31 = 1000.0

! 940:[const] Real Constant 

      RT_33 = 1000.0

! 970:[const] Real Constant 

      RT_35 = 1000.0

! 980:[datamerge] Merges data signals into an array 
      Vabc1(1) = Vab0
      Vabc1(2) = Vbc0
      Vabc1(3) = Vca0

! 990:[datamerge] Merges data signals into an array 
      RT_8(1) = Grd_Iac1
      RT_8(2) = Grd_Ibc1
      RT_8(3) = Grd_Icc1

! 1000:[datamerge] Merges data signals into an array 
      RT_15(1) = Grd_Iac1
      RT_15(2) = Grd_Ibc1
      RT_15(3) = Grd_Icc1

! 1060:[oc_spov]  
!
      CALL COMPONENT_ID(ICALL_NO,653297001)
      CALL oc_spovOut()
!

! 1160:[breaker3] 3 Phase Breaker 'MCB_DRV'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+18), (IBRCH(1)+19), (IBRCH(1)+20),&
     &0,0,0,IVD1_1,0.02,RVD1_1,RVD1_2)
      IF (UPDATE_AG) THEN
        CALL PSCAD_AGR2(ICALL_NO,36475754,RVD1_1,"P")
        CALL PSCAD_AGR2(ICALL_NO,36475754,RVD1_2,"Q")
      ENDIF
      Qmeas = RVD1_2

! 1170:[special_funcs]  
!
      CALL COMPONENT_ID(ICALL_NO,328370194)
      CALL special_funcsOut()
!

! 1390:[PWM_3Level]  
      CALL PWM_3LevelOut()


! 1810:[pgb] Output Channel 'Grd_Vdc'

      DO IVD1_1 = 1, 2
         PGB(IPGB+85+IVD1_1-1) = RT_36(IVD1_1)
      ENDDO

! 1820:[datamerge] Merges data signals into an array 
      RT_22(1) = Grd_Ia1
      RT_22(2) = Grd_Ib1

! 1830:[pgb] Output Channel 'Icap'

      DO IVD1_1 = 1, 2
         PGB(IPGB+87+IVD1_1-1) = RT_22(IVD1_1)
      ENDDO

! 1840:[pgb] Output Channel 'Iabc2'

      DO IVD1_1 = 1, 3
         PGB(IPGB+89+IVD1_1-1) = RT_15(IVD1_1)
      ENDDO

! 1850:[ThreePhase_3Level]  
      CALL ThreePhase_3LevelOut()


! 1860:[pgb] Output Channel 'Iabc1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+92+IVD1_1-1) = RT_8(IVD1_1)
      ENDDO

! 1870:[breaker3] 3 Phase Breaker 'AMC_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+4), (IBRCH(1)+5), (IBRCH(1)+6),0,0&
     &,0,IVD1_1,0.02,RVD1_1,RVD1_2)

! 1880:[breaker1] Single Phase Breaker 'DCC_EN1'
! Single phase breaker current
!

! 1890:[datamerge] Merges data signals into an array 
      RT_23(1) = TP_ia
      RT_23(2) = TP_ib
      RT_23(3) = TP_ic

! 1900:[pgb] Output Channel 'Igabc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+95+IVD1_1-1) = RT_23(IVD1_1)
      ENDDO

! 1910:[pgb] Output Channel 'Vabc1'

      DO IVD1_1 = 1, 3
         PGB(IPGB+98+IVD1_1-1) = Vabc1(IVD1_1)
      ENDDO

! 1920:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
! Single phase breaker current
!

! 1930:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS(1), (IBRCH(1)+8), (IBRCH(1)+9), (IBRCH(1)+10),0,&
     &0,0,IVD1_1,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 3) = Vab0
      STOF(ISTOF + 4) = Vbc0
      STOF(ISTOF + 27) = Ibat1
      STOF(ISTOF + 28) = BatVolt
      STOF(ISTOF + 29) = Vca0
      STOF(ISTOF + 73) = Grd_Ia1
      STOF(ISTOF + 74) = Grd_Ib1
      STOF(ISTOF + 80) = TP_ia
      STOF(ISTOF + 81) = TP_ib
      STOF(ISTOF + 82) = TP_ic
      STOF(ISTOF + 87) = RT_25
      STOF(ISTOF + 88) = RT_26
      STOI(ISTOI + 3) = VSGEn
      STOI(ISTOI + 4) = VgridHpfFreq
      STOI(ISTOI + 5) = GainK
      STOI(ISTOI + 6) = DroopCoft
      STOI(ISTOI + 7) = DampCoft
      STOI(ISTOI + 8) = JCoft
      STOI(ISTOI + 9) = SclToBess
      STOF(ISTOF + 92) = Tsample
      STOI(ISTOI + 10) = CommandWord
      STOI(ISTOI + 11) = SetupWord
      STOI(ISTOI + 12) = UFP5
      STOI(ISTOI + 13) = UFP4
      STOI(ISTOI + 14) = UFP3
      STOI(ISTOI + 15) = UFP2
      STOI(ISTOI + 16) = OFP3
      STOI(ISTOI + 17) = OFP2
      STOI(ISTOI + 18) = OFP1
      STOI(ISTOI + 19) = UFP1
      STOI(ISTOI + 20) = UFP5Timems
      STOI(ISTOI + 21) = UFP4Timems
      STOI(ISTOI + 22) = UFP3Timems
      STOI(ISTOI + 23) = OFP3Timems
      STOI(ISTOI + 24) = OFP2Timems
      STOI(ISTOI + 25) = OFP1Timems
      STOI(ISTOI + 26) = UFP2Timems
      STOI(ISTOI + 27) = UFP1Timems
      STOI(ISTOI + 28) = UVP4Timems
      STOI(ISTOI + 29) = UVP3Timems
      STOI(ISTOI + 30) = UVP4
      STOI(ISTOI + 31) = UVP3
      STOI(ISTOI + 32) = OVP4
      STOI(ISTOI + 33) = OVP3
      STOI(ISTOI + 34) = OVP2
      STOI(ISTOI + 35) = OVP1
      STOI(ISTOI + 36) = UVP2
      STOI(ISTOI + 37) = UVP1
      STOI(ISTOI + 38) = UVP1Timems
      STOI(ISTOI + 39) = UVP2Timems
      STOI(ISTOI + 40) = OVP4Timems
      STOI(ISTOI + 41) = OVP3Timems
      STOI(ISTOI + 42) = OVP2Timems
      STOI(ISTOI + 43) = OVP1Timems
      STOF(ISTOF + 211) = Grd_Iac1
      STOF(ISTOF + 212) = RT_31
      STOF(ISTOF + 215) = Grd_Ibc1
      STOF(ISTOF + 216) = RT_33
      STOF(ISTOF + 219) = Grd_Icc1
      STOF(ISTOF + 220) = RT_35
      STOF(ISTOF + 231) = Grd_Vdc1
      STOF(ISTOF + 232) = Grd_Vdc2
      STOF(ISTOF + 241) = Qmeas

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 74 + IT_0) = RT_22(IT_0)
         STOF(ISTOF + 162 + IT_0) = CapCur(IT_0)
         STOF(ISTOF + 167 + IT_0) = BusVolt(IT_0)
         STOF(ISTOF + 169 + IT_0) = GridVolt(IT_0)
         STOF(ISTOF + 232 + IT_0) = RT_36(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 29 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 59 + IT_0) = RT_15(IT_0)
         STOF(ISTOF + 76 + IT_0) = RT_23(IT_0)
         STOF(ISTOF + 164 + IT_0) = ModuleCur(IT_0)
         STOF(ISTOF + 234 + IT_0) = TP_iS(IT_0)
         STOF(ISTOF + 237 + IT_0) = Vabc1(IT_0)
         STOF(ISTOF + 261 + IT_0) = TP_iG(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakDyn_Begin  ! 
!     SUBR    FFT_ModDyn_Begin  ! 
!     SUBR    PWM_3LevelDyn_Begin  ! 
!     SUBR    ThreePhase_3LevelDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  VSGEn, VgridHpfFreq, GainK
      INTEGER  DroopCoft, DampCoft, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      REAL     RT_25, RT_26, Tsample, RT_31
      REAL     RT_33, RT_35

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 41
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 47

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakDyn_Begin()


! 100:[breaker3] 3 Phase Breaker 'MCB_DRV1'
      CALL COMPONENT_ID(ICALL_NO,900004966)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 160:[battery] Generic battery model 'Bat2'
      CALL COMPONENT_ID(ICALL_NO,763973743)
      CALL BATTERYCOEFF1_CFG(SS(1), (IBRCH(1)+11),0.675,1.15,1.03,3.26,0&
     &.95,0.4,80.0,0.005,2.0)

! 200:[consti] Integer Constant 
      OFP3 = 6300

! 210:[battery] Generic battery model 'Bat1'
      CALL COMPONENT_ID(ICALL_NO,1412014676)
      CALL BATTERYCOEFF1_CFG(SS(1), (IBRCH(1)+31),0.675,1.15,1.03,3.26,0&
     &.95,0.4,80.0,0.005,2.0)

! 220:[consti] Integer Constant 
      OFP2 = 6160

! 240:[consti] Integer Constant 
      OFP1 = 6060

! 250:[consti] Integer Constant 
      UFP1 = 5940

! 260:[consti] Integer Constant 
      UFP2 = 5840

! 290:[consti] Integer Constant 
      UFP3 = 5780

! 300:[consti] Integer Constant 
      UFP4 = 5730

! 310:[consti] Integer Constant 
      UFP5 = 5700

! 320:[consti] Integer Constant 
      OFP3Timems = 30000

! 330:[consti] Integer Constant 
      OFP2Timems = 300000

! 340:[consti] Integer Constant 
      OFP1Timems = 300000

! 350:[consti] Integer Constant 
      UFP1Timems = 300000

! 370:[consti] Integer Constant 
      UFP2Timems = 300000

! 390:[consti] Integer Constant 
      UFP3Timems = 300000

! 400:[consti] Integer Constant 
      UFP4Timems = 300000

! 420:[consti] Integer Constant 
      UFP5Timems = 30000

! 430:[datamerge] Merges data signals into an array 

! 440:[consti] Integer Constant 
      OVP4 = 1300

! 460:[var] Variable Input Slider 'ActivePowerSet'

! 470:[consti] Integer Constant 
      OVP3 = 1175

! 480:[consti] Integer Constant 
      OVP2 = 1150

! 490:[consti] Integer Constant 
      OVP1 = 1100

! 500:[var] Variable Input Slider 'ReactivePowerSet'

! 510:[consti] Integer Constant 
      UVP1 = 900

! 520:[consti] Integer Constant 
      UVP2 = 750

! 540:[consti] Integer Constant 
      UVP3 = 650

! 550:[consti] Integer Constant 
      UVP4 = 450

! 560:[datatap] Scalar/Array Tap 

! 570:[consti] Integer Constant 
      OVP4Timems = 30000

! 580:[consti] Integer Constant 
      VSGEn = 0

! 590:[consti] Integer Constant 
      JCoft = 683999206

! 600:[consti] Integer Constant 
      OVP3Timems = 30000

! 610:[datatap] Scalar/Array Tap 

! 620:[consti] Integer Constant 
      DampCoft = 20000

! 630:[consti] Integer Constant 
      DroopCoft = 28

! 640:[consti] Integer Constant 
      OVP2Timems = 30000

! 650:[consti] Integer Constant 
      GainK = 49

! 660:[consti] Integer Constant 
      CommandWord = 8709

! 670:[consti] Integer Constant 
      OVP1Timems = 30000

! 680:[consti] Integer Constant 
      SetupWord = 34757

! 690:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 700:[consti] Integer Constant 
      UVP1Timems = 30000

! 710:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 720:[consti] Integer Constant 
      SclToBess = 6188

! 730:[consti] Integer Constant 
      UVP2Timems = 30000

! 740:[pgb] Output Channel 'SOC'

! 750:[signalgen] Signal Generator /w Interpolation 
      CALL COMPONENT_ID(ICALL_NO,540280048)
      CALL E_XSGEN1_CFG(1,0.0,50.0,1.0,-1.0)

! 760:[consti] Integer Constant 
      UVP3Timems = 30000

! 770:[consti] Integer Constant 
      UVP4Timems = 30000

! 780:[FFT_Mod]  
      CALL FFT_ModDyn_Begin()


! 790:[datamerge] Merges data signals into an array 

! 800:[datamerge] Merges data signals into an array 

! 810:[datamerge] Merges data signals into an array 

! 820:[const] Real Constant 
      RT_25 = 0.0

! 830:[pgb] Output Channel 'Vlrms'

! 840:[const] Real Constant 
      RT_26 = 0.0

! 850:[datatap] Scalar/Array Tap 

! 860:[pgb] Output Channel 'P'

! 870:[time-sig] Output of Simulation Time 

! 880:[datatap] Scalar/Array Tap 

! 890:[compare] Single Input Level Comparator 

! 900:[pgb] Output Channel 'Q'

! 910:[datatap] Scalar/Array Tap 

! 920:[pgb] Output Channel 'I_active'

! 930:[const] Real Constant 
      RT_31 = 1000.0

! 940:[const] Real Constant 
      RT_33 = 1000.0

! 950:[datatap] Scalar/Array Tap 

! 960:[pgb] Output Channel 'I_reactive'

! 970:[const] Real Constant 
      RT_35 = 1000.0

! 1010:[datamerge] Merges data signals into an array 

! 1020:[datamerge] Merges data signals into an array 

! 1030:[datamerge] Merges data signals into an array 

! 1040:[datamerge] Merges data signals into an array 

! 1050:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 1060:[oc_spov]  
      CALL COMPONENT_ID(ICALL_NO,653297001)
      CALL oc_spovDyn_Begin()

! 1070:[mult] Multiplier 

! 1080:[mult] Multiplier 

! 1090:[abs] Absolute Value 

! 1100:[abs] Absolute Value 

! 1110:[compare] Single Input Level Comparator 

! 1120:[compare] Single Input Level Comparator 

! 1130:[mult] Multiplier 

! 1140:[abs] Absolute Value 

! 1150:[compare] Single Input Level Comparator 

! 1160:[breaker3] 3 Phase Breaker 'MCB_DRV'
      CALL COMPONENT_ID(ICALL_NO,36475754)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 1170:[special_funcs]  
      CALL COMPONENT_ID(ICALL_NO,328370194)
      CALL special_funcsDyn_Begin()

! 1180:[datamerge] Merges data signals into an array 

! 1190:[Ctrl]  

! 1210:[datatap] Scalar/Array Tap 

! 1230:[datatap] Scalar/Array Tap 

! 1240:[datatap] Scalar/Array Tap 

! 1250:[datatap] Scalar/Array Tap 

! 1300:[datatap] Scalar/Array Tap 

! 1310:[datamerge] Merges data signals into an array 

! 1320:[datatap] Scalar/Array Tap 

! 1330:[datatap] Scalar/Array Tap 

! 1340:[datatap] Scalar/Array Tap 

! 1350:[datatap] Scalar/Array Tap 

! 1360:[realpole] Real Pole 

! 1370:[pgb] Output Channel 'Qref'

! 1380:[datatap] Scalar/Array Tap 

! 1390:[PWM_3Level]  
      CALL PWM_3LevelDyn_Begin()


! 1400:[pgb] Output Channel 'PWM_Mod'

! 1410:[pgb] Output Channel 'Triasign_PWM'

! 1420:[datatap] Scalar/Array Tap 

! 1430:[datatap] Scalar/Array Tap 

! 1440:[datamerge] Merges data signals into an array 

! 1450:[datatap] Scalar/Array Tap 

! 1460:[pgb] Output Channel 'DebugData2'

! 1470:[pgb] Output Channel 'DebugData1'

! 1480:[datatap] Scalar/Array Tap 

! 1490:[datatap] Scalar/Array Tap 

! 1500:[datatap] Scalar/Array Tap 

! 1510:[datatap] Scalar/Array Tap 

! 1520:[pgb] Output Channel 'T4'

! 1530:[datatap] Scalar/Array Tap 

! 1540:[datatap] Scalar/Array Tap 

! 1550:[datatap] Scalar/Array Tap 

! 1560:[datatap] Scalar/Array Tap 

! 1570:[pgb] Output Channel 'T3'

! 1580:[datatap] Scalar/Array Tap 

! 1590:[pgb] Output Channel 'PCS Fault'

! 1600:[datatap] Scalar/Array Tap 

! 1610:[pgb] Output Channel 'T2'

! 1620:[pgb] Output Channel 'T7'

! 1630:[datatap] Scalar/Array Tap 

! 1640:[pgb] Output Channel 'T1'

! 1650:[datatap] Scalar/Array Tap 

! 1660:[datatap] Scalar/Array Tap 

! 1670:[datatap] Scalar/Array Tap 

! 1680:[datatap] Scalar/Array Tap 

! 1690:[datatap] Scalar/Array Tap 

! 1700:[pgb] Output Channel 'iRabs'

! 1710:[datatap] Scalar/Array Tap 

! 1720:[datatap] Scalar/Array Tap 

! 1730:[pgb] Output Channel 'OcpEn'

! 1740:[pgb] Output Channel 'PWM1'

! 1750:[pgb] Output Channel 'PWM'

! 1760:[pgb] Output Channel 'MCB'

! 1770:[pgb] Output Channel 'MC'

! 1780:[pgb] Output Channel 'DC_EN'

! 1790:[pgb] Output Channel 'DC_SS_EN'

! 1800:[pgb] Output Channel 'AC_SS_EN'

! 1850:[ThreePhase_3Level]  
      CALL ThreePhase_3LevelDyn_Begin()


! 1870:[breaker3] 3 Phase Breaker 'AMC_DRV1'
      CALL COMPONENT_ID(ICALL_NO,1569782592)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 1880:[breaker1] Single Phase Breaker 'DCC_EN1'
      CALL COMPONENT_ID(ICALL_NO,243978139)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 1920:[breaker1] Single Phase Breaker 'DCC_SS_EN1'
      CALL COMPONENT_ID(ICALL_NO,196338356)
      CALL E1PBRKR1_CFG(0.005,1000000.0,0.0)

! 1930:[breaker3] 3 Phase Breaker 'ACSSC_DRV1'
      CALL COMPONENT_ID(ICALL_NO,410852369)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    breakOut_Begin  ! 
!     SUBR    FFT_ModOut_Begin  ! 
!     SUBR    PWM_3LevelOut_Begin  ! 
!     SUBR    ThreePhase_3LevelOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_4, NT_5, NT_6, NT_16, NT_42
      INTEGER  NT_43, NT_44

! Control Signals
      INTEGER  VSGEn, VgridHpfFreq, GainK
      INTEGER  DroopCoft, DampCoft, JCoft
      INTEGER  SclToBess, CommandWord, SetupWord
      INTEGER  UFP5, UFP4, UFP3, UFP2, OFP3, OFP2
      INTEGER  OFP1, UFP1, UFP5Timems, UFP4Timems
      INTEGER  UFP3Timems, OFP3Timems, OFP2Timems
      INTEGER  OFP1Timems, UFP2Timems, UFP1Timems
      INTEGER  UVP4Timems, UVP3Timems, UVP4, UVP3
      INTEGER  OVP4, OVP3, OVP2, OVP1, UVP2, UVP1
      INTEGER  UVP1Timems, UVP2Timems, OVP4Timems
      INTEGER  OVP3Timems, OVP2Timems, OVP1Timems
      REAL     RT_25, RT_26, Tsample, RT_31
      REAL     RT_33, RT_35

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 41
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 47

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_4  = NODE(INODE + 10)
      NT_5  = NODE(INODE + 11)
      NT_6  = NODE(INODE + 12)
      NT_16 = NODE(INODE + 29)
      NT_42 = NODE(INODE + 17)
      NT_43 = NODE(INODE + 18)
      NT_44 = NODE(INODE + 19)

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[break]  
      CALL breakOut_Begin()


! 200:[consti] Integer Constant 
      OFP3 = 6300

! 220:[consti] Integer Constant 
      OFP2 = 6160

! 230:[datamerge] Merges data signals into an array 

! 240:[consti] Integer Constant 
      OFP1 = 6060

! 250:[consti] Integer Constant 
      UFP1 = 5940

! 260:[consti] Integer Constant 
      UFP2 = 5840

! 290:[consti] Integer Constant 
      UFP3 = 5780

! 300:[consti] Integer Constant 
      UFP4 = 5730

! 310:[consti] Integer Constant 
      UFP5 = 5700

! 320:[consti] Integer Constant 
      OFP3Timems = 30000

! 330:[consti] Integer Constant 
      OFP2Timems = 300000

! 340:[consti] Integer Constant 
      OFP1Timems = 300000

! 350:[consti] Integer Constant 
      UFP1Timems = 300000

! 360:[datamerge] Merges data signals into an array 

! 370:[consti] Integer Constant 
      UFP2Timems = 300000

! 380:[datamerge] Merges data signals into an array 

! 390:[consti] Integer Constant 
      UFP3Timems = 300000

! 400:[consti] Integer Constant 
      UFP4Timems = 300000

! 410:[datamerge] Merges data signals into an array 

! 420:[consti] Integer Constant 
      UFP5Timems = 30000

! 440:[consti] Integer Constant 
      OVP4 = 1300

! 450:[datamerge] Merges data signals into an array 

! 470:[consti] Integer Constant 
      OVP3 = 1175

! 480:[consti] Integer Constant 
      OVP2 = 1150

! 490:[consti] Integer Constant 
      OVP1 = 1100

! 510:[consti] Integer Constant 
      UVP1 = 900

! 520:[consti] Integer Constant 
      UVP2 = 750

! 540:[consti] Integer Constant 
      UVP3 = 650

! 550:[consti] Integer Constant 
      UVP4 = 450

! 570:[consti] Integer Constant 
      OVP4Timems = 30000

! 580:[consti] Integer Constant 
      VSGEn = 0

! 590:[consti] Integer Constant 
      JCoft = 683999206

! 600:[consti] Integer Constant 
      OVP3Timems = 30000

! 620:[consti] Integer Constant 
      DampCoft = 20000

! 630:[consti] Integer Constant 
      DroopCoft = 28

! 640:[consti] Integer Constant 
      OVP2Timems = 30000

! 650:[consti] Integer Constant 
      GainK = 49

! 660:[consti] Integer Constant 
      CommandWord = 8709

! 670:[consti] Integer Constant 
      OVP1Timems = 30000

! 680:[consti] Integer Constant 
      SetupWord = 34757

! 690:[delta-t] Output of Simulation Time-Step (DELT) 
      Tsample = DELT

! 700:[consti] Integer Constant 
      UVP1Timems = 30000

! 710:[consti] Integer Constant 
      VgridHpfFreq = 100000

! 720:[consti] Integer Constant 
      SclToBess = 6188

! 730:[consti] Integer Constant 
      UVP2Timems = 30000

! 760:[consti] Integer Constant 
      UVP3Timems = 30000

! 770:[consti] Integer Constant 
      UVP4Timems = 30000

! 780:[FFT_Mod]  
      CALL FFT_ModOut_Begin()


! 820:[const] Real Constant 
      RT_25 = 0.0

! 840:[const] Real Constant 
      RT_26 = 0.0

! 930:[const] Real Constant 
      RT_31 = 1000.0

! 940:[const] Real Constant 
      RT_33 = 1000.0

! 970:[const] Real Constant 
      RT_35 = 1000.0

! 980:[datamerge] Merges data signals into an array 

! 990:[datamerge] Merges data signals into an array 

! 1000:[datamerge] Merges data signals into an array 

! 1060:[oc_spov]  
      CALL COMPONENT_ID(ICALL_NO,653297001)
      CALL oc_spovOut_Begin()

! 1170:[special_funcs]  
      CALL COMPONENT_ID(ICALL_NO,328370194)
      CALL special_funcsOut_Begin()

! 1390:[PWM_3Level]  
      CALL PWM_3LevelOut_Begin()


! 1810:[pgb] Output Channel 'Grd_Vdc'

! 1820:[datamerge] Merges data signals into an array 

! 1830:[pgb] Output Channel 'Icap'

! 1840:[pgb] Output Channel 'Iabc2'

! 1850:[ThreePhase_3Level]  
      CALL ThreePhase_3LevelOut_Begin()


! 1860:[pgb] Output Channel 'Iabc1'

! 1890:[datamerge] Merges data signals into an array 

! 1900:[pgb] Output Channel 'Igabc'

! 1910:[pgb] Output Channel 'Vabc1'

      RETURN
      END

