!=======================================================================
! Generated by: PSCAD v5.0.2.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : ThreePhase_3Level
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE ThreePhase_3LevelDyn(PWM)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: PWM(12)

! Electrical Node Indices

! Control Signals
      INTEGER  sa_au, sa_ad, sb_ad, sb_au, sc_ad
      INTEGER  sc_au
      REAL     sa_m2, sa_b, sb_u, sb_m1, sa_u
      REAL     sa_m1, sb_m2, sb_b, sc_u, sc_m2
      REAL     sc_b, sc_m1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 24
      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 54

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      sa_m2    = STOF(ISTOF + 13)
      sa_b     = STOF(ISTOF + 14)
      sb_u     = STOF(ISTOF + 15)
      sb_m1    = STOF(ISTOF + 16)
      sa_au    = STOI(ISTOI + 1)
      sa_ad    = STOI(ISTOI + 2)
      sb_ad    = STOI(ISTOI + 3)
      sb_au    = STOI(ISTOI + 4)
      sc_ad    = STOI(ISTOI + 5)
      sc_au    = STOI(ISTOI + 6)
      sa_u     = STOF(ISTOF + 17)
      sa_m1    = STOF(ISTOF + 18)
      sb_m2    = STOF(ISTOF + 19)
      sb_b     = STOF(ISTOF + 20)
      sc_u     = STOF(ISTOF + 21)
      sc_m2    = STOF(ISTOF + 22)
      sc_b     = STOF(ISTOF + 23)
      sc_m1    = STOF(ISTOF + 24)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'ThreePhase_3Level.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 
      sa_u = PWM(1)

! 30:[consti] Integer Constant 
      sa_au = 0

! 40:[datatap] Scalar/Array Tap 
      sa_m1 = PWM(2)

! 50:[consti] Integer Constant 
      sa_ad = 0

! 60:[datatap] Scalar/Array Tap 
      sa_m2 = PWM(3)

! 70:[consti] Integer Constant 
      sb_au = 0

! 80:[datatap] Scalar/Array Tap 
      sa_b = PWM(4)

! 90:[consti] Integer Constant 
      sb_ad = 0

! 100:[datatap] Scalar/Array Tap 
      sb_u = PWM(5)

! 110:[consti] Integer Constant 
      sc_au = 0

! 120:[datatap] Scalar/Array Tap 
      sb_m1 = PWM(6)

! 130:[consti] Integer Constant 
      sc_ad = 0

! 140:[datatap] Scalar/Array Tap 
      sb_m2 = PWM(7)

! 150:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,566812718)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+1), NINT(sa_u), 0.0)

! 160:[datatap] Scalar/Array Tap 
      sb_b = PWM(8)

! 170:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,2004566266)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+17), NINT(sb_u), 0.0)

! 180:[datatap] Scalar/Array Tap 
      sc_u = PWM(9)

! 190:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,699832633)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+29), NINT(sc_u), 0.0)

! 200:[datatap] Scalar/Array Tap 
      sc_m1 = PWM(10)

! 210:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,2011945410)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+13), sa_au, 0.0)

! 220:[datatap] Scalar/Array Tap 
      sc_m2 = PWM(11)

! 230:[datatap] Scalar/Array Tap 
      sc_b = PWM(12)

! 240:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,719388580)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+50), sb_au, 0.0)

! 250:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,220312489)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+44), sc_au, 0.0)

! 260:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,717405171)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+4), NINT(sa_m1), 0.0)

! 270:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,2062558870)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+20), NINT(sb_m1), 0.0)

! 280:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,272639436)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+32), NINT(sc_m1), 0.0)

! 290:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1558446162)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+7), NINT(sa_m2), 0.0)

! 300:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,503715766)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+23), NINT(sb_m2), 0.0)

! 310:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,711202599)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+35), NINT(sc_m2), 0.0)

! 320:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,449464512)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+15), sa_ad, 0.0)

! 330:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1060526691)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+47), sb_ad, 0.0)

! 340:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1242801377)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+41), sc_ad, 0.0)

! 350:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,550061472)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+10), NINT(sa_b), 0.0)

! 360:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,918577049)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+26), NINT(sb_b), 0.0)

! 370:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1421291493)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+38), NINT(sc_b), 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,144338258)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+3), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,682011367)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+19), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,632746732)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+31), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1196720219)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+53), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1028487589)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+52), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1560517851)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+46), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,294439875)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+6), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,545129163)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+22), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,379042079)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+34), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1362193661)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+9), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,661737509)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+54), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,2029080758)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+25), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,2048447616)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+49), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,952991096)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+37), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1291354108)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+43), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1883078135)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+12), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1989308212)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+28), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1939594590)
      CALL PESWITCH1_EXE(SS(1), (IBRCH(1)+40), 1, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 13) = sa_m2
      STOF(ISTOF + 14) = sa_b
      STOF(ISTOF + 15) = sb_u
      STOF(ISTOF + 16) = sb_m1
      STOI(ISTOI + 1) = sa_au
      STOI(ISTOI + 2) = sa_ad
      STOI(ISTOI + 3) = sb_ad
      STOI(ISTOI + 4) = sb_au
      STOI(ISTOI + 5) = sc_ad
      STOI(ISTOI + 6) = sc_au
      STOF(ISTOF + 17) = sa_u
      STOF(ISTOF + 18) = sa_m1
      STOF(ISTOF + 19) = sb_m2
      STOF(ISTOF + 20) = sb_b
      STOF(ISTOF + 21) = sc_u
      STOF(ISTOF + 22) = sc_m2
      STOF(ISTOF + 23) = sc_b
      STOF(ISTOF + 24) = sc_m1

! Array (1:12) quantities...
      DO IT_0 = 1,12
         STOF(ISTOF + 0 + IT_0) = PWM(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE ThreePhase_3LevelOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  sa_au, sa_ad, sb_ad, sb_au, sc_ad
      INTEGER  sc_au

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 54

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      sa_au    = STOI(ISTOI + 1)
      sa_ad    = STOI(ISTOI + 2)
      sb_ad    = STOI(ISTOI + 3)
      sb_au    = STOI(ISTOI + 4)
      sc_ad    = STOI(ISTOI + 5)
      sc_au    = STOI(ISTOI + 6)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'ThreePhase_3Level.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 

      sa_au = 0

! 50:[consti] Integer Constant 

      sa_ad = 0

! 70:[consti] Integer Constant 

      sb_au = 0

! 90:[consti] Integer Constant 

      sb_ad = 0

! 110:[consti] Integer Constant 

      sc_au = 0

! 130:[consti] Integer Constant 

      sc_ad = 0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = sa_au
      STOI(ISTOI + 2) = sa_ad
      STOI(ISTOI + 3) = sb_ad
      STOI(ISTOI + 4) = sb_au
      STOI(ISTOI + 5) = sc_ad
      STOI(ISTOI + 6) = sc_au


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE ThreePhase_3LevelDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  sa_au, sa_ad, sb_ad, sb_au, sc_ad
      INTEGER  sc_au

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 54

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

! 30:[consti] Integer Constant 
      sa_au = 0

! 40:[datatap] Scalar/Array Tap 

! 50:[consti] Integer Constant 
      sa_ad = 0

! 60:[datatap] Scalar/Array Tap 

! 70:[consti] Integer Constant 
      sb_au = 0

! 80:[datatap] Scalar/Array Tap 

! 90:[consti] Integer Constant 
      sb_ad = 0

! 100:[datatap] Scalar/Array Tap 

! 110:[consti] Integer Constant 
      sc_au = 0

! 120:[datatap] Scalar/Array Tap 

! 130:[consti] Integer Constant 
      sc_ad = 0

! 140:[datatap] Scalar/Array Tap 

! 150:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+2),SS(1),1,0,1,100000.0,0.0,2.0)

! 160:[datatap] Scalar/Array Tap 

! 170:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+18),SS(1),1,0,1,100000.0,0.0,2.0)

! 180:[datatap] Scalar/Array Tap 

! 190:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+30),SS(1),1,0,1,100000.0,0.0,2.0)

! 200:[datatap] Scalar/Array Tap 

! 210:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+14),SS(1),1,0,1,100000.0,0.0,2.0)

! 220:[datatap] Scalar/Array Tap 

! 230:[datatap] Scalar/Array Tap 

! 240:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+51),SS(1),1,0,1,100000.0,0.0,2.0)

! 250:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+45),SS(1),1,0,1,100000.0,0.0,2.0)

! 260:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+5),SS(1),1,0,1,100000.0,0.0,2.0)

! 270:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+21),SS(1),1,0,1,100000.0,0.0,2.0)

! 280:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+33),SS(1),1,0,1,100000.0,0.0,2.0)

! 290:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+8),SS(1),1,0,1,100000.0,0.0,2.0)

! 300:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+24),SS(1),1,0,1,100000.0,0.0,2.0)

! 310:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+36),SS(1),1,0,1,100000.0,0.0,2.0)

! 320:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+16),SS(1),1,0,1,100000.0,0.0,2.0)

! 330:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+48),SS(1),1,0,1,100000.0,0.0,2.0)

! 340:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+42),SS(1),1,0,1,100000.0,0.0,2.0)

! 350:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+11),SS(1),1,0,1,100000.0,0.0,2.0)

! 360:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+27),SS(1),1,0,1,100000.0,0.0,2.0)

! 370:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)
      CALL E_BRANCH_CFG( (IBRCH(1)+39),SS(1),1,0,1,100000.0,0.0,2.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.01, 1000000.0, 100000.0, 100000.0, 0.0, &
     &0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE ThreePhase_3LevelOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  sa_au, sa_ad, sb_ad, sb_au, sc_ad
      INTEGER  sc_au

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ISUBS, SS(1), IBRCH(1), INODE       ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 14
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

! Initialize Subsystem Mapping

      ISUBS = NSUBS + 0
      NSUBS = NSUBS + 1

      DO IT_0 = 1,1
         SS(IT_0) = SUBS(ISUBS + IT_0)
      END DO

! Initialize Branch Mapping.

      IBRCH(1)     = NBRCH(SS(1))
      NBRCH(SS(1)) = NBRCH(SS(1)) + 54

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 
      sa_au = 0

! 50:[consti] Integer Constant 
      sa_ad = 0

! 70:[consti] Integer Constant 
      sb_au = 0

! 90:[consti] Integer Constant 
      sb_ad = 0

! 110:[consti] Integer Constant 
      sc_au = 0

! 130:[consti] Integer Constant 
      sc_ad = 0

      RETURN
      END

